// English. Content: Inner Development Guide 2.0 (version 7.2) — 25 skills in five
// dimensions. The framework layer (dimension names, subtitles, intros, skill names
// and descriptions) is taken verbatim from the official English edition.
//
// One change to that source: the typographic apostrophe (U+02BC) it uses in
// "one's" and "planet's" is normalised to the plain apostrophe used elsewhere here.
//
// The reflection questions, classroom ideas, subject links and mini-exercises are
// not part of the IDG framework — they were written for this app and are translated
// from the German original. Swiss curriculum subjects have been generalised.
export const ui = {
  appName: "Inner Development Guide",
  appNameSub: "in the classroom",
  tagline: "25 skills. One card at a time.",
  intro: "The Inner Development Guide 2.0 describes inner abilities we need in order to shape change. These cards translate them into your teaching day.",
  tabs: { stack: "Deck", dimensions: "Dimensions", saved: "Saved", settings: "Settings" },
  language: "Language",
  cardDesign: "Card design",
  variantFarbe: "Colour card",
  variantPapier: "Paper card",
  flipDirection: "Flip",
  flipH: "Horizontal",
  flipV: "Vertical",
  clearSaved: "Clear saved cards",
  cleared: "Saved cards cleared",
  about: "This app makes the Inner Development Guide accessible to teachers: 25 skills, each with reflection questions for you and for your class, plus ideas for the classroom.",
  cardOfDay: "Card of the day",
  random: "Random card",
  flipHint: "Tap to flip",
  swipeHint: "Swipe right to save",
  savedToast: "Saved",
  front: "Skill",
  back: "For the classroom",
  forMe: "For me",
  forStudents: "For my class",
  ideas: "In the classroom",
  sheetSub: "Ideas, subject links and a mini-exercise",
  subjects: "Subject links",
  exercise: "Mini-exercise · 5 minutes",
  save: "Save",
  saved: "Saved",
  share: "Share",
  shared: "Copied",
  next: "Next",
  prev: "Back",
  emptySaved: "No cards saved yet.",
  emptySavedHint: "Tap “Save” when a card should stay with you.",
  skillsCount: "skills",
  ofCards: "of",
  attribution: "This work is inspired by the Inner Development Guide. More at innerdevelopmentgoals.org",
  dimensionLabel: "Dimension",
  allCards: "All cards",
  close: "Close",
  level: "Primary to upper secondary",
  orderRandom: "Random order",
  orderGuide: "Order as in the guide",
  on: "On",
  off: "Off",
  tapNext: "Tap for the next question",
  // The four-step intro tour (IdgCards.jsx#tourSteps) — see the comment in
  // content/de.js. `ofCards` (above, "of") supplies the connector for the
  // step indicator "{n} of {tourSteps.length}".
  tourStep1Title: "Flip the card",
  tourStep1Text: "Tap the card: the skill up front, reflection questions for you and your class on the back.",
  tourStep2Title: "Browse the deck",
  tourStep2Text: "Swipe the card left or right. The dots at the top show where you are in the deck.",
  tourStep3Title: "Save cards",
  tourStep3Text: "The circle at the top right of the card fills in and adds it to your saved cards.",
  tourStep4Title: "Everything else in the menu",
  tourStep4Text: "Behind the rings at the top right you'll find dimensions, saved cards, order and settings.",
  tourSkip: "Skip",
  tourNext: "Next",
  tourDone: "Let's go"
};

export const dimensions = [
  { id: "being", num: 1, name: "Being", subtitle: "Cultivating Our Inner Life", color: "#D4B88C",
    intro: "Deepening our awareness of inner experiences and their dynamic relationship with the world around us nurtures embodied presence, clarity of purpose, and thoughtful responses when we face complexity." },
  { id: "thinking", num: 2, name: "Thinking", subtitle: "Understanding Our Complex World", color: "#E585A1",
    intro: "Expanding clarity, considering diverse perspectives, and imagining long-term consequences help us navigate complexity and make wiser decisions in our interconnected world." },
  { id: "relating", num: 3, name: "Relating", subtitle: "Caring for Others and the World", color: "#EF4136",
    intro: "Connecting with kindness, compassion, and a sense of shared belonging to communities, the living planet, and future generations helps us to create a more just, inclusive, and flourishing world." },
  { id: "collaborating", num: 4, name: "Collaborating", subtitle: "Building Trust and Working Together", color: "#FF7E2A",
    intro: "Developing relationships of trust, acknowledging diverse values, skills, and perspectives, and creating safe spaces enables everyone to contribute to shared purposes and collective impact." },
  { id: "acting", num: 5, name: "Acting", subtitle: "Leading and Enabling Change", color: "#661A30",
    intro: "Moving forward with courage and optimism, building collective agency, and acting with purpose and persistence turns visions into meaningful change in uncertain times." }
];

export const skills = [
  { id: "innerer-kompass", dim: "being", name: "Inner Compass", icon: "innerer-kompass",
    desc: "A deeply felt commitment to live and act in accordance with values and purposes that serve the good of the whole.",
    teacher: ["Which value guided my decisions in the classroom today – and where did I depart from it?", "Why did I become a teacher? How much of that was noticeable this week?"],
    students: ["What matters so much to you that you would stand up for it?", "How do you notice that something feels right or wrong to you?"],
    ideas: ["Map of values: the class collects values on cards and sorts them together – what connects us, where do we differ?", "Don't hand down class rules; derive them from the shared values."],
    subjects: ["Ethics & citizenship", "Class time", "Language arts"],
    exercise: { title: "My sentence for today", text: "Everyone writes down in one sentence what matters to them today. Reading out is voluntary. At the end of the day, check briefly: did it hold?" } },
  { id: "integritaet-und-authentizitaet", dim: "being", name: "Integrity and Authenticity", icon: "integritaet-und-authentizitaet",
    desc: "A sincere commitment to honesty and firmly grounded values, expressed and embodied in action.",
    teacher: ["When did I last admit to the class that I didn't know something or had made a mistake?", "Where do I say things I don't quite mean myself – and why?"],
    students: ["When is it hard for you to be honest?", "What does being yourself mean to you?"],
    ideas: ["Make a culture of mistakes visible: a wall of “mistakes we learned from”.", "Discuss dilemma stories: what would you do if nobody found out?"],
    subjects: ["Ethics & citizenship", "Language arts", "Class time"],
    exercise: { title: "An honest answer", text: "To “How are you?” everyone answers honestly for once instead of “fine”. Two minutes of silence, then share in pairs." } },
  { id: "offenheit-und-lernbereitschaft", dim: "being", name: "Openness and Learning Mindset", icon: "offenheit-und-lernbereitschaft",
    desc: "A curious, adaptive attitude expressed through willingness to exchange perspectives, be vulnerable, welcome change, and grow.",
    teacher: ["What did I learn from my students this week?", "Which teaching routine do I keep because I have always done it that way?"],
    students: ["When did you last change your mind? What convinced you?", "What would you like to learn even if nobody asked you to?"],
    ideas: ["Swap roles: students teach the teacher something they are good at.", "Introduce “I don't know yet” cards as a permitted answer in class."],
    subjects: ["All subjects", "Class time", "Project work"],
    exercise: { title: "A curious question", text: "Everyone writes down a question they have no answer to. Questions go on the wall – one is chosen together and followed up during the week." } },
  { id: "selbsterkenntnis", dim: "being", name: "Self-Awareness", icon: "selbsterkenntnis",
    desc: "Ability to be in reflective contact with thoughts, emotions, desires, and actions; to maintain a realistic self-image and to regulate oneself.",
    teacher: ["Which classroom situations throw me off balance – and what lies behind that?", "How do I react under stress, and how much of it does my class pick up?"],
    students: ["How do you notice in your body that you are getting angry or nervous?", "What are you good at – and how do you know?"],
    ideas: ["A feelings check-in at the start of the lesson using weather cards or a scale from 1 to 5.", "A learning journal with a weekly question: what helped me today, what slowed me down?"],
    subjects: ["Class time", "Science & society", "Physical education"],
    exercise: { title: "Inner weather", text: "Close your eyes, take three breaths. What is my weather right now – sunny, cloudy, stormy? Anyone who wants to shares it in one word." } },
  { id: "praesenz", dim: "being", name: "Presence", icon: "praesenz",
    desc: "Capacity to be fully present in the here and now, to accept reality as it unfolds, and to respond in meaningful ways.",
    teacher: ["How often am I already thinking about the next lesson during this one?", "When did I truly listen to a student today – without already knowing the answer?"],
    students: ["When were you last so absorbed that you forgot the time?", "What can you hear right now if you stay completely still for a minute?"],
    ideas: ["A minute of silence as a fixed ritual after break.", "Mindful observation in nature or art: five minutes of just looking, then describing."],
    subjects: ["Physical education", "Visual arts", "Music", "Science & society"],
    exercise: { title: "Five senses", text: "One after another: what do I see, hear, feel, smell, taste? Thirty seconds each, without judging." } },

  { id: "kritisches-denken", dim: "thinking", name: "Critical Thinking", icon: "kritisches-denken",
    desc: "Ability to reflect on the validity of ideas, evidence, assumptions and plans.",
    teacher: ["Which assumptions about my class have I not questioned lately?", "Where do I allow disagreement in class – and where do I unknowingly shut it down?"],
    students: ["How do you know that is true?", "Who has an interest in you believing that?"],
    ideas: ["Fake-news check: compare two reports, examine the sources, develop criteria.", "A debate format with side-swapping – every position is argued once."],
    subjects: ["Media & IT", "Language arts", "History & geography", "Science & technology"],
    exercise: { title: "Three questions for a claim", text: "Put a statement on the board. In groups: where does it come from? What speaks against it? What would we need to know to be sure?" } },
  { id: "perspektivische-faehigkeiten", dim: "thinking", name: "Perspective Skills", icon: "perspektivische-faehigkeiten",
    desc: "Ability to learn from diverse perspectives and integrate insights into reflective sense-making and action.",
    teacher: ["What does my lesson look like from the perspective of the quietest child?", "What story am I telling myself about my class – and does it still hold?"],
    students: ["How would this story sound if another character told it?", "What might someone think whose life is completely different from yours?"],
    ideas: ["Retell texts or historical events from the viewpoint of a minor character.", "Opinion line: position yourself in the room on a statement and talk with someone at the other end."],
    subjects: ["Language arts", "History & geography", "Foreign languages", "Ethics & citizenship"],
    exercise: { title: "Change chairs", text: "Discuss a topic in pairs. After two minutes swap places – and carry on from the other person's position." } },
  { id: "systemisches-denken", dim: "thinking", name: "Systems Thinking", icon: "systemisches-denken",
    desc: "Ability to understand complexity and work with the interconnections and properties of systems.",
    teacher: ["Which problem in my class am I trying to fix with a simple solution although it has many causes?", "Which connections outside school reach into my teaching?"],
    students: ["What all happens when one thing happens?", "Which pattern do you recognise here – and where have you seen it before?"],
    ideas: ["A web of effects instead of a summary: one topic (e.g. classroom noise, plastic) in the middle, causes and consequences as arrows – draw the connections, don't list them.", "A systems game: everyone is part of a cycle and experiences how a change is passed along. Afterwards look for the leverage point."],
    subjects: ["Science & society", "History & geography", "Economics & practical skills", "Science & technology"],
    exercise: { title: "And then?", text: "Name a change (e.g. “there is no more homework”). Ask around the circle: and then? Five rounds, until the consequences surprise you." } },
  { id: "langfristige-orientierung", dim: "thinking", name: "Long-Term Orientation and Visioning", icon: "langfristige-orientierung",
    desc: "Imagining long-term goals and staying committed to them in ways that support broader societal and ecological well-being.",
    teacher: ["What should my students still carry from my teaching in twenty years?", "Where am I optimising for the next test instead of for lasting understanding?"],
    students: ["What should your neighbourhood look like in 30 years?", "What would you like people to say later about your generation?"],
    ideas: ["Start the lesson with “why are we learning this?” and let the class answer it at the end – what of it lasts beyond the school year?", "A futures workshop: critique – vision – implementation, on a topic that concerns the class."],
    subjects: ["History & geography", "Language arts", "Project work", "Careers guidance"],
    exercise: { title: "Time travel", text: "Close your eyes: it is the year 2050. What has got better? Who contributed? One sentence each." } },
  { id: "kreativitaet", dim: "thinking", name: "Creativity", icon: "kreativitaet",
    desc: "Ability to think outside conventional patterns, imagine new possibilities, and shape them into transformative ideas.",
    teacher: ["When were my students last allowed to make something that doesn't exist yet?", "Which task did I set this week so that only one answer is right – and did it have to be that way?"],
    students: ["How could this be solved completely differently?", "What would you invent if anything were possible?"],
    ideas: ["Open tasks with several routes to a solution – especially in mathematics.", "Reversal exercise: an everyday object gets a new purpose."],
    subjects: ["Visual arts", "Mathematics", "Design & technology", "Music"],
    exercise: { title: "30 circles", text: "A sheet with 30 empty circles. In three minutes turn as many as possible into something – a ball, a clock, a pizza. Quantity before quality." } },

  { id: "wertschaetzung", dim: "relating", name: "Appreciation", icon: "wertschaetzung",
    desc: "Relating to people and planet Earth with a deep sense of gratitude, positive regard, and joy.",
    teacher: ["Who in my class have I not said anything appreciative to this week?", "What am I grateful for in my profession – even on hard days?"],
    students: ["Who helped you today without it being noticed?", "What do you take for granted that is actually special?"],
    ideas: ["Warm shower: one person sits in the middle, everyone names something they value about them.", "A gratitude wall in the classroom, added to weekly."],
    subjects: ["Class time", "Ethics & citizenship", "Language arts"],
    exercise: { title: "Three good things", text: "Everyone writes down three things that were good today – however small. Share one of them with your neighbour." } },
  { id: "verbundenheit", dim: "relating", name: "Connectedness", icon: "verbundenheit",
    desc: "Feeling a sense of belonging to a larger whole, such as humanity, the planet's web of life, and the spiritual dimensions of existence.",
    teacher: ["Does every child in my class feel part of the group? How do I know?", "Where do I feel connected myself – to the staff, the school, the place?"],
    students: ["Who or what do you belong to?", "What connects you with a child on another continent?"],
    ideas: ["Trace an everyday object back to its origin: who all contributed to it?", "A class partnership with a school in another country or region."],
    subjects: ["Science & society", "History & geography", "Foreign languages"],
    exercise: { title: "Web of yarn", text: "In a circle: a ball of yarn is thrown. Whoever catches it names something they have in common with the person who threw it. In the end everyone holds a web." } },
  { id: "demut-und-bescheidenheit", dim: "relating", name: "Humility", icon: "demut-und-bescheidenheit",
    desc: "Being able to respond to the needs of the situation without concern for one's own importance.",
    teacher: ["How much do I talk in a lesson, how much does the class?", "When did I last prefer a student's idea to my own?"],
    students: ["When does it matter more that the group moves on than that you are right?", "What can others do better than you – and how does that feel?"],
    ideas: ["Silent discussion on paper: every voice gets the same amount of space.", "Rotate roles in group work, including the inconspicuous ones."],
    subjects: ["Class time", "Physical education", "All subjects"],
    exercise: { title: "Listening without answering", text: "In pairs: one person talks for two minutes, the other only listens – no comment, no advice. Then swap. How was it?" } },
  { id: "empathie-und-mitgefuehl", dim: "relating", name: "Empathy and Compassion", icon: "empathie-und-mitgefuehl",
    desc: "Connecting to others, oneself, and nature with kindness, care, and love, guided by the intention to reduce suffering.",
    teacher: ["Which behaviour in my class annoys me – and which need might sit behind it?", "How do I treat myself when a lesson goes wrong?"],
    students: ["How do you notice that someone is not doing well?", "What helps you when you are sad – and could it help others too?"],
    ideas: ["Widen the vocabulary of feelings: describe pictures or scenes, collect precise words.", "Change of perspective in conflicts: both sides write down what the other probably felt."],
    subjects: ["Language arts", "Ethics & citizenship", "Class time", "Visual arts"],
    exercise: { title: "A kind thought", text: "Everyone thinks of someone who is having a hard time. Silently form a good wish for them. Then direct the same wish at yourself." } },
  { id: "vergebung", dim: "relating", name: "Forgiveness", icon: "vergebung",
    desc: "Willingness to transcend hostility, work through trauma, and create space for healing.",
    teacher: ["Which child do I still meet with last week's conflict in the back of my mind?", "How do I show that a matter is settled for me – and does the class notice?"],
    students: ["What has to happen for something to be truly settled for you?", "Are you holding something against someone? What would make it easier?"],
    ideas: ["Close conflicts with repair rather than punishment: what does the person affected need for things to be right again?", "A ritual for starting over: after an argument each side says what they will do differently next time – nobody has to apologise."],
    subjects: ["Ethics & citizenship", "Class time", "Language arts"],
    exercise: { title: "Settled", text: "Everyone writes down one thing that still occupies them and decides for themselves: keep it or let it go. The let-go notes are collected unread and disposed of." } },

  { id: "beziehungen-aufbauen", dim: "collaborating", name: "Relationship-Building Skills", icon: "beziehungen-aufbauen",
    desc: "Nurturing relationships with emotional intelligence grounded in trust, respect, mutual understanding, and a spirit of collaboration.",
    teacher: ["Which child in my class do I barely have a relationship with – and when would I have two minutes for it?", "Where do I check up although I could trust?"],
    students: ["How do you notice that someone likes you, even without them saying so?", "What would have to happen for you to trust someone again?"],
    ideas: ["The two-minute rule: for ten days, spend two minutes a day with the child you have the thinnest relationship with – about anything but school.", "Hand over responsibility: class duties, materials, break organisation without supervision."],
    subjects: ["Class time", "Physical education", "All subjects"],
    exercise: { title: "Blind guiding", text: "In pairs: one person closes their eyes, the other guides them through the room by voice alone. Then swap. What helped?" } },
  { id: "inklusive-denkweise", dim: "collaborating", name: "Inclusive Mindset and Intercultural Competence", icon: "inklusive-denkweise",
    desc: "Willingness and competence to embrace diversity and include people and communities with different perspectives and backgrounds.",
    teacher: ["Who in my class appears in examples, pictures and texts – and who does not?", "Which normality am I unknowingly assuming?"],
    students: ["What is different at your home than at others' – and what do you like about it?", "When have you felt excluded?"],
    ideas: ["Language portrait: everyone draws their languages into a body outline and presents it.", "Take festivals and rituals from the class into the year's calendar."],
    subjects: ["Foreign languages", "Ethics & citizenship", "History & geography", "Music"],
    exercise: { title: "Alike and different", text: "In pairs, find three things in common and three differences in two minutes. Which were surprising?" } },
  { id: "gemeinsam-gestalten", dim: "collaborating", name: "Co-Creation Skills", icon: "gemeinsam-gestalten",
    desc: "Facilitating collaborative processes with diverse stakeholders, fostering teamwork and psychological safety, and being aware of power dynamics.",
    teacher: ["What do my students actually get to decide on – and what only seemingly?", "Does everyone feel safe enough to voice a half-finished idea?"],
    students: ["Who talks most in your group – and who decides in the end?", "What do you need in order to say an unfinished idea out loud?"],
    ideas: ["Plan a class project together from idea to delivery – the teacher as coach.", "Make airtime visible: during group work one person tallies who speaks how much. Look at it together afterwards."],
    subjects: ["Project work", "Design & technology", "Class time"],
    exercise: { title: "Build together", text: "Groups get ten sheets of paper and build the tallest tower – without speaking. Afterwards: who contributed how?" } },
  { id: "kommunizieren", dim: "collaborating", name: "Communication Skills", icon: "kommunizieren",
    desc: "Ability to listen deeply, foster genuine dialogue, advocate one's views skillfully, manage conflicts constructively and adapt communication to diverse groups.",
    teacher: ["How many of my questions in class are real questions I don't know the answer to?", "How do I speak to parents differently than to students – and how much of that is helpful?"],
    students: ["How do you notice that someone is really listening to you?", "How do you tell someone that something bothers you without hurting them?"],
    ideas: ["Work out rules for conversation together and put them up as a poster.", "A class council with fixed roles: chair, minutes, timekeeping, mood."],
    subjects: ["Language arts", "Foreign languages", "Class time"],
    exercise: { title: "Mirroring", text: "In pairs: A talks for a minute. B summarises: “What I understood is …” A corrects or confirms. Then swap." } },
  { id: "mobilisieren", dim: "collaborating", name: "Mobilization Skills", icon: "mobilisieren",
    desc: "Inspiring and enabling others to engage in shared purposes and collective action.",
    teacher: ["What excites me about my subject – and does my class see that excitement?", "How do I win colleagues over for an idea rather than talk them into it?"],
    students: ["What would you want to get others excited about?", "Who has carried you along before – how did they do it?"],
    ideas: ["Students plan an action for the school (a collection, a break kiosk, an exhibition) and campaign for it.", "Short speeches: win people over for a cause in 60 seconds."],
    subjects: ["Language arts", "Project work", "Economics & practical skills"],
    exercise: { title: "One-minute pitch", text: "Everyone picks a small improvement for the class. One minute to campaign for it. The class votes – and the winner gets implemented." } },

  { id: "mut", dim: "acting", name: "Courage", icon: "mut",
    desc: "Standing up for fundamental values, making decisions, taking action, and, when needed, questioning and disrupting established structures and views.",
    teacher: ["What would I change in my teaching if I weren't afraid of criticism?", "When did I last disagree in a staff meeting?"],
    students: ["When did you dare to say something even though it was difficult?", "What is the difference between brave and reckless?"],
    ideas: ["Collect courage stories: children tell of small brave moments – not heroic deeds.", "Practise bystander scenes in role play: what do I say when someone is laughed at?"],
    subjects: ["Ethics & citizenship", "Language arts", "Drama", "Physical education"],
    exercise: { title: "A small courage", text: "Everyone considers: what would be a small brave step for me today? Write it down, fold it up. Tomorrow: who did it?" } },
  { id: "hoffnung-und-optimismus", dim: "acting", name: "Hope and Optimism", icon: "hoffnung-und-optimismus",
    desc: "Building and sustaining a shared belief in our capacity to create a more just, inclusive, and sustainable future.",
    teacher: ["Which future am I conveying to my class – one you can shape, or one you have to endure?", "What gives me hope in my profession?"],
    students: ["What has got better in recent years?", "What could we manage as a class that one person alone could not?"],
    ideas: ["Good news of the week: students research what is developing positively.", "Solution stories instead of problem stories: who has already solved a similar problem – and how?"],
    subjects: ["Media & IT", "Science & society", "Language arts"],
    exercise: { title: "Even so", text: "Everyone names a worry in one sentence. Their neighbour answers with a sentence beginning “Even so …”." } },
  { id: "bewusster-umgang-mit-ressourcen", dim: "acting", name: "Conscious Use of Resources", icon: "bewusster-umgang-mit-ressourcen",
    desc: "Acting with awareness of the planet's limited natural resources, prioritizing conservation, regeneration, and frugality to avoid harmful consumption.",
    teacher: ["What do I use up in my teaching without thinking about it – paper, electricity, materials?", "Do I talk about sustainability, or is it visible in the classroom too?"],
    students: ["What ends up in your bin at the end of the day – and where else could it go?", "Of everything you own, what do you really need?"],
    ideas: ["A waste audit: collect for a week what gets thrown away in the classroom, then sort it and derive rules from it.", "Repair instead of replace: bring broken things from home and mend them together."],
    subjects: ["Science & technology", "Economics & practical skills", "Design & technology", "Science & society"],
    exercise: { title: "One object, three lives", text: "Pick one object from your pencil case. Where did it come from, what happens to it when it breaks? Tell its story in pairs in two minutes." } },
  { id: "proaktiv-handeln", dim: "acting", name: "Proactivity", icon: "proaktiv-handeln",
    desc: "Practicing future-oriented, accountable stewardship in the face of urgent challenges, grounded in solidarity and care for human dignity and the living Earth.",
    teacher: ["Where am I waiting for someone else to solve a problem I have seen for a long time?", "Which responsibility do I trust my class with – and which do I take away from them?"],
    students: ["What bothers you about school enough that you would do something about it?", "What could you do as soon as tomorrow without anyone asking you to?"],
    ideas: ["Take up a real concern from the school building and see it through to implementation – with a letter to the head teacher, not just a poster.", "Assign responsibility for good: each person takes on a task that serves the community for a term."],
    subjects: ["History & geography", "Project work", "Ethics & citizenship", "Economics & practical skills"],
    exercise: { title: "From annoyance to action", text: "Everyone names something that annoys them. Their neighbour answers with a first step that would be possible today." } },
  { id: "resilienz", dim: "acting", name: "Resilience", icon: "resilienz",
    desc: "Navigating adversity with agility, staying engaged, and persevering even when progress is slow or uncertain.",
    teacher: ["Which child am I quietly starting to give up on – and what would it take to stay with them?", "Which plan did I drop too early – and which should I have adjusted sooner?"],
    students: ["What can you do today that you couldn't before? How did you learn it?", "What do you do when something fails for the third time – keep going or try differently?"],
    ideas: ["Make progress visible: put work from September and from June side by side.", "A long-term project across a term with interim stages – plants, a journal, practising a skill."],
    subjects: ["Mathematics", "Music", "Physical education", "Science & technology"],
    exercise: { title: "Not yet", text: "Collect sentences with “I can't do that” and add one word out loud: “I can't do that yet.” What does the small word change?" } }
];

export default { ui, dimensions, skills };
