// English. Framework layer (dimensions, skill names, descriptions) taken
// verbatim from "IDG Framework (English).pdf".
//
// Two corrections to that source: it carries the description of "Creativity"
// under "Courage", and the description of "Inclusive Mindset" under
// "Creativity". The French, Spanish and Swedish editions all agree on the
// correct wording, which is used here.
//
// The reflection questions, classroom ideas, subject links and mini-exercises
// are not part of the IDG framework — they were written for this app and are
// translated from the German original. Swiss curriculum subjects have been
// generalised.
export const ui = {
  appName: "IDG in the classroom",
  tagline: "23 skills. One card at a time.",
  intro: "The Inner Development Goals describe inner abilities we need in order to shape change. These cards translate them into your teaching day.",
  tabs: { stack: "Deck", dimensions: "Dimensions", saved: "Saved", settings: "Settings" },
  language: "Language",
  cardDesign: "Card design",
  variantFarbe: "Colour card",
  variantPapier: "Paper card",
  flipDirection: "Flip",
  flipH: "Horizontal",
  flipV: "Vertical",
  clearSaved: "Clear saved cards",
  cleared: "Saved cards cleared",
  about: "This app makes the Inner Development Goals accessible to teachers: 23 skills, each with reflection questions for you and for your class, plus ideas for the classroom.",
  cardOfDay: "Card of the day",
  random: "Random card",
  flipHint: "Tap to flip",
  swipeHint: "Swipe right to save",
  savedToast: "Saved",
  front: "Skill",
  back: "For the classroom",
  forMe: "For me",
  forStudents: "For my class",
  ideas: "In the classroom",
  sheetSub: "Ideas, subject links and a mini-exercise",
  subjects: "Subject links",
  exercise: "Mini-exercise · 5 minutes",
  save: "Save",
  saved: "Saved",
  share: "Share",
  shared: "Copied",
  next: "Next",
  prev: "Back",
  emptySaved: "No cards saved yet.",
  emptySavedHint: "Tap “Save” when a card should stay with you.",
  skillsCount: "skills",
  ofCards: "of",
  attribution: "This work is inspired by the Inner Development Goals. More at innerdevelopmentgoals.org",
  dimensionLabel: "Dimension",
  allCards: "All cards",
  close: "Close",
  level: "Primary to upper secondary",
  orderRandom: "Random order",
  orderGuide: "Order as in the guide",
  on: "On",
  off: "Off",
  tapNext: "Tap for the next question"
};

export const dimensions = [
  { id: "being", num: 1, name: "Being", subtitle: "Relationship to Self", color: "#D4B88C",
    intro: "Cultivating our inner life and developing and deepening our relationship to our thoughts, feelings and body help us be present, intentional and non-reactive when we face complexity." },
  { id: "thinking", num: 2, name: "Thinking", subtitle: "Cognitive Skills", color: "#E585A1",
    intro: "Developing our cognitive skills by taking different perspectives, evaluating information and making sense of the world as an interconnected whole is essential for wise decision-making." },
  { id: "relating", num: 3, name: "Relating", subtitle: "Caring for Others and the World", color: "#EF4136",
    intro: "Appreciating, caring for and feeling connected to others, such as neighbors, future generations or the biosphere, helps us create more just and sustainable systems and societies for everyone." },
  { id: "collaborating", num: 4, name: "Collaborating", subtitle: "Social Skills", color: "#FF7E2A",
    intro: "To make progress on shared concerns, we need to develop our abilities to include, hold space and communicate with stakeholders with different values, skills and competencies." },
  { id: "acting", num: 5, name: "Acting", subtitle: "Enabling Change", color: "#661A30",
    intro: "Qualities such as courage and optimism help us acquire true agency, break old patterns, generate original ideas and act with persistence in uncertain times." }
];

export const skills = [
  { id: "b1", dim: "being", name: "Inner Compass", icon: "b1-innerer-kompass",
    desc: "Having a deeply felt sense of responsibility and commitment to values and purposes relating to the good of the whole.",
    teacher: ["Which value guided my decisions in the classroom today – and where did I depart from it?", "Why did I become a teacher? How much of that was noticeable this week?"],
    students: ["What matters so much to you that you would stand up for it?", "How do you notice that something feels right or wrong to you?"],
    ideas: ["Map of values: the class collects values on cards and sorts them together – what connects us, where do we differ?", "Don't hand down class rules; derive them from the shared values."],
    subjects: ["Ethics & citizenship", "Class time", "Language arts"],
    exercise: { title: "My sentence for today", text: "Everyone writes down in one sentence what matters to them today. Reading out is voluntary. At the end of the day, check briefly: did it hold?" } },
  { id: "b2", dim: "being", name: "Integrity and Authenticity", icon: "b2-integritaet-und-authentizitaet",
    desc: "A commitment and ability to act with sincerity, honesty and integrity.",
    teacher: ["When did I last admit to the class that I didn't know something or had made a mistake?", "Where do I say things I don't quite mean myself – and why?"],
    students: ["When is it hard for you to be honest?", "What does being yourself mean to you?"],
    ideas: ["Make a culture of mistakes visible: a wall of “mistakes we learned from”.", "Discuss dilemma stories: what would you do if nobody found out?"],
    subjects: ["Ethics & citizenship", "Language arts", "Class time"],
    exercise: { title: "An honest answer", text: "To “How are you?” everyone answers honestly for once instead of “fine”. Two minutes of silence, then share in pairs." } },
  { id: "b3", dim: "being", name: "Openness and Learning Mindset", icon: "b3-offenheit-und-lernbereitschaft",
    desc: "Having a basic mindset of curiosity and a willingness to be vulnerable and embrace change & grow.",
    teacher: ["What did I learn from my students this week?", "Which teaching routine do I keep because I have always done it that way?"],
    students: ["When did you last change your mind? What convinced you?", "What would you like to learn even if nobody asked you to?"],
    ideas: ["Swap roles: students teach the teacher something they are good at.", "Introduce “I don't know yet” cards as a permitted answer in class."],
    subjects: ["All subjects", "Class time", "Project work"],
    exercise: { title: "A curious question", text: "Everyone writes down a question they have no answer to. Questions go on the wall – one is chosen together and followed up during the week." } },
  { id: "b4", dim: "being", name: "Self-awareness", icon: "b4-selbsterkenntnis",
    desc: "Ability to be in reflective contact with own thoughts, feelings and desires; having a realistic self-image & ability to regulate oneself.",
    teacher: ["Which classroom situations throw me off balance – and what lies behind that?", "How do I react under stress, and how much of it does my class pick up?"],
    students: ["How do you notice in your body that you are getting angry or nervous?", "What are you good at – and how do you know?"],
    ideas: ["A feelings check-in at the start of the lesson using weather cards or a scale from 1 to 5.", "A learning journal with a weekly question: what helped me today, what slowed me down?"],
    subjects: ["Class time", "Science & society", "Physical education"],
    exercise: { title: "Inner weather", text: "Close your eyes, take three breaths. What is my weather right now – sunny, cloudy, stormy? Anyone who wants to shares it in one word." } },
  { id: "b5", dim: "being", name: "Presence", icon: "b5-gegenwaertigkeit",
    desc: "Ability to be in the here and now, without judgement & in a state of open-ended presence.",
    teacher: ["How often am I already thinking about the next lesson during this one?", "When did I truly listen to a student today – without already knowing the answer?"],
    students: ["When were you last so absorbed that you forgot the time?", "What can you hear right now if you stay completely still for a minute?"],
    ideas: ["A minute of silence as a fixed ritual after break.", "Mindful observation in nature or art: five minutes of just looking, then describing."],
    subjects: ["Physical education", "Visual arts", "Music", "Science & society"],
    exercise: { title: "Five senses", text: "One after another: what do I see, hear, feel, smell, taste? Thirty seconds each, without judging." } },

  { id: "t1", dim: "thinking", name: "Critical Thinking", icon: "t1-kritisches-denken",
    desc: "Skills in critically reviewing the validity of views, evidence and plans.",
    teacher: ["Which assumptions about my class have I not questioned lately?", "Where do I allow disagreement in class – and where do I unknowingly shut it down?"],
    students: ["How do you know that is true?", "Who has an interest in you believing that?"],
    ideas: ["Fake-news check: compare two reports, examine the sources, develop criteria.", "A debate format with side-swapping – every position is argued once."],
    subjects: ["Media & IT", "Language arts", "History & geography", "Science & technology"],
    exercise: { title: "Three questions for a claim", text: "Put a statement on the board. In groups: where does it come from? What speaks against it? What would we need to know to be sure?" } },
  { id: "t2", dim: "thinking", name: "Complexity Awareness", icon: "t2-bewusstsein-fuer-komplexitaet",
    desc: "Understanding of and skills in working with complex and systemic conditions and causalities.",
    teacher: ["Which problem in my class am I trying to fix with a simple solution although it has many causes?", "Which connections outside school reach into my teaching?"],
    students: ["What all happens when one thing happens?", "Where does a small cause lead to a large effect?"],
    ideas: ["Draw a web of effects: one topic (e.g. classroom noise, plastic) in the middle, causes and consequences as arrows.", "A systems game: everyone is part of a cycle and experiences how a change is passed along."],
    subjects: ["Science & society", "History & geography", "Economics & practical skills"],
    exercise: { title: "And then?", text: "Name a change (e.g. “there is no more homework”). Ask around the circle: and then? Five rounds, until the consequences surprise you." } },
  { id: "t3", dim: "thinking", name: "Perspective Skills", icon: "t3-perspektivische-faehigkeiten",
    desc: "Skills in seeking, understanding and actively making use of insights from contrasting perspectives.",
    teacher: ["What does my lesson look like from the perspective of the quietest child?", "Whose viewpoint is missing from my teaching materials?"],
    students: ["How would this story sound if another character told it?", "What might someone think whose life is completely different from yours?"],
    ideas: ["Retell texts or historical events from the viewpoint of a minor character.", "Opinion line: position yourself in the room on a statement and talk with someone at the other end."],
    subjects: ["Language arts", "History & geography", "Foreign languages", "Ethics & citizenship"],
    exercise: { title: "Change chairs", text: "Discuss a topic in pairs. After two minutes swap places – and carry on from the other person's position." } },
  { id: "t4", dim: "thinking", name: "Sense-making", icon: "t4-sinnstiftung",
    desc: "Skills in seeing patterns, structuring the unknown and being able to consciously create stories.",
    teacher: ["What story am I telling myself about my class – and does it still hold?", "Do my students understand why we learn what we learn?"],
    students: ["What does what we learned today have to do with your life?", "Which pattern do you recognise here?"],
    ideas: ["Start the lesson with a “why are we learning this?” question and let the class answer it at the end.", "Concept maps instead of summaries: make connections visible."],
    subjects: ["All subjects", "Language arts", "Mathematics"],
    exercise: { title: "The common thread", text: "Three terms from last week on the board. In pairs: which story connects them? The shortest version wins." } },
  { id: "t5", dim: "thinking", name: "Long-term Orientation and Visioning", icon: "t5-langfristige-orientierung",
    desc: "Long-term orientation and ability to formulate & sustain commitment to visions relating to the larger context.",
    teacher: ["What should my students still carry from my teaching in twenty years?", "Where am I optimising for the next test instead of for lasting understanding?"],
    students: ["What should your neighbourhood look like in 30 years?", "What would you like people to say later about your generation?"],
    ideas: ["Write a letter to your future self in ten years and keep it at school.", "A futures workshop: critique – vision – implementation, on a topic that concerns the class."],
    subjects: ["History & geography", "Language arts", "Project work", "Careers guidance"],
    exercise: { title: "Time travel", text: "Close your eyes: it is the year 2050. What has got better? Who contributed? One sentence each." } },

  { id: "r1", dim: "relating", name: "Appreciation", icon: "r1-wertschaetzung",
    desc: "Relating to others and to the world with a basic sense of appreciation, gratitude and joy.",
    teacher: ["Who in my class have I not said anything appreciative to this week?", "What am I grateful for in my profession – even on hard days?"],
    students: ["Who helped you today without it being noticed?", "What do you take for granted that is actually special?"],
    ideas: ["Warm shower: one person sits in the middle, everyone names something they value about them.", "A gratitude wall in the classroom, added to weekly."],
    subjects: ["Class time", "Ethics & citizenship", "Language arts"],
    exercise: { title: "Three good things", text: "Everyone writes down three things that were good today – however small. Share one of them with your neighbour." } },
  { id: "r2", dim: "relating", name: "Connectedness", icon: "r2-verbundenheit",
    desc: "Having a keen sense of being connected with and/or being a part of a larger whole, such as a community, humanity or global ecosystem.",
    teacher: ["Does every child in my class feel part of the group? How do I know?", "Where do I feel connected myself – to the staff, the school, the place?"],
    students: ["Who or what do you belong to?", "What connects you with a child on another continent?"],
    ideas: ["Trace an everyday object back to its origin: who all contributed to it?", "A class partnership with a school in another country or region."],
    subjects: ["Science & society", "History & geography", "Foreign languages"],
    exercise: { title: "Web of yarn", text: "In a circle: a ball of yarn is thrown. Whoever catches it names something they have in common with the person who threw it. In the end everyone holds a web." } },
  { id: "r3", dim: "relating", name: "Humility", icon: "r3-bescheidenheit",
    desc: "Being able to act in accordance with the needs of the situation without concern for one's own importance.",
    teacher: ["How much do I talk in a lesson, how much does the class?", "When did I last prefer a student's idea to my own?"],
    students: ["When does it matter more that the group moves on than that you are right?", "What can others do better than you – and how does that feel?"],
    ideas: ["Silent discussion on paper: every voice gets the same amount of space.", "Rotate roles in group work, including the inconspicuous ones."],
    subjects: ["Class time", "Physical education", "All subjects"],
    exercise: { title: "Listening without answering", text: "In pairs: one person talks for two minutes, the other only listens – no comment, no advice. Then swap. How was it?" } },
  { id: "r4", dim: "relating", name: "Empathy and Compassion", icon: "r4-einfuehlungsvermoegen-und-mitgefuehl",
    desc: "Ability to relate to others, oneself and nature with kindness, empathy and compassion and address related suffering.",
    teacher: ["Which behaviour in my class annoys me – and which need might sit behind it?", "How do I treat myself when a lesson goes wrong?"],
    students: ["How do you notice that someone is not doing well?", "What helps you when you are sad – and could it help others too?"],
    ideas: ["Widen the vocabulary of feelings: describe pictures or scenes, collect precise words.", "Change of perspective in conflicts: both sides write down what the other probably felt."],
    subjects: ["Language arts", "Ethics & citizenship", "Class time", "Visual arts"],
    exercise: { title: "A kind thought", text: "Everyone thinks of someone who is having a hard time. Silently form a good wish for them. Then direct the same wish at yourself." } },

  { id: "c1", dim: "collaborating", name: "Communication Skills", icon: "c1-kommunikationsfaehigkeiten",
    desc: "Ability to really listen to others, to foster genuine dialogue, to advocate own views skillfully, to manage conflicts constructively & to adapt communication to diverse groups.",
    teacher: ["How many of my questions in class are real questions I don't know the answer to?", "How do I speak to parents differently than to students – and how much of that is helpful?"],
    students: ["How do you notice that someone is really listening to you?", "How do you tell someone that something bothers you without hurting them?"],
    ideas: ["Work out rules for conversation together and put them up as a poster.", "A class council with fixed roles: chair, minutes, timekeeping, mood."],
    subjects: ["Language arts", "Foreign languages", "Class time"],
    exercise: { title: "Mirroring", text: "In pairs: A talks for a minute. B summarises: “What I understood is …” A corrects or confirms. Then swap." } },
  { id: "c2", dim: "collaborating", name: "Co-creation Skills", icon: "c2-mitgestaltungsfaehigkeiten",
    desc: "Skills and motivation to build, develop and facilitate collaborative relationships with diverse stakeholders, characterized by psychological safety and genuine co-creation.",
    teacher: ["What do my students actually get to decide on – and what only seemingly?", "Does everyone feel safe enough to voice a half-finished idea?"],
    students: ["When did group work feel really good? What was different?", "What do you need in order to say an unfinished idea out loud?"],
    ideas: ["Plan a class project together from idea to delivery – the teacher as coach.", "A “yes, and …” rule when gathering ideas: build first, judge later."],
    subjects: ["Project work", "Design & technology", "Class time"],
    exercise: { title: "Build together", text: "Groups get ten sheets of paper and build the tallest tower – without speaking. Afterwards: who contributed how?" } },
  { id: "c3", dim: "collaborating", name: "Inclusive Mindset and Intercultural Competence", icon: "c3-inklusive-denkweise",
    desc: "Willingness and competence to embrace diversity and include people and collectives with different views and backgrounds.",
    teacher: ["Who in my class appears in examples, pictures and texts – and who does not?", "Which normality am I unknowingly assuming?"],
    students: ["What is different at your home than at others' – and what do you like about it?", "When have you felt excluded?"],
    ideas: ["Language portrait: everyone draws their languages into a body outline and presents it.", "Take festivals and rituals from the class into the year's calendar."],
    subjects: ["Foreign languages", "Ethics & citizenship", "History & geography", "Music"],
    exercise: { title: "Alike and different", text: "In pairs, find three things in common and three differences in two minutes. Which were surprising?" } },
  { id: "c4", dim: "collaborating", name: "Trust", icon: "c4-vertrauen",
    desc: "Ability to show trust and to create and maintain trusting relationships.",
    teacher: ["Where do I check up although I could trust?", "What do I do so that my students trust me – even after a conflict?"],
    students: ["Who do you trust – and why exactly?", "What would have to happen for you to trust someone again?"],
    ideas: ["Hand over responsibility: class duties, materials, break organisation without supervision.", "A trust course in PE with blindfolds."],
    subjects: ["Physical education", "Class time", "All subjects"],
    exercise: { title: "Blind guiding", text: "In pairs: one person closes their eyes, the other guides them through the room by voice alone. Then swap. What helped?" } },
  { id: "c5", dim: "collaborating", name: "Mobilization Skills", icon: "c5-mobilisierungsfaehigkeiten",
    desc: "Skills in inspiring and mobilizing others to engage in shared purposes.",
    teacher: ["What excites me about my subject – and does my class see that excitement?", "How do I win colleagues over for an idea rather than talk them into it?"],
    students: ["What would you want to get others excited about?", "Who has carried you along before – how did they do it?"],
    ideas: ["Students plan an action for the school (a collection, a break kiosk, an exhibition) and campaign for it.", "Short speeches: win people over for a cause in 60 seconds."],
    subjects: ["Language arts", "Project work", "Economics & practical skills"],
    exercise: { title: "One-minute pitch", text: "Everyone picks a small improvement for the class. One minute to campaign for it. The class votes – and the winner gets implemented." } },

  { id: "a1", dim: "acting", name: "Courage", icon: "a1-mut",
    desc: "Ability to stand up for values, make decisions, take resolute action and, if need be, challenge and disrupt existing structures and views.",
    teacher: ["What would I change in my teaching if I weren't afraid of criticism?", "When did I last disagree in a staff meeting?"],
    students: ["When did you dare to say something even though it was difficult?", "What is the difference between brave and reckless?"],
    ideas: ["Collect courage stories: children tell of small brave moments – not heroic deeds.", "Practise bystander scenes in role play: what do I say when someone is laughed at?"],
    subjects: ["Ethics & citizenship", "Language arts", "Drama", "Physical education"],
    exercise: { title: "A small courage", text: "Everyone considers: what would be a small brave step for me today? Write it down, fold it up. Tomorrow: who did it?" } },
  { id: "a2", dim: "acting", name: "Creativity", icon: "a2-kreativitaet",
    desc: "Ability to generate and develop original ideas, innovate and being willing to disrupt conventional patterns.",
    teacher: ["When were my students last allowed to make something that doesn't exist yet?", "Which task did I set this week so that only one answer is right – and did it have to be that way?"],
    students: ["How could this be solved completely differently?", "What would you invent if anything were possible?"],
    ideas: ["Open tasks with several routes to a solution – especially in mathematics.", "Reversal exercise: an everyday object gets a new purpose."],
    subjects: ["Visual arts", "Mathematics", "Design & technology", "Music"],
    exercise: { title: "30 circles", text: "A sheet with 30 empty circles. In three minutes turn as many as possible into something – a ball, a clock, a pizza. Quantity before quality." } },
  { id: "a3", dim: "acting", name: "Optimism", icon: "a3-optimismus",
    desc: "Ability to sustain and communicate a sense of hope, positive attitude and confidence in the possibility of meaningful change.",
    teacher: ["Which future am I conveying to my class – one you can shape, or one you have to endure?", "What gives me hope in my profession?"],
    students: ["What has got better in recent years?", "What could you contribute so that something turns out well?"],
    ideas: ["Good news of the week: students research what is developing positively.", "Solution stories instead of problem stories: who has solved a similar problem?"],
    subjects: ["Media & IT", "Science & society", "Language arts"],
    exercise: { title: "Even so", text: "Everyone names a worry in one sentence. Their neighbour answers with a sentence beginning “Even so …”." } },
  { id: "a4", dim: "acting", name: "Perseverance", icon: "a4-beharrlichkeit",
    desc: "Ability to sustain engagement and remain determined and patient even when efforts take a long time to bear fruit.",
    teacher: ["Which child am I quietly starting to give up on – and what would it take to stay with them?", "Which plan did I drop too early?"],
    students: ["What can you do today that you couldn't before? How did you learn it?", "What do you do when something doesn't work the first time?"],
    ideas: ["Make progress visible: put work from September and from June side by side.", "A long-term project across a term with interim stages – plants, a journal, practising a skill."],
    subjects: ["Mathematics", "Music", "Physical education", "Science & technology"],
    exercise: { title: "Not yet", text: "Collect sentences with “I can't do that” and add one word out loud: “I can't do that yet.” What does the small word change?" } }
];

export default { ui, dimensions, skills };
