// Español. Contenido: Inner Development Guide 2.0 (versión 7.2), 25 habilidades en
// cinco dimensiones. La capa del marco (nombres y subtítulos de las dimensiones,
// introducciones, nombres y descripciones de las habilidades) está traducida de la
// edición alemana de la guía, que es la fuente con la que se actualizó esta
// aplicación; se ha conservado la formulación española de la versión 1.0 allí donde
// sigue correspondiendo a la definición 2.0.
//
// Las preguntas de reflexión, las ideas para el aula, los vínculos con las materias
// y los miniejercicios no forman parte del marco IDG: se escribieron para esta
// aplicación y están traducidos del alemán. Las materias del plan de estudios suizo
// se han generalizado.
export const ui = {
  appName: "Inner Development Guide",
  appNameSub: "en el aula",
  tagline: "25 habilidades. Una carta cada vez.",
  intro: "El Inner Development Guide 2.0 describe habilidades interiores que necesitamos para dar forma al cambio. Estas cartas las traducen a tu día a día docente.",
  tabs: { stack: "Mazo", dimensions: "Dimensiones", saved: "Guardadas", settings: "Ajustes" },
  language: "Idioma",
  cardDesign: "Diseño de las cartas",
  variantFarbe: "Carta en color",
  variantPapier: "Carta en papel",
  flipDirection: "Girar",
  flipH: "Horizontal",
  flipV: "Vertical",
  clearSaved: "Vaciar las guardadas",
  cleared: "Guardadas vaciadas",
  about: "Esta aplicación acerca el Inner Development Guide al profesorado: 25 habilidades, cada una con preguntas de reflexión para ti y para tu clase, además de ideas para el aula.",
  cardOfDay: "Carta del día",
  random: "Carta al azar",
  flipHint: "Toca para girar",
  swipeHint: "Desliza a la derecha para guardar",
  savedToast: "Guardada",
  front: "Habilidad",
  back: "Para el aula",
  forMe: "Para mí",
  forStudents: "Para mi clase",
  ideas: "En el aula",
  sheetSub: "Ideas, vínculos con las materias y miniejercicio",
  subjects: "Vínculos con las materias",
  exercise: "Miniejercicio · 5 minutos",
  save: "Guardar",
  saved: "Guardada",
  share: "Compartir",
  shared: "Copiado",
  next: "Siguiente",
  prev: "Atrás",
  emptySaved: "Todavía no has guardado ninguna carta.",
  emptySavedHint: "Toca «Guardar» cuando quieras que una carta te acompañe.",
  skillsCount: "habilidades",
  ofCards: "de",
  attribution: "Este trabajo se inspira en el Inner Development Guide. Más información en innerdevelopmentgoals.org",
  dimensionLabel: "Dimensión",
  allCards: "Todas las cartas",
  close: "Cerrar",
  level: "De primaria a bachillerato",
  orderRandom: "Orden aleatorio",
  orderGuide: "Orden de la guía",
  on: "Activado",
  off: "Desactivado",
  tapNext: "Toca para la siguiente pregunta"
};

export const dimensions = [
  { id: "being", num: 1, name: "Ser", subtitle: "Cultivar nuestra vida interior", color: "#D4B88C",
    intro: "Un mundo complejo exige, más que nunca, una conciencia profunda de nuestra experiencia interior y de nuestra relación dinámica con el mundo que nos rodea. Eso exige y fortalece nuestra atención y presencia, nuestra claridad interior y nuestra capacidad de actuar de forma reflexiva." },
  { id: "thinking", num: 2, name: "Pensar", subtitle: "Comprender nuestro mundo complejo", color: "#E585A1",
    intro: "Tener en cuenta perspectivas distintas y las consecuencias a largo plazo de nuestros actos nos ayuda a comprender la complejidad de nuestro mundo, a manejarla y a tomar decisiones más sensatas en un mundo interconectado." },
  { id: "relating", num: 3, name: "Relacionarse", subtitle: "Cuidar de los demás y del mundo", color: "#EF4136",
    intro: "Mediante la amabilidad, la compasión y el sentimiento de pertenecer a comunidades, al planeta vivo y a las generaciones futuras, creamos un mundo más justo, más inclusivo y más floreciente." },
  { id: "collaborating", num: 4, name: "Colaborar", subtitle: "Construir confianza y trabajar juntos", color: "#FF7E2A",
    intro: "Construir relaciones de confianza, reconocer valores, capacidades y perspectivas diversas y crear espacios seguros permiten que todas las personas contribuyan a objetivos comunes y a un impacto colectivo." },
  { id: "acting", num: 5, name: "Actuar", subtitle: "Iniciar y posibilitar el cambio", color: "#661A30",
    intro: "Cuando avanzamos con valentía y optimismo y desarrollamos nuestras capacidades comunes, podemos actuar con determinación y constancia. En tiempos inciertos, eso convierte nuestras visiones compartidas en cambios concretos y con sentido." }
];

export const skills = [
  { id: "innerer-kompass", dim: "being", name: "Brújula interior", icon: "innerer-kompass",
    desc: "Un compromiso profundamente sentido de vivir y actuar en consonancia con valores y propósitos que sirven al bien común.",
    teacher: ["¿Qué valor guió hoy mis decisiones en el aula, y en qué momento me aparté de él?", "¿Por qué me hice docente? ¿Cuánto de eso se notó esta semana?"],
    students: ["¿Qué te importa tanto como para defenderlo?", "¿En qué notas que algo te parece correcto o incorrecto?"],
    ideas: ["Mapa de valores: la clase reúne valores en tarjetas y los ordena en conjunto. ¿Qué nos une, en qué nos diferenciamos?", "No imponer las normas de clase, sino deducirlas de los valores compartidos."],
    subjects: ["Ética y ciudadanía", "Tutoría", "Lengua"],
    exercise: { title: "Mi frase de hoy", text: "Cada persona escribe en una frase lo que hoy le importa. Leerla en voz alta es voluntario. Al final del día, comprobar brevemente: ¿se cumplió?" } },
  { id: "integritaet-und-authentizitaet", dim: "being", name: "Integridad y autenticidad", icon: "integritaet-und-authentizitaet",
    desc: "Un compromiso sincero con la honestidad y con valores firmemente arraigados, que se expresan y se encarnan en todos los actos.",
    teacher: ["¿Cuándo fue la última vez que admití ante la clase que no sabía algo o que me había equivocado?", "¿Dónde digo cosas que en realidad no pienso del todo, y por qué?"],
    students: ["¿Cuándo te cuesta ser honesto?", "¿Qué significa para ti ser tú mismo?"],
    ideas: ["Hacer visible una cultura del error: un mural con «errores de los que hemos aprendido».", "Comentar historias-dilema: ¿qué harías si nadie se enterara?"],
    subjects: ["Ética y ciudadanía", "Lengua", "Tutoría"],
    exercise: { title: "Una respuesta sincera", text: "A la pregunta «¿cómo estás?» todo el mundo responde por una vez con sinceridad en lugar de «bien». Dos minutos en silencio y después intercambio por parejas." } },
  { id: "offenheit-und-lernbereitschaft", dim: "being", name: "Apertura y mentalidad de aprendizaje", icon: "offenheit-und-lernbereitschaft",
    desc: "Una actitud curiosa y adaptable, y la disposición a cambiar de perspectiva, a mostrarse vulnerable, a acoger el cambio y a crecer.",
    teacher: ["¿Qué he aprendido esta semana de mi alumnado?", "¿Qué rutina de clase mantengo solo porque siempre lo he hecho así?"],
    students: ["¿Cuándo cambiaste de opinión por última vez? ¿Qué te convenció?", "¿Qué te gustaría aprender aunque nadie te lo pidiera?"],
    ideas: ["Intercambio de papeles: el alumnado enseña al docente algo que sabe hacer bien.", "Introducir tarjetas de «todavía no lo sé» como respuesta permitida en clase."],
    subjects: ["Todas las materias", "Tutoría", "Trabajo por proyectos"],
    exercise: { title: "Una pregunta curiosa", text: "Cada persona anota una pregunta para la que no tiene respuesta. Las preguntas van a la pared: se elige una en común y se sigue durante la semana." } },
  { id: "selbsterkenntnis", dim: "being", name: "Autoconciencia", icon: "selbsterkenntnis",
    desc: "La capacidad de relacionarse de forma reflexiva con los propios pensamientos, emociones, deseos y actos, mantener una imagen realista de sí mismo y autorregularse.",
    teacher: ["¿Qué situaciones de clase me sacan del equilibrio, y qué hay detrás?", "¿Cómo reacciono bajo estrés y cuánto percibe mi clase de ello?"],
    students: ["¿En qué notas en tu cuerpo que te estás enfadando o poniendo nervioso?", "¿Qué se te da bien, y cómo lo sabes?"],
    ideas: ["Un registro de emociones al empezar la clase, con tarjetas del tiempo o una escala del 1 al 5.", "Un diario de aprendizaje con una pregunta semanal: ¿qué me ayudó hoy, qué me frenó?"],
    subjects: ["Tutoría", "Ciencias y sociedad", "Educación física"],
    exercise: { title: "Mi tiempo interior", text: "Cerrar los ojos, tres respiraciones. ¿Qué tiempo hace dentro de mí ahora: soleado, nublado, tormentoso? Quien quiera lo comparte en una palabra." } },
  { id: "praesenz", dim: "being", name: "Presencia", icon: "praesenz",
    desc: "La capacidad de estar plenamente presente en el aquí y ahora, aceptar la realidad tal como es y responder a ella de forma significativa.",
    teacher: ["¿Con cuánta frecuencia estoy, durante la clase, ya pensando en la siguiente?", "¿Cuándo he escuchado hoy de verdad a un alumno o alumna, sin saber ya la respuesta?"],
    students: ["¿Cuándo estuviste tan absorto que se te pasó el tiempo?", "¿Qué oyes ahora mismo si te quedas un minuto en completo silencio?"],
    ideas: ["Un minuto de silencio como ritual fijo después del recreo.", "Observación atenta en la naturaleza o ante una obra: cinco minutos solo mirando y después describir."],
    subjects: ["Educación física", "Educación plástica", "Música", "Ciencias y sociedad"],
    exercise: { title: "Cinco sentidos", text: "Uno tras otro: ¿qué veo, qué oigo, qué siento, qué huelo, qué saboreo? Treinta segundos cada uno, sin valorar." } },

  { id: "kritisches-denken", dim: "thinking", name: "Pensamiento crítico", icon: "kritisches-denken",
    desc: "La capacidad de reflexionar sobre la validez de ideas, pruebas, supuestos y planes.",
    teacher: ["¿Qué suposiciones sobre mi clase no he revisado últimamente?", "¿Dónde permito la discrepancia en clase y dónde la corto sin darme cuenta?"],
    students: ["¿Cómo sabes que eso es cierto?", "¿A quién le interesa que te lo creas?"],
    ideas: ["Comprobación de bulos: comparar dos noticias, examinar las fuentes, elaborar criterios.", "Un formato de debate con cambio de bando: cada postura se defiende una vez."],
    subjects: ["Medios e informática", "Lengua", "Historia y geografía", "Ciencias y tecnología"],
    exercise: { title: "Tres preguntas a una afirmación", text: "Una afirmación en la pizarra. En grupos: ¿de dónde viene? ¿Qué la contradice? ¿Qué necesitaríamos saber para estar seguros?" } },
  { id: "perspektivische-faehigkeiten", dim: "thinking", name: "Habilidades de perspectiva", icon: "perspektivische-faehigkeiten",
    desc: "La capacidad de tener en cuenta perspectivas distintas y de hacer que esos hallazgos fluyan hacia una comprensión y una acción reflexivas.",
    teacher: ["¿Cómo se ve mi clase desde la perspectiva del niño más callado?", "¿Qué historia me cuento sobre mi clase, y sigue siendo cierta?"],
    students: ["¿Cómo sonaría esta historia si la contara otro personaje?", "¿Qué podría pensar alguien que vive de forma muy distinta a ti?"],
    ideas: ["Volver a contar textos o hechos históricos desde la mirada de un personaje secundario.", "Línea de posturas: situarse en el aula ante una afirmación e intercambiar con alguien del extremo opuesto."],
    subjects: ["Lengua", "Historia y geografía", "Lenguas extranjeras", "Ética y ciudadanía"],
    exercise: { title: "Cambio de silla", text: "Hablar de un tema por parejas. A los dos minutos, cambiar de sitio y continuar defendiendo la postura de la otra persona." } },
  { id: "systemisches-denken", dim: "thinking", name: "Pensamiento sistémico", icon: "systemisches-denken",
    desc: "La capacidad de comprender las relaciones complejas y las propiedades de los sistemas y de utilizarlas activamente.",
    teacher: ["¿Qué problema de mi clase intento resolver con una solución simple aunque tenga muchas causas?", "¿Qué relaciones de fuera de la escuela influyen en mis clases?"],
    students: ["¿Qué cosas pasan cuando pasa una sola cosa?", "¿Qué patrón reconoces aquí, y dónde lo has visto antes?"],
    ideas: ["Una red de efectos en lugar de un resumen: un tema (ruido en clase, plástico) en el centro y las causas y consecuencias como flechas. Dibujar las relaciones, no enumerarlas.", "Un juego de sistemas: todos forman parte de un ciclo y viven cómo se transmite un cambio. Después, buscar dónde está la palanca."],
    subjects: ["Ciencias y sociedad", "Historia y geografía", "Economía y vida práctica", "Ciencias y tecnología"],
    exercise: { title: "¿Y entonces?", text: "Nombrar un cambio (por ejemplo, «ya no hay deberes»). Preguntar en círculo: ¿y entonces? Cinco rondas, hasta que las consecuencias sorprendan." } },
  { id: "langfristige-orientierung", dim: "thinking", name: "Orientación y visión a largo plazo", icon: "langfristige-orientierung",
    desc: "Desarrollar objetivos a largo plazo y perseguirlos de un modo que favorezca el bienestar social y ecológico.",
    teacher: ["¿Qué debería seguir llevándose mi alumnado de mis clases dentro de veinte años?", "¿Dónde optimizo para el próximo examen en lugar de para la comprensión duradera?"],
    students: ["¿Cómo debería ser tu barrio dentro de 30 años?", "¿Qué te gustaría que se dijera más adelante sobre tu generación?"],
    ideas: ["Empezar la clase con «¿por qué aprendemos esto?» y dejar que la clase lo responda al final: ¿qué de ello dura más allá del curso?", "Un taller de futuro: crítica, visión y realización, sobre un tema que afecte a la clase."],
    subjects: ["Historia y geografía", "Lengua", "Trabajo por proyectos", "Orientación profesional"],
    exercise: { title: "Viaje en el tiempo", text: "Cerrar los ojos: estamos en 2050. ¿Qué ha mejorado? ¿Quién ha contribuido? Una frase por persona." } },
  { id: "kreativitaet", dim: "thinking", name: "Creatividad", icon: "kreativitaet",
    desc: "La capacidad de pensar más allá de los patrones convencionales, desarrollar nuevas posibilidades y convertirlas en ideas transformadoras.",
    teacher: ["¿Cuándo pudo mi alumnado hacer por última vez algo que todavía no existe?", "¿Qué tarea he planteado esta semana de modo que solo hubiera una respuesta correcta, y tenía que ser así?"],
    students: ["¿Cómo se podría resolver esto de una forma totalmente distinta?", "¿Qué inventarías si todo fuera posible?"],
    ideas: ["Tareas abiertas con varios caminos de solución, sobre todo en matemáticas.", "Ejercicio de inversión: un objeto cotidiano recibe un uso nuevo."],
    subjects: ["Educación plástica", "Matemáticas", "Tecnología y diseño", "Música"],
    exercise: { title: "30 círculos", text: "Una hoja con 30 círculos vacíos. En tres minutos convertir en algo los más posibles: pelota, reloj, pizza. Cantidad antes que calidad." } },

  { id: "wertschaetzung", dim: "relating", name: "Aprecio", icon: "wertschaetzung",
    desc: "Acercarse a las personas y al planeta Tierra con aprecio, alegría y gratitud.",
    teacher: ["¿A quién de mi clase no le he dicho todavía nada de reconocimiento esta semana?", "¿Por qué estoy agradecido en mi profesión, incluso en los días difíciles?"],
    students: ["¿Quién te ha ayudado hoy sin que se notara?", "¿Qué das por hecho aunque en realidad sea especial?"],
    ideas: ["Ducha cálida: una persona se sienta en el centro y todas nombran algo que valoran de ella.", "Un mural de la gratitud en el aula, ampliado cada semana."],
    subjects: ["Tutoría", "Ética y ciudadanía", "Lengua"],
    exercise: { title: "Tres cosas buenas", text: "Cada persona escribe tres cosas que hoy han estado bien, por pequeñas que sean. Compartir una con quien tenga al lado." } },
  { id: "verbundenheit", dim: "relating", name: "Conectividad", icon: "verbundenheit",
    desc: "El sentimiento de pertenecer a un conjunto más amplio: la humanidad, la red de la vida en el planeta y las dimensiones espirituales de la existencia.",
    teacher: ["¿Se siente cada criatura de mi clase parte del grupo? ¿En qué lo noto?", "¿Dónde siento yo mismo esa conexión: con el claustro, la escuela, el lugar?"],
    students: ["¿A quién o a qué perteneces?", "¿Qué te une a una criatura de otro continente?"],
    ideas: ["Rastrear el origen de un objeto cotidiano: ¿quiénes han intervenido en él?", "Un hermanamiento de clase con una escuela de otro país o de otra región."],
    subjects: ["Ciencias y sociedad", "Historia y geografía", "Lenguas extranjeras"],
    exercise: { title: "La red de lana", text: "En círculo se lanza un ovillo de lana. Quien lo recoge dice algo que tiene en común con quien se lo ha lanzado. Al final todo el grupo sostiene una red." } },
  { id: "demut-und-bescheidenheit", dim: "relating", name: "Humildad y modestia", icon: "demut-und-bescheidenheit",
    desc: "Ser capaz de responder a lo que exige una situación sin anteponer la propia importancia.",
    teacher: ["¿Cuánto hablo yo en una clase y cuánto habla el grupo?", "¿Cuándo preferí por última vez la idea de un alumno o alumna a la mía?"],
    students: ["¿Cuándo importa más que el grupo avance que tener tú razón?", "¿Qué hacen otras personas mejor que tú, y cómo se siente eso?"],
    ideas: ["Discusión silenciosa sobre papel: cada voz recibe el mismo espacio.", "Rotar los papeles en los trabajos de grupo, también los menos vistosos."],
    subjects: ["Tutoría", "Educación física", "Todas las materias"],
    exercise: { title: "Escuchar sin responder", text: "Por parejas: una persona habla dos minutos y la otra solo escucha, sin comentar ni aconsejar. Después se cambia. ¿Cómo ha sido?" } },
  { id: "empathie-und-mitgefuehl", dim: "relating", name: "Empatía y compasión", icon: "empathie-und-mitgefuehl",
    desc: "Vincularse con los demás, con uno mismo y con la naturaleza desde la amabilidad, el cuidado y el amor, con el objetivo y la intención de reducir el sufrimiento.",
    teacher: ["¿Qué conducta de mi clase me molesta, y qué necesidad podría haber detrás?", "¿Cómo me trato a mí mismo cuando una clase sale mal?"],
    students: ["¿En qué notas que alguien no está bien?", "¿Qué te sienta bien cuando estás triste, y podría ayudar también a otras personas?"],
    ideas: ["Ampliar el vocabulario emocional: describir imágenes o escenas y reunir palabras precisas.", "Cambio de perspectiva en los conflictos: cada parte escribe qué habrá sentido la otra."],
    subjects: ["Lengua", "Ética y ciudadanía", "Tutoría", "Educación plástica"],
    exercise: { title: "Un pensamiento amable", text: "Cada persona piensa en alguien que lo esté pasando mal y formula en silencio un buen deseo. Después dirige ese mismo deseo hacia sí misma." } },
  { id: "vergebung", dim: "relating", name: "Perdón", icon: "vergebung",
    desc: "La disposición a superar las hostilidades, a elaborar los traumas y a crear espacio para la sanación.",
    teacher: ["¿A qué criatura sigo tratando con el conflicto de la semana pasada en la cabeza?", "¿Cómo muestro que para mí un asunto está cerrado, y lo nota también la clase?"],
    students: ["¿Qué tiene que pasar para que un asunto quede realmente cerrado para ti?", "¿Le guardas rencor a alguien? ¿Qué lo haría más llevadero?"],
    ideas: ["Cerrar los conflictos con reparación en lugar de castigo: ¿qué necesita la persona afectada para que las cosas vuelvan a estar bien?", "Un ritual de nuevo comienzo: después de una pelea, cada parte dice qué hará distinto la próxima vez. Nadie tiene que disculparse."],
    subjects: ["Ética y ciudadanía", "Tutoría", "Lengua"],
    exercise: { title: "Asunto cerrado", text: "Cada persona escribe algo que todavía le preocupa y decide por sí misma: conservarlo o soltarlo. Los papeles de «soltar» se recogen sin leer y se tiran." } },

  { id: "beziehungen-aufbauen", dim: "collaborating", name: "Construir relaciones", icon: "beziehungen-aufbauen",
    desc: "El cuidado de relaciones con inteligencia emocional, basadas en la confianza, el respeto, la comprensión mutua y un espíritu de cooperación.",
    teacher: ["¿Con qué criatura de mi clase apenas tengo relación, y cuándo tendría dos minutos para ello?", "¿Dónde controlo aunque podría confiar?"],
    students: ["¿En qué notas que alguien te aprecia, aunque no lo diga?", "¿Qué tendría que pasar para que volvieras a confiar en alguien?"],
    ideas: ["La regla de los dos minutos: durante diez días, dos minutos diarios con la criatura con la que la relación es más fina, hablando de todo menos de la escuela.", "Ceder responsabilidad: cargos de clase, gestión del material, organización del recreo, sin supervisión."],
    subjects: ["Tutoría", "Educación física", "Todas las materias"],
    exercise: { title: "Guiar a ciegas", text: "Por parejas: una persona cierra los ojos y la otra la guía por el aula solo con la voz. Después se cambia. ¿Qué ha ayudado?" } },
  { id: "inklusive-denkweise", dim: "collaborating", name: "Mentalidad inclusiva y competencia intercultural", icon: "inklusive-denkweise",
    desc: "La disposición y la competencia para reconocer y vivir la diversidad y para incluir a personas y comunidades con perspectivas y trayectorias distintas.",
    teacher: ["¿Quién de mi clase aparece en los ejemplos, las imágenes y los textos, y quién no?", "¿Qué normalidad doy por supuesta sin darme cuenta?"],
    students: ["¿Qué es distinto en tu casa respecto a otras, y qué te gusta de ello?", "¿Cuándo te has sentido excluido alguna vez?"],
    ideas: ["Retrato lingüístico: cada persona dibuja sus lenguas en una silueta y la presenta.", "Incorporar al calendario del curso las fiestas y rituales presentes en la clase."],
    subjects: ["Lenguas extranjeras", "Ética y ciudadanía", "Historia y geografía", "Música"],
    exercise: { title: "Iguales y distintos", text: "Por parejas, encontrar en dos minutos tres cosas en común y tres diferencias. ¿Cuáles han sorprendido?" } },
  { id: "gemeinsam-gestalten", dim: "collaborating", name: "Co-crear", icon: "gemeinsam-gestalten",
    desc: "Impulsar procesos de cooperación con grupos de interés diversos, fomentar el trabajo en equipo y la seguridad psicológica y ser consciente de las relaciones de poder.",
    teacher: ["¿Sobre qué puede decidir realmente mi alumnado, y sobre qué solo en apariencia?", "¿Se siente todo el mundo lo bastante seguro para decir una idea a medio hacer?"],
    students: ["¿Quién habla más en vuestro grupo, y quién decide al final?", "¿Qué necesitas para atreverte a decir una idea sin terminar?"],
    ideas: ["Planificar juntos un proyecto de clase desde la idea hasta la ejecución, con el docente como acompañante.", "Hacer visible el tiempo de palabra: durante un trabajo en grupo, una persona anota quién habla cuánto. Después se mira en común."],
    subjects: ["Trabajo por proyectos", "Tecnología y diseño", "Tutoría"],
    exercise: { title: "Construir juntos", text: "Cada grupo recibe diez hojas de papel y construye la torre más alta, sin hablar. Después: ¿quién ha aportado y cómo?" } },
  { id: "kommunizieren", dim: "collaborating", name: "Comunicar", icon: "kommunizieren",
    desc: "La capacidad de escuchar con atención, promover un diálogo genuino, defender con habilidad los propios puntos de vista, manejar los conflictos de forma constructiva y adaptar la comunicación a grupos diversos.",
    teacher: ["¿Cuántas de mis preguntas en clase son preguntas de verdad, cuya respuesta desconozco?", "¿Cómo hablo distinto a las familias que al alumnado, y qué parte de ello resulta útil?"],
    students: ["¿En qué notas que alguien te escucha de verdad?", "¿Cómo le dices a alguien que algo te molesta sin herirle?"],
    ideas: ["Elaborar juntos las normas de conversación y colgarlas como cartel.", "Una asamblea de clase con papeles fijos: moderación, acta, tiempo, ambiente."],
    subjects: ["Lengua", "Lenguas extranjeras", "Tutoría"],
    exercise: { title: "Reflejar", text: "Por parejas: A cuenta durante un minuto. B resume: «He entendido que…». A corrige o confirma. Después se cambia." } },
  { id: "mobilisieren", dim: "collaborating", name: "Movilizar", icon: "mobilisieren",
    desc: "Inspirar a otras personas y capacitarlas para comprometerse con objetivos comunes y con la acción colectiva.",
    teacher: ["¿Qué me entusiasma de mi materia, y ve mi clase ese entusiasmo?", "¿Cómo gano a mis colegas para una idea, en lugar de convencerlos?"],
    students: ["¿Con qué te gustaría entusiasmar a otras personas?", "¿Quién te ha arrastrado alguna vez? ¿Cómo lo hizo?"],
    ideas: ["El alumnado planifica una acción para la escuela (una recogida, un quiosco de recreo, una exposición) y hace campaña por ella.", "Discursos breves: ganar apoyo para una causa en 60 segundos."],
    subjects: ["Lengua", "Trabajo por proyectos", "Economía y vida práctica"],
    exercise: { title: "Discurso de un minuto", text: "Cada persona elige una pequeña mejora para la clase. Un minuto para defenderla. La clase vota y se lleva a cabo la ganadora." } },

  { id: "mut", dim: "acting", name: "Valentía", icon: "mut",
    desc: "Defender valores fundamentales, tomar decisiones, pasar a la acción y, si es necesario, cuestionar y remover estructuras y opiniones establecidas.",
    teacher: ["¿Qué cambiaría en mis clases si no tuviera miedo a las críticas?", "¿Cuándo fue la última vez que discrepé en el claustro?"],
    students: ["¿Cuándo te atreviste a decir algo aunque fuera difícil?", "¿Cuál es la diferencia entre ser valiente y ser imprudente?"],
    ideas: ["Reunir historias de valentía: las criaturas cuentan pequeños momentos valientes, no hazañas.", "Ensayar escenas de valentía cívica en juego de rol: ¿qué digo cuando alguien se ríe de otra persona?"],
    subjects: ["Ética y ciudadanía", "Lengua", "Teatro", "Educación física"],
    exercise: { title: "Una pequeña valentía", text: "Cada persona piensa: ¿cuál sería hoy un pequeño paso valiente para mí? Escribirlo y doblar el papel. Mañana: ¿quién lo ha hecho?" } },
  { id: "hoffnung-und-optimismus", dim: "acting", name: "Esperanza y optimismo", icon: "hoffnung-und-optimismus",
    desc: "La convicción compartida de que se puede crear, construir y sostener un futuro más justo, más inclusivo y más sostenible.",
    teacher: ["¿Qué futuro transmito a mi clase: uno que se puede configurar o uno que hay que soportar?", "¿Qué me da esperanza en mi profesión?"],
    students: ["¿Qué ha mejorado en los últimos años?", "¿Qué podríamos lograr como clase que una sola persona no lograría?"],
    ideas: ["Buenas noticias de la semana: el alumnado busca qué está evolucionando de forma positiva.", "Historias de soluciones en lugar de historias de problemas: ¿quién ha resuelto ya un problema parecido, y cómo?"],
    subjects: ["Medios e informática", "Ciencias y sociedad", "Lengua"],
    exercise: { title: "Aun así", text: "Cada persona nombra una preocupación en una frase. Quien tiene al lado responde con una frase que empiece por «Aun así…»." } },
  { id: "bewusster-umgang-mit-ressourcen", dim: "acting", name: "Uso consciente de los recursos", icon: "bewusster-umgang-mit-ressourcen",
    desc: "Actuar con conciencia de los recursos naturales limitados de nuestro planeta, poniendo el acento en la conservación, la regeneración y la sobriedad para evitar un consumo dañino.",
    teacher: ["¿Qué consumo en mis clases sin pensarlo: papel, electricidad, material?", "¿Hablo de sostenibilidad, o se ve también en el aula?"],
    students: ["¿Qué acaba en tu papelera al final del día, y adónde podría ir en su lugar?", "De todo lo que tienes, ¿qué necesitas de verdad?"],
    ideas: ["Auditoría de residuos: durante una semana, reunir lo que se tira en el aula, después clasificarlo y deducir normas.", "Reparar en lugar de reemplazar: traer de casa cosas rotas y arreglarlas juntos."],
    subjects: ["Ciencias y tecnología", "Economía y vida práctica", "Tecnología y diseño", "Ciencias y sociedad"],
    exercise: { title: "Un objeto, tres vidas", text: "Elegir un objeto del estuche. ¿De dónde vino, qué pasa con él cuando se rompe? Por parejas, contar su historia en dos minutos." } },
  { id: "proaktiv-handeln", dim: "acting", name: "Actuar de forma proactiva", icon: "proaktiv-handeln",
    desc: "Los retos globales actuales exigen una acción orientada al futuro y responsable, basada en la solidaridad y en el respeto a la dignidad humana y a la Tierra viva.",
    teacher: ["¿Dónde espero a que otra persona resuelva un problema que yo veo desde hace tiempo?", "¿Qué responsabilidad confío a mi clase, y cuál le quito?"],
    students: ["¿Qué te molesta de la escuela tanto como para hacer algo al respecto?", "¿Qué podrías hacer ya mañana sin que nadie te lo encargue?"],
    ideas: ["Recoger una preocupación real del centro y acompañarla hasta su realización, con una carta a la dirección y no solo con un cartel.", "Repartir responsabilidades de forma estable: cada persona asume durante un trimestre una tarea que sirva a la comunidad."],
    subjects: ["Historia y geografía", "Trabajo por proyectos", "Ética y ciudadanía", "Economía y vida práctica"],
    exercise: { title: "Del enfado a la acción", text: "Cada persona nombra algo que le enfada. Quien tiene al lado responde con un primer paso que ya hoy sería posible." } },
  { id: "resilienz", dim: "acting", name: "Resiliencia", icon: "resilienz",
    desc: "Afrontar las adversidades y los obstáculos con flexibilidad, compromiso y constancia, incluso cuando el avance es lento o incierto.",
    teacher: ["¿A qué criatura estoy dando por perdida un poco por dentro, y qué haría falta para seguir con ella?", "¿Qué propósito abandoné demasiado pronto, y cuál debería haber adaptado antes?"],
    students: ["¿Qué sabes hacer hoy que antes no sabías? ¿Cómo lo aprendiste?", "¿Qué haces cuando algo falla por tercera vez: seguir igual o probar de otra manera?"],
    ideas: ["Hacer visible el progreso: poner uno al lado del otro trabajos de septiembre y de junio.", "Un proyecto largo a lo largo de un semestre con etapas intermedias: plantas, un diario, practicar una destreza."],
    subjects: ["Matemáticas", "Música", "Educación física", "Ciencias y tecnología"],
    exercise: { title: "Todavía no", text: "Reunir frases con «no sé hacerlo» y añadir en voz alta una palabra: «todavía no sé hacerlo». ¿Qué cambia esa palabra pequeña?" } }
];

export default { ui, dimensions, skills };
