// Español. La capa del marco (dimensiones, nombres y descripciones de las
// habilidades) se ha tomado literalmente de «IDG Framework (Spanish).pdf».
//
// Las preguntas de reflexión, las ideas para el aula, los vínculos con las
// materias y los miniejercicios no forman parte del marco IDG: se escribieron
// para esta aplicación y están traducidos del alemán. Las materias del plan de
// estudios suizo se han generalizado.
export const ui = {
  appName: "Los IDG en el aula",
  tagline: "23 habilidades. Una carta cada vez.",
  intro: "Los Inner Development Goals describen habilidades interiores que necesitamos para dar forma al cambio. Estas cartas las traducen a tu día a día docente.",
  tabs: { stack: "Mazo", dimensions: "Dimensiones", saved: "Guardadas", settings: "Ajustes" },
  language: "Idioma",
  cardDesign: "Diseño de las cartas",
  variantFarbe: "Carta en color",
  variantPapier: "Carta en papel",
  flipDirection: "Girar",
  flipH: "Horizontal",
  flipV: "Vertical",
  clearSaved: "Vaciar las guardadas",
  cleared: "Guardadas vaciadas",
  about: "Esta aplicación acerca los Inner Development Goals al profesorado: 23 habilidades, cada una con preguntas de reflexión para ti y para tu clase, además de ideas para el aula.",
  cardOfDay: "Carta del día",
  random: "Carta al azar",
  flipHint: "Toca para girar",
  swipeHint: "Desliza a la derecha para guardar",
  savedToast: "Guardada",
  front: "Habilidad",
  back: "Para el aula",
  forMe: "Para mí",
  forStudents: "Para mi clase",
  ideas: "En el aula",
  sheetSub: "Ideas, vínculos con las materias y miniejercicio",
  subjects: "Vínculos con las materias",
  exercise: "Miniejercicio · 5 minutos",
  save: "Guardar",
  saved: "Guardada",
  share: "Compartir",
  shared: "Copiado",
  next: "Siguiente",
  prev: "Atrás",
  emptySaved: "Todavía no has guardado ninguna carta.",
  emptySavedHint: "Toca «Guardar» cuando quieras que una carta te acompañe.",
  skillsCount: "habilidades",
  ofCards: "de",
  attribution: "Este trabajo se inspira en los Inner Development Goals. Más información en innerdevelopmentgoals.org",
  dimensionLabel: "Dimensión",
  allCards: "Todas las cartas",
  close: "Cerrar",
  level: "De primaria a bachillerato",
  orderRandom: "Orden aleatorio",
  orderGuide: "Orden de la guía",
  on: "Activado",
  off: "Desactivado",
  tapNext: "Toca para la siguiente pregunta"
};

export const dimensions = [
  { id: "being", num: 1, name: "Ser", subtitle: "Relación con el Yo", color: "#D4B88C",
    intro: "Cultivar nuestra vida interior y desarrollar y profundizar nuestra relación con nuestros pensamientos, sentimientos y cuerpo, nos ayuda a estar presentes, intencionales y no reactivos cuando nos enfrentamos a la complejidad." },
  { id: "thinking", num: 2, name: "Pensar", subtitle: "Habilidades cognitivas", color: "#E585A1",
    intro: "Desarrollar nuestras habilidades cognitivas tomando diferentes perspectivas, evaluando información y dando sentido al mundo como un todo interconectado, es esencial para tomar decisiones acertadas." },
  { id: "relating", num: 3, name: "Relacionarse", subtitle: "Cuidar de Los Demás y del Mundo", color: "#EF4136",
    intro: "Apreciar, cuidar, y sentirse conectados a otros, como pueden ser vecinos, generaciones futuras o a la biosfera, nos ayuda a crear sistemas y sociedades más justas y sostenibles para todos." },
  { id: "collaborating", num: 4, name: "Colaborar", subtitle: "Habilidades Sociales", color: "#FF7E2A",
    intro: "Para progresar en preocupaciones colectivas, necesitamos desarrollar habilidades que incluyan, mantengan el espacio y comuniquen con grupos de interés con diversos valores, aptitudes y competencias." },
  { id: "acting", num: 5, name: "Actuar", subtitle: "Facilitar el Cambio", color: "#661A30",
    intro: "Cualidades como la valentía y el optimismo nos ayudan a adquirir un verdadero empoderamiento, romper viejos patrones, generar ideas originales y actuar con persistencia en los momentos de incertidumbre." }
];

export const skills = [
  { id: "b1", dim: "being", name: "Brújula interior", icon: "b1-innerer-kompass",
    desc: "Tener un profundo sentido de la responsabilidad y el compromiso con valores y propósitos relacionados con el bien común.",
    teacher: ["¿Qué valor guió hoy mis decisiones en el aula, y en qué momento me aparté de él?", "¿Por qué me hice docente? ¿Cuánto de eso se notó esta semana?"],
    students: ["¿Qué te importa tanto como para defenderlo?", "¿En qué notas que algo te parece correcto o incorrecto?"],
    ideas: ["Mapa de valores: la clase reúne valores en tarjetas y los ordena en conjunto. ¿Qué nos une, en qué nos diferenciamos?", "No imponer las normas de clase, sino deducirlas de los valores compartidos."],
    subjects: ["Ética y ciudadanía", "Tutoría", "Lengua"],
    exercise: { title: "Mi frase de hoy", text: "Cada persona escribe en una frase lo que hoy le importa. Leerla en voz alta es voluntario. Al final del día, comprobar brevemente: ¿se cumplió?" } },
  { id: "b2", dim: "being", name: "Integridad y autenticidad", icon: "b2-integritaet-und-authentizitaet",
    desc: "Compromiso y capacidad para actuar con sinceridad, honestidad e integridad.",
    teacher: ["¿Cuándo fue la última vez que admití ante la clase que no sabía algo o que me había equivocado?", "¿Dónde digo cosas que en realidad no pienso del todo, y por qué?"],
    students: ["¿Cuándo te cuesta ser honesto?", "¿Qué significa para ti ser tú mismo?"],
    ideas: ["Hacer visible una cultura del error: un mural con «errores de los que hemos aprendido».", "Comentar historias-dilema: ¿qué harías si nadie se enterara?"],
    subjects: ["Ética y ciudadanía", "Lengua", "Tutoría"],
    exercise: { title: "Una respuesta sincera", text: "A la pregunta «¿cómo estás?» todo el mundo responde por una vez con sinceridad en lugar de «bien». Dos minutos en silencio y después intercambio por parejas." } },
  { id: "b3", dim: "being", name: "Apertura y mentalidad de aprendizaje", icon: "b3-offenheit-und-lernbereitschaft",
    desc: "Poseer una mente curiosa y una disposición a ser vulnerable y a aceptar el cambio y crecer.",
    teacher: ["¿Qué he aprendido esta semana de mi alumnado?", "¿Qué rutina de clase mantengo solo porque siempre lo he hecho así?"],
    students: ["¿Cuándo cambiaste de opinión por última vez? ¿Qué te convenció?", "¿Qué te gustaría aprender aunque nadie te lo pidiera?"],
    ideas: ["Intercambio de papeles: el alumnado enseña al docente algo que sabe hacer bien.", "Introducir tarjetas de «todavía no lo sé» como respuesta permitida en clase."],
    subjects: ["Todas las materias", "Tutoría", "Trabajo por proyectos"],
    exercise: { title: "Una pregunta curiosa", text: "Cada persona anota una pregunta para la que no tiene respuesta. Las preguntas van a la pared: se elige una en común y se sigue durante la semana." } },
  { id: "b4", dim: "being", name: "Autoconciencia", icon: "b4-selbsterkenntnis",
    desc: "Habilidad de contactar reflexivamente con los pensamientos, sentimientos y deseos propios; tener una imagen propia realista y saber autorregularse.",
    teacher: ["¿Qué situaciones de clase me sacan del equilibrio, y qué hay detrás?", "¿Cómo reacciono bajo estrés y cuánto percibe mi clase de ello?"],
    students: ["¿En qué notas en tu cuerpo que te estás enfadando o poniendo nervioso?", "¿Qué se te da bien, y cómo lo sabes?"],
    ideas: ["Un registro de emociones al empezar la clase, con tarjetas del tiempo o una escala del 1 al 5.", "Un diario de aprendizaje con una pregunta semanal: ¿qué me ayudó hoy, qué me frenó?"],
    subjects: ["Tutoría", "Ciencias y sociedad", "Educación física"],
    exercise: { title: "Mi tiempo interior", text: "Cerrar los ojos, tres respiraciones. ¿Qué tiempo hace dentro de mí ahora: soleado, nublado, tormentoso? Quien quiera lo comparte en una palabra." } },
  { id: "b5", dim: "being", name: "Presencia", icon: "b5-gegenwaertigkeit",
    desc: "Habilidad de estar en el aquí y ahora, sin juzgar y en un estado de presencia abierta.",
    teacher: ["¿Con cuánta frecuencia estoy, durante la clase, ya pensando en la siguiente?", "¿Cuándo he escuchado hoy de verdad a un alumno o alumna, sin saber ya la respuesta?"],
    students: ["¿Cuándo estuviste tan absorto que se te pasó el tiempo?", "¿Qué oyes ahora mismo si te quedas un minuto en completo silencio?"],
    ideas: ["Un minuto de silencio como ritual fijo después del recreo.", "Observación atenta en la naturaleza o ante una obra: cinco minutos solo mirando y después describir."],
    subjects: ["Educación física", "Educación plástica", "Música", "Ciencias y sociedad"],
    exercise: { title: "Cinco sentidos", text: "Uno tras otro: ¿qué veo, qué oigo, qué siento, qué huelo, qué saboreo? Treinta segundos cada uno, sin valorar." } },

  { id: "t1", dim: "thinking", name: "Pensamiento crítico", icon: "t1-kritisches-denken",
    desc: "Aptitudes para la revisión crítica y validación de opiniones, evidencia y planes.",
    teacher: ["¿Qué suposiciones sobre mi clase no he revisado últimamente?", "¿Dónde permito la discrepancia en clase y dónde la corto sin darme cuenta?"],
    students: ["¿Cómo sabes que eso es cierto?", "¿A quién le interesa que te lo creas?"],
    ideas: ["Comprobación de bulos: comparar dos noticias, examinar las fuentes, elaborar criterios.", "Un formato de debate con cambio de bando: cada postura se defiende una vez."],
    subjects: ["Medios e informática", "Lengua", "Historia y geografía", "Ciencias y tecnología"],
    exercise: { title: "Tres preguntas a una afirmación", text: "Una afirmación en la pizarra. En grupos: ¿de dónde viene? ¿Qué la contradice? ¿Qué necesitaríamos saber para estar seguros?" } },
  { id: "t2", dim: "thinking", name: "Conciencia de complejidad", icon: "t2-bewusstsein-fuer-komplexitaet",
    desc: "Comprensión y habilidades para trabajar con condiciones y causalidades complejas y sistémicas.",
    teacher: ["¿Qué problema de mi clase intento resolver con una solución simple aunque tenga muchas causas?", "¿Qué relaciones de fuera de la escuela influyen en mis clases?"],
    students: ["¿Qué cosas pasan cuando pasa una sola cosa?", "¿Dónde una causa pequeña produce un efecto grande?"],
    ideas: ["Dibujar una red de efectos: un tema (ruido en clase, plástico) en el centro y las causas y consecuencias como flechas.", "Un juego de sistemas: todos forman parte de un ciclo y viven cómo se transmite un cambio."],
    subjects: ["Ciencias y sociedad", "Historia y geografía", "Economía y vida práctica"],
    exercise: { title: "¿Y entonces?", text: "Nombrar un cambio (por ejemplo, «ya no hay deberes»). Preguntar en círculo: ¿y entonces? Cinco rondas, hasta que las consecuencias sorprendan." } },
  { id: "t3", dim: "thinking", name: "Habilidades de perspectiva", icon: "t3-perspektivische-faehigkeiten",
    desc: "Habilidades para buscar, entender y hacer uso activo de conocimientos desde perspectivas que contrasten.",
    teacher: ["¿Cómo se ve mi clase desde la perspectiva del niño más callado?", "¿Qué punto de vista falta en mis materiales?"],
    students: ["¿Cómo sonaría esta historia si la contara otro personaje?", "¿Qué podría pensar alguien que vive de forma muy distinta a ti?"],
    ideas: ["Volver a contar textos o hechos históricos desde la mirada de un personaje secundario.", "Línea de posturas: situarse en el aula ante una afirmación e intercambiar con alguien del extremo opuesto."],
    subjects: ["Lengua", "Historia y geografía", "Lenguas extranjeras", "Ética y ciudadanía"],
    exercise: { title: "Cambio de silla", text: "Hablar de un tema por parejas. A los dos minutos, cambiar de sitio y continuar defendiendo la postura de la otra persona." } },
  { id: "t4", dim: "thinking", name: "Búsqueda de sentido", icon: "t4-sinnstiftung",
    desc: "Habilidades para identificar patrones, estructurar lo desconocido y ser capaz de crear historias conscientemente.",
    teacher: ["¿Qué historia me cuento sobre mi clase, y sigue siendo cierta?", "¿Entiende mi alumnado por qué aprendemos lo que aprendemos?"],
    students: ["¿Qué tiene que ver con tu vida lo que hemos aprendido hoy?", "¿Qué patrón reconoces aquí?"],
    ideas: ["Empezar la clase con la pregunta «¿por qué aprendemos esto?» y dejar que la clase la responda al final.", "Mapas conceptuales en lugar de resúmenes: hacer visibles las relaciones."],
    subjects: ["Todas las materias", "Lengua", "Matemáticas"],
    exercise: { title: "El hilo conductor", text: "Tres conceptos de la semana pasada en la pizarra. Por parejas: ¿qué historia los conecta? Gana la versión más breve." } },
  { id: "t5", dim: "thinking", name: "Orientación y visión a largo plazo", icon: "t5-langfristige-orientierung",
    desc: "Orientación a largo plazo y capacidad para formular y mantener el compromiso con visiones relacionadas con el contexto más amplio.",
    teacher: ["¿Qué debería seguir llevándose mi alumnado de mis clases dentro de veinte años?", "¿Dónde optimizo para el próximo examen en lugar de para la comprensión duradera?"],
    students: ["¿Cómo debería ser tu barrio dentro de 30 años?", "¿Qué te gustaría que se dijera más adelante sobre tu generación?"],
    ideas: ["Escribir una carta al yo de dentro de diez años y guardarla en la escuela.", "Un taller de futuro: crítica, visión y realización, sobre un tema que afecte a la clase."],
    subjects: ["Historia y geografía", "Lengua", "Trabajo por proyectos", "Orientación profesional"],
    exercise: { title: "Viaje en el tiempo", text: "Cerrar los ojos: estamos en 2050. ¿Qué ha mejorado? ¿Quién ha contribuido? Una frase por persona." } },

  { id: "r1", dim: "relating", name: "Aprecio", icon: "r1-wertschaetzung",
    desc: "Relacionarse con los demás y con el mundo con un sentido básico de aprecio, gratitud y alegría.",
    teacher: ["¿A quién de mi clase no le he dicho todavía nada de reconocimiento esta semana?", "¿Por qué estoy agradecido en mi profesión, incluso en los días difíciles?"],
    students: ["¿Quién te ha ayudado hoy sin que se notara?", "¿Qué das por hecho aunque en realidad sea especial?"],
    ideas: ["Ducha cálida: una persona se sienta en el centro y todas nombran algo que valoran de ella.", "Un mural de la gratitud en el aula, ampliado cada semana."],
    subjects: ["Tutoría", "Ética y ciudadanía", "Lengua"],
    exercise: { title: "Tres cosas buenas", text: "Cada persona escribe tres cosas que hoy han estado bien, por pequeñas que sean. Compartir una con quien tenga al lado." } },
  { id: "r2", dim: "relating", name: "Conectividad", icon: "r2-verbundenheit",
    desc: "Tener una profunda conexión con los demás y/o formar parte de un conjunto más amplio, como puede ser una comunidad, la humanidad o el ecosistema global.",
    teacher: ["¿Se siente cada criatura de mi clase parte del grupo? ¿En qué lo noto?", "¿Dónde siento yo mismo esa conexión: con el claustro, la escuela, el lugar?"],
    students: ["¿A quién o a qué perteneces?", "¿Qué te une a una criatura de otro continente?"],
    ideas: ["Rastrear el origen de un objeto cotidiano: ¿quiénes han intervenido en él?", "Un hermanamiento de clase con una escuela de otro país o de otra región."],
    subjects: ["Ciencias y sociedad", "Historia y geografía", "Lenguas extranjeras"],
    exercise: { title: "La red de lana", text: "En círculo se lanza un ovillo de lana. Quien lo recoge dice algo que tiene en común con quien se lo ha lanzado. Al final todo el grupo sostiene una red." } },
  { id: "r3", dim: "relating", name: "Humildad", icon: "r3-bescheidenheit",
    desc: "Ser capaz de actuar de acuerdo con las necesidades de la situación sin preocuparse por la propia importancia.",
    teacher: ["¿Cuánto hablo yo en una clase y cuánto habla el grupo?", "¿Cuándo preferí por última vez la idea de un alumno o alumna a la mía?"],
    students: ["¿Cuándo importa más que el grupo avance que tener tú razón?", "¿Qué hacen otras personas mejor que tú, y cómo se siente eso?"],
    ideas: ["Discusión silenciosa sobre papel: cada voz recibe el mismo espacio.", "Rotar los papeles en los trabajos de grupo, también los menos vistosos."],
    subjects: ["Tutoría", "Educación física", "Todas las materias"],
    exercise: { title: "Escuchar sin responder", text: "Por parejas: una persona habla dos minutos y la otra solo escucha, sin comentar ni aconsejar. Después se cambia. ¿Cómo ha sido?" } },
  { id: "r4", dim: "relating", name: "Empatía y Compasión", icon: "r4-einfuehlungsvermoegen-und-mitgefuehl",
    desc: "Habilidad de relacionarse con los demás, con uno mismo y con la naturaleza, con bondad, empatía y compasión y abordar el sufrimiento del prójimo.",
    teacher: ["¿Qué conducta de mi clase me molesta, y qué necesidad podría haber detrás?", "¿Cómo me trato a mí mismo cuando una clase sale mal?"],
    students: ["¿En qué notas que alguien no está bien?", "¿Qué te sienta bien cuando estás triste, y podría ayudar también a otras personas?"],
    ideas: ["Ampliar el vocabulario emocional: describir imágenes o escenas y reunir palabras precisas.", "Cambio de perspectiva en los conflictos: cada parte escribe qué habrá sentido la otra."],
    subjects: ["Lengua", "Ética y ciudadanía", "Tutoría", "Educación plástica"],
    exercise: { title: "Un pensamiento amable", text: "Cada persona piensa en alguien que lo esté pasando mal y formula en silencio un buen deseo. Después dirige ese mismo deseo hacia sí misma." } },

  { id: "c1", dim: "collaborating", name: "Habilidad para la comunicación", icon: "c1-kommunikationsfaehigkeiten",
    desc: "Aptitud de realmente escuchar a los demás, promover el diálogo genuino, defender hábilmente nuestros puntos de vista, manejar conflictos constructivamente y adaptar la comunicación a grupos diversos.",
    teacher: ["¿Cuántas de mis preguntas en clase son preguntas de verdad, cuya respuesta desconozco?", "¿Cómo hablo distinto a las familias que al alumnado, y qué parte de ello resulta útil?"],
    students: ["¿En qué notas que alguien te escucha de verdad?", "¿Cómo le dices a alguien que algo te molesta sin herirle?"],
    ideas: ["Elaborar juntos las normas de conversación y colgarlas como cartel.", "Una asamblea de clase con papeles fijos: moderación, acta, tiempo, ambiente."],
    subjects: ["Lengua", "Lenguas extranjeras", "Tutoría"],
    exercise: { title: "Reflejar", text: "Por parejas: A cuenta durante un minuto. B resume: «He entendido que…». A corrige o confirma. Después se cambia." } },
  { id: "c2", dim: "collaborating", name: "Habilidades de co-creación", icon: "c2-mitgestaltungsfaehigkeiten",
    desc: "Habilidad y motivación para construir, desarrollar y facilitar relaciones colaborativas con grupos de interés diversos, caracterizado por la seguridad psicológica y la co-creación genuina.",
    teacher: ["¿Sobre qué puede decidir realmente mi alumnado, y sobre qué solo en apariencia?", "¿Se siente todo el mundo lo bastante seguro para decir una idea a medio hacer?"],
    students: ["¿Cuándo te ha sentado realmente bien un trabajo en grupo? ¿Qué fue distinto?", "¿Qué necesitas para atreverte a decir una idea sin terminar?"],
    ideas: ["Planificar juntos un proyecto de clase desde la idea hasta la ejecución, con el docente como acompañante.", "La regla del «sí, y…» en las lluvias de ideas: primero construir, después valorar."],
    subjects: ["Trabajo por proyectos", "Tecnología y diseño", "Tutoría"],
    exercise: { title: "Construir juntos", text: "Cada grupo recibe diez hojas de papel y construye la torre más alta, sin hablar. Después: ¿quién ha aportado y cómo?" } },
  { id: "c3", dim: "collaborating", name: "Mentalidad inclusiva y competencia intercultural", icon: "c3-inklusive-denkweise",
    desc: "Disposición y competencias para acoger la diversidad e incluir a personas y colectivos con perspectivas y experiencias diferentes.",
    teacher: ["¿Quién de mi clase aparece en los ejemplos, las imágenes y los textos, y quién no?", "¿Qué normalidad doy por supuesta sin darme cuenta?"],
    students: ["¿Qué es distinto en tu casa respecto a otras, y qué te gusta de ello?", "¿Cuándo te has sentido excluido alguna vez?"],
    ideas: ["Retrato lingüístico: cada persona dibuja sus lenguas en una silueta y la presenta.", "Incorporar al calendario del curso las fiestas y rituales presentes en la clase."],
    subjects: ["Lenguas extranjeras", "Ética y ciudadanía", "Historia y geografía", "Música"],
    exercise: { title: "Iguales y distintos", text: "Por parejas, encontrar en dos minutos tres cosas en común y tres diferencias. ¿Cuáles han sorprendido?" } },
  { id: "c4", dim: "collaborating", name: "Confianza", icon: "c4-vertrauen",
    desc: "Habilidad de demostrar confianza y crear y mantener relaciones basadas en la confianza.",
    teacher: ["¿Dónde controlo aunque podría confiar?", "¿Qué hago para que mi alumnado confíe en mí, también después de un conflicto?"],
    students: ["¿En quién confías, y por qué exactamente?", "¿Qué tendría que pasar para que volvieras a confiar en alguien?"],
    ideas: ["Ceder responsabilidad: cargos de clase, gestión del material, organización del recreo, sin supervisión.", "Un circuito de confianza en educación física con los ojos vendados."],
    subjects: ["Educación física", "Tutoría", "Todas las materias"],
    exercise: { title: "Guiar a ciegas", text: "Por parejas: una persona cierra los ojos y la otra la guía por el aula solo con la voz. Después se cambia. ¿Qué ha ayudado?" } },
  { id: "c5", dim: "collaborating", name: "Habilidades de movilización", icon: "c5-mobilisierungsfaehigkeiten",
    desc: "Habilidad de inspirar y movilizar a otras personas para participar en propósitos colectivos.",
    teacher: ["¿Qué me entusiasma de mi materia, y ve mi clase ese entusiasmo?", "¿Cómo gano a mis colegas para una idea, en lugar de convencerlos?"],
    students: ["¿Con qué te gustaría entusiasmar a otras personas?", "¿Quién te ha arrastrado alguna vez? ¿Cómo lo hizo?"],
    ideas: ["El alumnado planifica una acción para la escuela (una recogida, un quiosco de recreo, una exposición) y hace campaña por ella.", "Discursos breves: ganar apoyo para una causa en 60 segundos."],
    subjects: ["Lengua", "Trabajo por proyectos", "Economía y vida práctica"],
    exercise: { title: "Discurso de un minuto", text: "Cada persona elige una pequeña mejora para la clase. Un minuto para defenderla. La clase vota y se lleva a cabo la ganadora." } },

  { id: "a1", dim: "acting", name: "Valentía", icon: "a1-mut",
    desc: "Habilidad de defender valores, tomar decisiones, actuar de forma decisiva y, si fuese necesario, desafiar y alterar las estructuras y perspectivas existentes.",
    teacher: ["¿Qué cambiaría en mis clases si no tuviera miedo a las críticas?", "¿Cuándo fue la última vez que discrepé en el claustro?"],
    students: ["¿Cuándo te atreviste a decir algo aunque fuera difícil?", "¿Cuál es la diferencia entre ser valiente y ser imprudente?"],
    ideas: ["Reunir historias de valentía: las criaturas cuentan pequeños momentos valientes, no hazañas.", "Ensayar escenas de valentía cívica en juego de rol: ¿qué digo cuando alguien se ríe de otra persona?"],
    subjects: ["Ética y ciudadanía", "Lengua", "Teatro", "Educación física"],
    exercise: { title: "Una pequeña valentía", text: "Cada persona piensa: ¿cuál sería hoy un pequeño paso valiente para mí? Escribirlo y doblar el papel. Mañana: ¿quién lo ha hecho?" } },
  { id: "a2", dim: "acting", name: "Creatividad", icon: "a2-kreativitaet",
    desc: "Habilidad de generar y desarrollar ideas originales, innovar y estar dispuesto a disrumpir patrones convencionales.",
    teacher: ["¿Cuándo pudo mi alumnado hacer por última vez algo que todavía no existe?", "¿Qué tarea he planteado esta semana de modo que solo hubiera una respuesta correcta, y tenía que ser así?"],
    students: ["¿Cómo se podría resolver esto de una forma totalmente distinta?", "¿Qué inventarías si todo fuera posible?"],
    ideas: ["Tareas abiertas con varios caminos de solución, sobre todo en matemáticas.", "Ejercicio de inversión: un objeto cotidiano recibe un uso nuevo."],
    subjects: ["Educación plástica", "Matemáticas", "Tecnología y diseño", "Música"],
    exercise: { title: "30 círculos", text: "Una hoja con 30 círculos vacíos. En tres minutos convertir en algo los más posibles: pelota, reloj, pizza. Cantidad antes que calidad." } },
  { id: "a3", dim: "acting", name: "Optimismo", icon: "a3-optimismus",
    desc: "Habilidad de mantener y comunicar un sentido de esperanza, actitud positiva y confianza en la posibilidad de un cambio significativo.",
    teacher: ["¿Qué futuro transmito a mi clase: uno que se puede configurar o uno que hay que soportar?", "¿Qué me da esperanza en mi profesión?"],
    students: ["¿Qué ha mejorado en los últimos años?", "¿Con qué podrías contribuir para que algo salga bien?"],
    ideas: ["Buenas noticias de la semana: el alumnado busca qué está evolucionando de forma positiva.", "Historias de soluciones en lugar de historias de problemas: ¿quién ha resuelto un problema parecido?"],
    subjects: ["Medios e informática", "Ciencias y sociedad", "Lengua"],
    exercise: { title: "Aun así", text: "Cada persona nombra una preocupación en una frase. Quien tiene al lado responde con una frase que empiece por «Aun así…»." } },
  { id: "a4", dim: "acting", name: "Perseverancia", icon: "a4-beharrlichkeit",
    desc: "Habilidad de sostener compromiso y mantenerse determinado y paciente incluso cuando los esfuerzos tardan en dar frutos.",
    teacher: ["¿A qué criatura estoy dando por perdida un poco por dentro, y qué haría falta para seguir con ella?", "¿Qué propósito abandoné demasiado pronto?"],
    students: ["¿Qué sabes hacer hoy que antes no sabías? ¿Cómo lo aprendiste?", "¿Qué haces cuando algo no sale a la primera?"],
    ideas: ["Hacer visible el progreso: poner uno al lado del otro trabajos de septiembre y de junio.", "Un proyecto largo a lo largo de un semestre con etapas intermedias: plantas, un diario, practicar una destreza."],
    subjects: ["Matemáticas", "Música", "Educación física", "Ciencias y tecnología"],
    exercise: { title: "Todavía no", text: "Reunir frases con «no sé hacerlo» y añadir en voz alta una palabra: «todavía no sé hacerlo». ¿Qué cambia esa palabra pequeña?" } }
];

export default { ui, dimensions, skills };
