// Français. Couche « cadre » (dimensions, noms et descriptions des capacités)
// reprise telle quelle de « IDG Framework (French).pdf ».
//
// Deux corrections de coquilles de cette source : « Compéténcs
// communicationnelles » → « Compétences communicationnelles », et
// « Long-term Orientation et vision à long terme » (à moitié non traduit)
// → « Orientation et vision à long terme ».
//
// Les questions de réflexion, les idées pour la classe, les liens
// disciplinaires et les mini-exercices ne font pas partie du cadre IDG : ils
// ont été écrits pour cette application et sont traduits de l'allemand. Les
// disciplines du plan d'études suisse ont été généralisées.
export const ui = {
  appName: "Les IDG en classe",
  tagline: "23 capacités. Une carte à la fois.",
  intro: "Les Inner Development Goals décrivent les capacités intérieures dont nous avons besoin pour façonner le changement. Ces cartes les traduisent dans votre quotidien d'enseignement.",
  tabs: { stack: "Jeu", dimensions: "Dimensions", saved: "Favoris", settings: "Réglages" },
  language: "Langue",
  cardDesign: "Design des cartes",
  variantFarbe: "Carte couleur",
  variantPapier: "Carte papier",
  flipDirection: "Retourner",
  flipH: "Horizontal",
  flipV: "Vertical",
  clearSaved: "Vider les favoris",
  cleared: "Favoris vidés",
  about: "Cette application rend les Inner Development Goals accessibles aux enseignantes et enseignants : 23 capacités, chacune avec des questions de réflexion pour vous et pour votre classe, ainsi que des idées pour le cours.",
  cardOfDay: "Carte du jour",
  random: "Carte au hasard",
  flipHint: "Toucher pour retourner",
  swipeHint: "Glisser à droite pour garder",
  savedToast: "Dans les favoris",
  front: "Capacité",
  back: "Pour la classe",
  forMe: "Pour moi",
  forStudents: "Pour ma classe",
  ideas: "En classe",
  sheetSub: "Idées, liens disciplinaires et mini-exercice",
  subjects: "Liens disciplinaires",
  exercise: "Mini-exercice · 5 minutes",
  save: "Garder",
  saved: "Gardée",
  share: "Partager",
  shared: "Copié",
  next: "Suivante",
  prev: "Retour",
  emptySaved: "Aucune carte gardée pour l'instant.",
  emptySavedHint: "Touchez « Garder » si une carte doit vous accompagner.",
  skillsCount: "capacités",
  ofCards: "sur",
  attribution: "Ce travail s'inspire des Inner Development Goals. Plus d'informations sur innerdevelopmentgoals.org",
  dimensionLabel: "Dimension",
  allCards: "Toutes les cartes",
  close: "Fermer",
  level: "Du primaire au secondaire II",
  orderRandom: "Ordre aléatoire",
  orderGuide: "Ordre du guide",
  on: "Activé",
  off: "Désactivé",
  tapNext: "Toucher pour la question suivante"
};

export const dimensions = [
  { id: "being", num: 1, name: "Etre", subtitle: "Notre rapport à nous-mêmes", color: "#D4B88C",
    intro: "Le développement de notre vie intérieure, tout comme l'accroissement et l'approfondissement de notre relation avec nos pensées, nos sentiments et notre corps, nous aident à être présents et non réactifs lorsque nous sommes confrontés à la complexité." },
  { id: "thinking", num: 2, name: "Penser", subtitle: "Capacité cognitives", color: "#E585A1",
    intro: "Le développement de nos capacités cognitives en examinant différents angles, en évaluant les informations et en comprenant le monde en tant que tout interconnecté est essentiel pour une prise de décision sensée." },
  { id: "relating", num: 3, name: "Interagir", subtitle: "Prendre soin des autres et du monde", color: "#EF4136",
    intro: "Le fait de respecter les autres, d'en prendre soin et de se sentir connecté à eux – nos voisins, les générations futures, ou la biosphère, par exemple – nous aide à créer des systèmes et des sociétés plus justes et durables pour tout le monde." },
  { id: "collaborating", num: 4, name: "Collaborer", subtitle: "Compétences sociales", color: "#FF7E2A",
    intro: "Pour progresser concernant des préoccupations partagées, nous devons développer notre capacité à inclure des acteurs présentant des valeurs, des compétences et des talents différents, mais aussi notre capacité à leur faire une place et à communiquer avec eux." },
  { id: "acting", num: 5, name: "Agir", subtitle: "Etre moteur du changement", color: "#661A30",
    intro: "Les qualités telles que le courage et l'optimisme nous aident à nous responsabiliser véritablement, à casser les vieux schémas, à produire des idées originales et à agir avec persévérance en des temps incertains." }
];

export const skills = [
  { id: "b1", dim: "being", name: "Boussole intérieure", icon: "b1-innerer-kompass",
    desc: "Le fait d'éprouver un sens profond des responsabilités et un devoir d'engagement envers des valeurs et des objectifs liés au bien de tous.",
    teacher: ["Quelle valeur a guidé mes décisions en classe aujourd'hui – et où m'en suis-je écarté ?", "Pourquoi suis-je devenu enseignant ? Combien de cela était perceptible cette semaine ?"],
    students: ["Qu'est-ce qui compte assez pour toi pour que tu le défendes ?", "À quoi remarques-tu que quelque chose est juste ou faux pour toi ?"],
    ideas: ["Carte des valeurs : la classe rassemble des valeurs sur des cartes et les classe ensemble – qu'est-ce qui nous relie, où différons-nous ?", "Ne pas imposer les règles de classe, mais les déduire des valeurs communes."],
    subjects: ["Éthique et vie en société", "Heure de classe", "Français"],
    exercise: { title: "Ma phrase du jour", text: "Chacune et chacun écrit en une phrase ce qui compte pour elle ou lui aujourd'hui. Lecture à voix haute facultative. En fin de journée, vérifier brièvement : cela s'est-il vérifié ?" } },
  { id: "b2", dim: "being", name: "Intégrité et authenticité", icon: "b2-integritaet-und-authentizitaet",
    desc: "Un engagement et une capacité à agir avec sincérité, honnêteté et intégrité.",
    teacher: ["Quand ai-je admis pour la dernière fois devant la classe que je ne savais pas ou que j'avais fait une erreur ?", "Où est-ce que je dis des choses que je ne pense pas tout à fait – et pourquoi ?"],
    students: ["Quand est-ce difficile pour toi d'être honnête ?", "Que signifie pour toi être toi-même ?"],
    ideas: ["Rendre visible une culture de l'erreur : un mur des « erreurs dont nous avons appris ».", "Discuter d'histoires-dilemmes : que ferais-tu si personne ne l'apprenait ?"],
    subjects: ["Éthique et vie en société", "Français", "Heure de classe"],
    exercise: { title: "Une réponse sincère", text: "À « Comment ça va ? », tout le monde répond une fois sincèrement au lieu de « bien ». Deux minutes de silence, puis échange à deux." } },
  { id: "b3", dim: "being", name: "Ouverture et envie d'apprendre", icon: "b3-offenheit-und-lernbereitschaft",
    desc: "Le fait d'être fondamentalement curieux et d'accepter d'être vulnérable, d'accepter le changement et de grandir.",
    teacher: ["Qu'ai-je appris de mes élèves cette semaine ?", "Quelle routine d'enseignement est-ce que je garde simplement parce que j'ai toujours fait ainsi ?"],
    students: ["Quand as-tu changé d'avis pour la dernière fois ? Qu'est-ce qui t'a convaincu ?", "Qu'aimerais-tu apprendre, même si personne ne te le demande ?"],
    ideas: ["Échange de rôles : les élèves enseignent à l'enseignante ou l'enseignant quelque chose qu'ils maîtrisent.", "Introduire des cartes « je ne sais pas encore » comme réponse admise en classe."],
    subjects: ["Toutes les disciplines", "Heure de classe", "Travail de projet"],
    exercise: { title: "Une question curieuse", text: "Chacune et chacun note une question sans réponse. Les questions vont au mur – une est choisie ensemble et suivie durant la semaine." } },
  { id: "b4", dim: "being", name: "Conscience de soi", icon: "b4-selbsterkenntnis",
    desc: "Capacité d'être en contact avec ses propres pensées, sentiments et désirs et d'y réfléchir ; d'avoir une image de soi réaliste et de s'auto-réguler.",
    teacher: ["Quelles situations en classe me déséquilibrent – et qu'y a-t-il derrière ?", "Comment est-ce que je réagis sous stress, et qu'en perçoit ma classe ?"],
    students: ["À quoi remarques-tu dans ton corps que tu deviens fâché ou nerveux ?", "Qu'est-ce que tu sais bien faire – et comment le sais-tu ?"],
    ideas: ["Un point météo des émotions en début de leçon, avec des cartes ou une échelle de 1 à 5.", "Un journal d'apprentissage avec une question hebdomadaire : qu'est-ce qui m'a aidé aujourd'hui, qu'est-ce qui m'a freiné ?"],
    subjects: ["Heure de classe", "Sciences humaines et naturelles", "Éducation physique"],
    exercise: { title: "Météo intérieure", text: "Fermer les yeux, trois respirations. Quel temps fait-il en moi – ensoleillé, nuageux, orageux ? Qui veut le partage en un mot." } },
  { id: "b5", dim: "being", name: "Présence", icon: "b5-gegenwaertigkeit",
    desc: "Le fait d'être capable d'être là, ici et maintenant, sans jugement, avec un esprit d'ouverture.",
    teacher: ["Combien de fois suis-je déjà, pendant la leçon, en pensée à la suivante ?", "Quand ai-je vraiment écouté une ou un élève aujourd'hui – sans déjà connaître la réponse ?"],
    students: ["Quand as-tu été si absorbé que tu as oublié l'heure ?", "Qu'entends-tu maintenant si tu restes une minute complètement immobile ?"],
    ideas: ["Une minute de silence comme rituel fixe après la récréation.", "Observation attentive dans la nature ou devant une œuvre : cinq minutes à seulement regarder, puis décrire."],
    subjects: ["Éducation physique", "Arts visuels", "Musique", "Sciences humaines et naturelles"],
    exercise: { title: "Cinq sens", text: "L'un après l'autre : que vois-je, qu'entends-je, que sens-je, qu'est-ce que je hume, qu'est-ce que je goûte ? Trente secondes chaque fois, sans juger." } },

  { id: "t1", dim: "thinking", name: "Pensée critique", icon: "t1-kritisches-denken",
    desc: "Capacité à évaluer de manière critique la validité des opinions, des preuves et des projets.",
    teacher: ["Quelles hypothèses sur ma classe n'ai-je pas remises en question récemment ?", "Où est-ce que j'autorise la contradiction en classe – et où est-ce que je l'étouffe sans le vouloir ?"],
    students: ["Comment sais-tu que c'est vrai ?", "Qui a intérêt à ce que tu le croies ?"],
    ideas: ["Vérification d'infox : comparer deux dépêches, examiner les sources, élaborer des critères.", "Un format de débat avec changement de camp – chaque position est défendue une fois."],
    subjects: ["Médias et informatique", "Français", "Histoire et géographie", "Sciences et technique"],
    exercise: { title: "Trois questions pour une affirmation", text: "Une affirmation au tableau. En groupes : d'où vient-elle ? Qu'est-ce qui la contredit ? Que faudrait-il savoir pour en être sûr ?" } },
  { id: "t2", dim: "thinking", name: "Conscience de la complexité", icon: "t2-bewusstsein-fuer-komplexitaet",
    desc: "Comprendre des conditions et causalités complexes et systémiques tout en développant des compétences de travail en la matière.",
    teacher: ["Quel problème dans ma classe est-ce que j'essaie de régler par une solution simple alors qu'il a de multiples causes ?", "Quels liens hors de l'école agissent dans mon enseignement ?"],
    students: ["Qu'est-ce qui se passe, en tout, quand une chose se passe ?", "Où une petite cause produit-elle un grand effet ?"],
    ideas: ["Dessiner un réseau d'effets : un thème (bruit en classe, plastique) au centre, causes et conséquences en flèches.", "Un jeu systémique : chacun fait partie d'un cycle et éprouve comment un changement se transmet."],
    subjects: ["Sciences humaines et naturelles", "Histoire et géographie", "Économie et vie pratique"],
    exercise: { title: "Et ensuite ?", text: "Nommer un changement (par ex. « plus de devoirs à la maison »). Demander en cercle : et ensuite ? Cinq tours, jusqu'à ce que les conséquences surprennent." } },
  { id: "t3", dim: "thinking", name: "Capacités de mise en perspective", icon: "t3-perspektivische-faehigkeiten",
    desc: "Capacités en matière de recherche, de compréhension et d'utilisation active d'informations issues de perspectives contradictoires.",
    teacher: ["À quoi ressemble ma leçon vue par l'enfant le plus silencieux ?", "Quel point de vue manque dans mes supports d'enseignement ?"],
    students: ["Comment sonnerait cette histoire si un autre personnage la racontait ?", "Que pourrait penser quelqu'un dont la vie est très différente de la tienne ?"],
    ideas: ["Raconter à nouveau des textes ou des événements historiques du point de vue d'un personnage secondaire.", "Ligne de position : se placer dans la salle par rapport à une affirmation et échanger avec quelqu'un à l'autre bout."],
    subjects: ["Français", "Histoire et géographie", "Langues étrangères", "Éthique et vie en société"],
    exercise: { title: "Changement de chaise", text: "Discuter d'un sujet à deux. Après deux minutes, échanger les places – et poursuivre la position de l'autre." } },
  { id: "t4", dim: "thinking", name: "Donner du sens", icon: "t4-sinnstiftung",
    desc: "Capacité d'identification de schémas, de structuration de l'inconnu et de création consciente d'histoires.",
    teacher: ["Quelle histoire est-ce que je me raconte sur ma classe – et tient-elle encore ?", "Mes élèves comprennent-ils pourquoi nous apprenons ce que nous apprenons ?"],
    students: ["Qu'est-ce que ce que nous avons appris aujourd'hui a à voir avec ta vie ?", "Quel schéma reconnais-tu ici ?"],
    ideas: ["Commencer la leçon par la question « pourquoi apprenons-nous cela ? » et laisser la classe y répondre à la fin.", "Des cartes conceptuelles plutôt que des résumés : rendre les liens visibles."],
    subjects: ["Toutes les disciplines", "Français", "Mathématiques"],
    exercise: { title: "Le fil rouge", text: "Trois notions de la semaine passée au tableau. À deux : quelle histoire les relie ? La version la plus courte gagne." } },
  { id: "t5", dim: "thinking", name: "Orientation et vision à long terme", icon: "t5-langfristige-orientierung",
    desc: "Le fait d'être axé sur le long terme et la capacité à formuler et maintenir un engagement envers des visions liées à un contexte plus vaste.",
    teacher: ["Que devraient encore porter mes élèves de mon enseignement dans vingt ans ?", "Où est-ce que j'optimise pour la prochaine épreuve plutôt que pour une compréhension durable ?"],
    students: ["À quoi devrait ressembler ton quartier dans 30 ans ?", "Qu'aimerais-tu qu'on dise plus tard de ta génération ?"],
    ideas: ["Écrire une lettre à soi-même dans dix ans et la conserver à l'école.", "Un atelier du futur : critique – vision – mise en œuvre, sur un thème qui concerne la classe."],
    subjects: ["Histoire et géographie", "Français", "Travail de projet", "Orientation professionnelle"],
    exercise: { title: "Voyage dans le temps", text: "Fermer les yeux : nous sommes en 2050. Qu'est-ce qui s'est amélioré ? Qui y a contribué ? Une phrase par personne." } },

  { id: "r1", dim: "relating", name: "Respect", icon: "r1-wertschaetzung",
    desc: "Interagir avec les autres et le monde en faisant preuve, fondamentalement, de respect, de gratitude et de joie.",
    teacher: ["À qui, dans ma classe, n'ai-je encore rien dit de valorisant cette semaine ?", "De quoi suis-je reconnaissant dans mon métier – même les jours difficiles ?"],
    students: ["Qui t'a aidé aujourd'hui sans que cela se remarque ?", "Qu'est-ce que tu tiens pour acquis alors que c'est en fait précieux ?"],
    ideas: ["Douche chaude : une personne s'assied au milieu, tout le monde nomme ce qu'il apprécie chez elle.", "Un mur de la gratitude en classe, complété chaque semaine."],
    subjects: ["Heure de classe", "Éthique et vie en société", "Français"],
    exercise: { title: "Trois bonnes choses", text: "Chacune et chacun note trois choses qui ont été bonnes aujourd'hui – aussi petites soient-elles. En partager une avec son voisin ou sa voisine." } },
  { id: "r2", dim: "relating", name: "Connectivité", icon: "r2-verbundenheit",
    desc: "Le fait d'être fortement conscient de notre lien avec un tout plus vaste et/ou d'en faire partie – par exemple, une communauté, l'humanité, l'écosystème mondial.",
    teacher: ["Chaque enfant de ma classe se sent-il partie du groupe ? À quoi le vois-je ?", "Où est-ce que je ressens moi-même un lien – avec l'équipe, l'école, le lieu ?"],
    students: ["À qui ou à quoi appartiens-tu ?", "Qu'est-ce qui te relie à un enfant d'un autre continent ?"],
    ideas: ["Remonter à l'origine d'un objet du quotidien : qui a contribué à sa fabrication ?", "Un partenariat de classe avec une école d'un autre pays ou d'une autre région."],
    subjects: ["Sciences humaines et naturelles", "Histoire et géographie", "Langues étrangères"],
    exercise: { title: "La toile de laine", text: "En cercle : on se lance une pelote de laine. Qui l'attrape nomme un point commun avec la personne qui l'a lancée. À la fin, tout le monde tient une toile." } },
  { id: "r3", dim: "relating", name: "Humilité", icon: "r3-bescheidenheit",
    desc: "Etre capable d'agir conformément aux besoins de la situation sans se soucier de sa propre personne.",
    teacher: ["Combien est-ce que je parle pendant une leçon, et combien la classe ?", "Quand ai-je pour la dernière fois préféré l'idée d'une ou d'un élève à la mienne ?"],
    students: ["Quand est-il plus important que le groupe avance plutôt que d'avoir raison ?", "Que font les autres mieux que toi – et quel effet cela te fait-il ?"],
    ideas: ["Discussion silencieuse sur papier : chaque voix reçoit la même place.", "Faire tourner les rôles dans les travaux de groupe, y compris les plus discrets."],
    subjects: ["Heure de classe", "Éducation physique", "Toutes les disciplines"],
    exercise: { title: "Écouter sans répondre", text: "À deux : une personne raconte deux minutes, l'autre écoute seulement – ni commentaire, ni conseil. Puis échanger. Comment était-ce ?" } },
  { id: "r4", dim: "relating", name: "Empathie et compassion", icon: "r4-einfuehlungsvermoegen-und-mitgefuehl",
    desc: "La capacité d'interagir avec les autres, avec soi-même et avec la nature en faisant preuve de gentillesse, d'empathie et de compassion, et de traiter toute souffrance éprouvée dans ce contexte.",
    teacher: ["Quel comportement dans ma classe m'agace – et quel besoin pourrait se cacher derrière ?", "Comment est-ce que je me traite moi-même quand une leçon échoue ?"],
    students: ["À quoi remarques-tu que quelqu'un ne va pas bien ?", "Qu'est-ce qui te fait du bien quand tu es triste – et cela pourrait-il aider d'autres ?"],
    ideas: ["Élargir le vocabulaire des émotions : décrire des images ou des scènes, rassembler des mots précis.", "Changement de perspective dans les conflits : chaque partie écrit ce que l'autre a probablement ressenti."],
    subjects: ["Français", "Éthique et vie en société", "Heure de classe", "Arts visuels"],
    exercise: { title: "Une pensée bienveillante", text: "Chacune et chacun pense à quelqu'un qui traverse une période difficile. Formuler en silence un bon souhait. Puis adresser le même souhait à soi-même." } },

  { id: "c1", dim: "collaborating", name: "Compétences communicationnelles", icon: "c1-kommunikationsfaehigkeiten",
    desc: "La capacité d'écouter réellement les autres, d'encourager un véritable dialogue, de défendre son propre point de vue avec habileté, de gérer les conflits de manière constructive et d'adapter sa communication à son interlocuteur.",
    teacher: ["Combien de mes questions en classe sont de vraies questions dont j'ignore la réponse ?", "Comment est-ce que je parle autrement aux parents qu'aux élèves – et qu'y a-t-il d'utile là-dedans ?"],
    students: ["À quoi remarques-tu que quelqu'un t'écoute vraiment ?", "Comment dis-tu à quelqu'un que quelque chose te dérange, sans le blesser ?"],
    ideas: ["Élaborer ensemble des règles de discussion et les afficher.", "Un conseil de classe avec des rôles fixes : présidence, procès-verbal, temps, ambiance."],
    subjects: ["Français", "Langues étrangères", "Heure de classe"],
    exercise: { title: "Reformuler", text: "À deux : A raconte une minute. B résume : « J'ai compris que… » A corrige ou confirme. Échanger." } },
  { id: "c2", dim: "collaborating", name: "Compétences de co-création", icon: "c2-mitgestaltungsfaehigkeiten",
    desc: "Les compétences et la motivation permettant de construire, développer et faciliter des relations collaboratives avec différentes parties prenantes dans un contexte de sécurité psychologique et de réelle co-création.",
    teacher: ["Sur quoi mes élèves peuvent-ils réellement décider – et sur quoi seulement en apparence ?", "Chacune et chacun se sent-il assez en sécurité pour exprimer une idée à moitié aboutie ?"],
    students: ["Quand un travail de groupe s'est-il vraiment bien passé ? Qu'y avait-il de différent ?", "De quoi as-tu besoin pour oser dire une idée inachevée ?"],
    ideas: ["Planifier ensemble un projet de classe, de l'idée à la réalisation – l'enseignant comme accompagnant.", "La règle du « oui, et… » lors des récoltes d'idées : construire d'abord, évaluer ensuite."],
    subjects: ["Travail de projet", "Arts appliqués", "Heure de classe"],
    exercise: { title: "Construire ensemble", text: "Les groupes reçoivent dix feuilles de papier et construisent la tour la plus haute – sans parler. Ensuite : qui a contribué et comment ?" } },
  { id: "c3", dim: "collaborating", name: "Mentalité inclusive et compétences interculturelles", icon: "c3-inklusive-denkweise",
    desc: "Le désir et la capacité d'accueillir la diversité et d'inclure des gens et des groupes aux origines et avis différents.",
    teacher: ["Qui, dans ma classe, apparaît dans les exemples, les images et les textes – et qui n'y apparaît pas ?", "Quelle normalité est-ce que je présuppose sans m'en rendre compte ?"],
    students: ["Qu'est-ce qui est différent chez toi par rapport aux autres – et qu'est-ce que tu aimes là-dedans ?", "Quand t'es-tu déjà senti exclu ?"],
    ideas: ["Portrait linguistique : chacune et chacun dessine ses langues dans une silhouette et la présente.", "Intégrer au calendrier de l'année les fêtes et rituels présents dans la classe."],
    subjects: ["Langues étrangères", "Éthique et vie en société", "Histoire et géographie", "Musique"],
    exercise: { title: "Semblables et différents", text: "À deux, trouver en deux minutes trois points communs et trois différences. Lesquels ont surpris ?" } },
  { id: "c4", dim: "collaborating", name: "Confiance", icon: "c4-vertrauen",
    desc: "La capacité de manifester de la confiance et de créer et d'entretenir des relations basées sur la confiance.",
    teacher: ["Où est-ce que je contrôle alors que je pourrais faire confiance ?", "Que fais-je pour que mes élèves me fassent confiance – même après un conflit ?"],
    students: ["À qui fais-tu confiance – et pourquoi exactement ?", "Que faudrait-il pour que tu refasses confiance à quelqu'un ?"],
    ideas: ["Confier des responsabilités : charges de classe, gestion du matériel, organisation de la récréation, sans contrôle.", "Un parcours de confiance en éducation physique, les yeux bandés."],
    subjects: ["Éducation physique", "Heure de classe", "Toutes les disciplines"],
    exercise: { title: "Guider à l'aveugle", text: "À deux : une personne ferme les yeux, l'autre la guide dans la salle uniquement à la voix. Échanger. Qu'est-ce qui a aidé ?" } },
  { id: "c5", dim: "collaborating", name: "Capacités de mobilisation", icon: "c5-mobilisierungsfaehigkeiten",
    desc: "Etre capable d'inspirer et de mobiliser les autres pour qu'ils s'investissent dans des objectifs communs.",
    teacher: ["Qu'est-ce qui m'enthousiasme dans ma discipline – et ma classe voit-elle cet enthousiasme ?", "Comment est-ce que je gagne des collègues à une idée, plutôt que de les convaincre ?"],
    students: ["Pour quoi voudrais-tu enthousiasmer les autres ?", "Qui t'a déjà entraîné – comment cette personne s'y est-elle prise ?"],
    ideas: ["Les élèves planifient une action pour l'école (collecte, kiosque de récréation, exposition) et font campagne pour elle.", "Discours courts : convaincre pour une cause en 60 secondes."],
    subjects: ["Français", "Travail de projet", "Économie et vie pratique"],
    exercise: { title: "Le pitch d'une minute", text: "Chacune et chacun choisit une petite amélioration pour la classe. Une minute pour la défendre. La classe vote – et met en œuvre la gagnante." } },

  { id: "a1", dim: "acting", name: "Courage", icon: "a1-mut",
    desc: "La capacité de se battre pour des valeurs, de prendre des décisions, d'agir de manière décisive et, si nécessaire, de défier et perturber des structures et opinions existantes.",
    teacher: ["Que changerais-je dans mon enseignement si je n'avais pas peur des critiques ?", "Quand ai-je pour la dernière fois exprimé un désaccord au sein de l'équipe ?"],
    students: ["Quand as-tu osé dire quelque chose alors que c'était difficile ?", "Quelle est la différence entre courageux et imprudent ?"],
    ideas: ["Rassembler des histoires de courage : les enfants racontent de petits moments courageux – pas des exploits.", "Exercer des scènes de courage civique en jeu de rôle : que dis-je quand quelqu'un se fait moquer ?"],
    subjects: ["Éthique et vie en société", "Français", "Théâtre", "Éducation physique"],
    exercise: { title: "Un petit courage", text: "Chacune et chacun réfléchit : quel serait aujourd'hui un petit pas courageux pour moi ? L'écrire, plier le papier. Demain : qui l'a fait ?" } },
  { id: "a2", dim: "acting", name: "Créativité", icon: "a2-kreativitaet",
    desc: "La capacité de générer et de développer des idées originales, d'innover, et d'être désireux de perturber les schémas conventionnels.",
    teacher: ["Quand mes élèves ont-ils pu, pour la dernière fois, faire quelque chose qui n'existe pas encore ?", "Quelle tâche ai-je posée cette semaine de sorte qu'une seule réponse soit juste – fallait-il que ce soit ainsi ?"],
    students: ["Comment pourrait-on résoudre cela tout autrement ?", "Qu'inventerais-tu si tout était possible ?"],
    ideas: ["Des tâches ouvertes avec plusieurs chemins de solution – en mathématiques notamment.", "Exercice d'inversion : un objet du quotidien reçoit un nouvel usage."],
    subjects: ["Arts visuels", "Mathématiques", "Arts appliqués", "Musique"],
    exercise: { title: "30 cercles", text: "Une feuille avec 30 cercles vides. En trois minutes, en transformer le plus possible – ballon, montre, pizza. La quantité avant la qualité." } },
  { id: "a3", dim: "acting", name: "Optimisme", icon: "a3-optimismus",
    desc: "La capacité d'entretenir et de communiquer un sens de l'espoir, une attitude positive et sa confiance dans la possibilité d'un changement significatif.",
    teacher: ["Quel avenir est-ce que je transmets à ma classe – un avenir qu'on façonne, ou un avenir qu'on subit ?", "Qu'est-ce qui me donne de l'espoir dans mon métier ?"],
    students: ["Qu'est-ce qui s'est amélioré ces dernières années ?", "Que pourrais-tu faire pour que quelque chose se termine bien ?"],
    ideas: ["Bonnes nouvelles de la semaine : les élèves cherchent ce qui évolue positivement.", "Des histoires de solutions plutôt que de problèmes : qui a résolu un problème semblable ?"],
    subjects: ["Médias et informatique", "Sciences humaines et naturelles", "Français"],
    exercise: { title: "Malgré tout", text: "Chacune et chacun nomme un souci en une phrase. Le voisin ou la voisine répond par une phrase commençant par « Malgré tout… »." } },
  { id: "a4", dim: "acting", name: "Persévérance", icon: "a4-beharrlichkeit",
    desc: "La capacité de maintenir son engagement et de rester déterminé et patient lorsque nos efforts mettent du temps à porter leurs fruits.",
    teacher: ["Quel enfant est-ce que j'abandonne un peu intérieurement – et que faudrait-il pour rester présent ?", "Quel projet ai-je laissé tomber trop tôt ?"],
    students: ["Que sais-tu faire aujourd'hui que tu ne savais pas faire avant ? Comment l'as-tu appris ?", "Que fais-tu quand quelque chose ne marche pas du premier coup ?"],
    ideas: ["Rendre les progrès visibles : poser côte à côte des travaux de septembre et de juin.", "Un projet long sur un semestre avec des étapes intermédiaires – plantes, journal, entraînement d'une habileté."],
    subjects: ["Mathématiques", "Musique", "Éducation physique", "Sciences et technique"],
    exercise: { title: "Pas encore", text: "Rassembler des phrases avec « je n'y arrive pas » et y ajouter un mot à voix haute : « je n'y arrive pas encore ». Que change ce petit mot ?" } }
];

export default { ui, dimensions, skills };
