// Français. Contenu : Inner Development Guide 2.0 (version 7.2) — 25 capacités en
// cinq dimensions. La couche « cadre » (noms et sous-titres des dimensions,
// introductions, noms et descriptions des capacités) est traduite de l'édition
// allemande du guide, la source à partir de laquelle cette application a été mise
// à jour ; la formulation française de la version 1.0 a été conservée là où elle
// correspond encore à la définition 2.0.
//
// Les questions de réflexion, les idées pour la classe, les liens disciplinaires
// et les mini-exercices ne font pas partie du cadre IDG : ils ont été écrits pour
// cette application et sont traduits de l'allemand. Les disciplines du plan
// d'études suisse ont été généralisées.
export const ui = {
  appName: "Les IDG en classe",
  tagline: "25 capacités. Une carte à la fois.",
  intro: "Les Inner Development Goals décrivent les capacités intérieures dont nous avons besoin pour façonner le changement. Ces cartes les traduisent dans votre quotidien d'enseignement.",
  tabs: { stack: "Jeu", dimensions: "Dimensions", saved: "Favoris", settings: "Réglages" },
  language: "Langue",
  cardDesign: "Design des cartes",
  variantFarbe: "Carte couleur",
  variantPapier: "Carte papier",
  flipDirection: "Retourner",
  flipH: "Horizontal",
  flipV: "Vertical",
  clearSaved: "Vider les favoris",
  cleared: "Favoris vidés",
  about: "Cette application rend les Inner Development Goals accessibles aux enseignantes et enseignants : 25 capacités, chacune avec des questions de réflexion pour vous et pour votre classe, ainsi que des idées pour le cours.",
  cardOfDay: "Carte du jour",
  random: "Carte au hasard",
  flipHint: "Toucher pour retourner",
  swipeHint: "Glisser à droite pour garder",
  savedToast: "Dans les favoris",
  front: "Capacité",
  back: "Pour la classe",
  forMe: "Pour moi",
  forStudents: "Pour ma classe",
  ideas: "En classe",
  sheetSub: "Idées, liens disciplinaires et mini-exercice",
  subjects: "Liens disciplinaires",
  exercise: "Mini-exercice · 5 minutes",
  save: "Garder",
  saved: "Gardée",
  share: "Partager",
  shared: "Copié",
  next: "Suivante",
  prev: "Retour",
  emptySaved: "Aucune carte gardée pour l'instant.",
  emptySavedHint: "Touchez « Garder » si une carte doit vous accompagner.",
  skillsCount: "capacités",
  ofCards: "sur",
  attribution: "Ce travail s'inspire des Inner Development Goals. Plus d'informations sur innerdevelopmentgoals.org",
  dimensionLabel: "Dimension",
  allCards: "Toutes les cartes",
  close: "Fermer",
  level: "Du primaire au secondaire II",
  orderRandom: "Ordre aléatoire",
  orderGuide: "Ordre du guide",
  on: "Activé",
  off: "Désactivé",
  tapNext: "Toucher pour la question suivante"
};

export const dimensions = [
  { id: "being", num: 1, name: "Etre", subtitle: "Cultiver notre vie intérieure", color: "#D4B88C",
    intro: "Un monde complexe exige plus que jamais une conscience approfondie de notre expérience intérieure et de notre relation dynamique au monde qui nous entoure. Cela sollicite et renforce notre attention et notre présence, notre clarté intérieure et notre capacité à agir de manière réfléchie." },
  { id: "thinking", num: 2, name: "Penser", subtitle: "Comprendre notre monde complexe", color: "#E585A1",
    intro: "Prendre en compte des perspectives différentes et les conséquences à long terme de nos actes nous aide à comprendre la complexité de notre monde, à composer avec elle et à prendre des décisions plus avisées dans un monde interconnecté." },
  { id: "relating", num: 3, name: "Interagir", subtitle: "Prendre soin des autres et du monde", color: "#EF4136",
    intro: "Par la bienveillance, la compassion et le sentiment d'appartenir à des communautés, à la planète vivante et aux générations futures, nous créons un monde plus juste, plus inclusif et plus florissant." },
  { id: "collaborating", num: 4, name: "Collaborer", subtitle: "Bâtir la confiance et travailler ensemble", color: "#FF7E2A",
    intro: "Bâtir des relations de confiance, reconnaître la diversité des valeurs, des capacités et des perspectives et créer des espaces sûrs permettent à chacune et chacun de contribuer à des objectifs communs et à un impact collectif." },
  { id: "acting", num: 5, name: "Agir", subtitle: "Initier et rendre possible le changement", color: "#661A30",
    intro: "Lorsque nous avançons avec courage et optimisme et que nous développons nos capacités communes, nous pouvons agir avec détermination et persévérance. En temps incertains, cela transforme nos visions communes en changements concrets et porteurs de sens." }
];

export const skills = [
  { id: "innerer-kompass", dim: "being", name: "Boussole intérieure", icon: "innerer-kompass",
    desc: "Un engagement profondément ressenti à vivre et à agir en accord avec des valeurs et des objectifs qui servent le bien de tous.",
    teacher: ["Quelle valeur a guidé mes décisions en classe aujourd'hui – et où m'en suis-je écarté ?", "Pourquoi suis-je devenu enseignant ? Combien de cela était perceptible cette semaine ?"],
    students: ["Qu'est-ce qui compte assez pour toi pour que tu le défendes ?", "À quoi remarques-tu que quelque chose est juste ou faux pour toi ?"],
    ideas: ["Carte des valeurs : la classe rassemble des valeurs sur des cartes et les classe ensemble – qu'est-ce qui nous relie, où différons-nous ?", "Ne pas imposer les règles de classe, mais les déduire des valeurs communes."],
    subjects: ["Éthique et vie en société", "Heure de classe", "Français"],
    exercise: { title: "Ma phrase du jour", text: "Chacune et chacun écrit en une phrase ce qui compte pour elle ou lui aujourd'hui. Lecture à voix haute facultative. En fin de journée, vérifier brièvement : cela s'est-il vérifié ?" } },
  { id: "integritaet-und-authentizitaet", dim: "being", name: "Intégrité et authenticité", icon: "integritaet-und-authentizitaet",
    desc: "Un engagement sincère envers l'honnêteté et des valeurs solidement ancrées, qui s'expriment et s'incarnent dans tous les actes.",
    teacher: ["Quand ai-je admis pour la dernière fois devant la classe que je ne savais pas ou que j'avais fait une erreur ?", "Où est-ce que je dis des choses que je ne pense pas tout à fait – et pourquoi ?"],
    students: ["Quand est-ce difficile pour toi d'être honnête ?", "Que signifie pour toi être toi-même ?"],
    ideas: ["Rendre visible une culture de l'erreur : un mur des « erreurs dont nous avons appris ».", "Discuter d'histoires-dilemmes : que ferais-tu si personne ne l'apprenait ?"],
    subjects: ["Éthique et vie en société", "Français", "Heure de classe"],
    exercise: { title: "Une réponse sincère", text: "À « Comment ça va ? », tout le monde répond une fois sincèrement au lieu de « bien ». Deux minutes de silence, puis échange à deux." } },
  { id: "offenheit-und-lernbereitschaft", dim: "being", name: "Ouverture et envie d'apprendre", icon: "offenheit-und-lernbereitschaft",
    desc: "Une attitude curieuse et adaptable, et la disposition à changer de perspective, à se montrer vulnérable, à accueillir le changement et à grandir.",
    teacher: ["Qu'ai-je appris de mes élèves cette semaine ?", "Quelle routine d'enseignement est-ce que je garde simplement parce que j'ai toujours fait ainsi ?"],
    students: ["Quand as-tu changé d'avis pour la dernière fois ? Qu'est-ce qui t'a convaincu ?", "Qu'aimerais-tu apprendre, même si personne ne te le demande ?"],
    ideas: ["Échange de rôles : les élèves enseignent à l'enseignante ou l'enseignant quelque chose qu'ils maîtrisent.", "Introduire des cartes « je ne sais pas encore » comme réponse admise en classe."],
    subjects: ["Toutes les disciplines", "Heure de classe", "Travail de projet"],
    exercise: { title: "Une question curieuse", text: "Chacune et chacun note une question sans réponse. Les questions vont au mur – une est choisie ensemble et suivie durant la semaine." } },
  { id: "selbsterkenntnis", dim: "being", name: "Conscience de soi", icon: "selbsterkenntnis",
    desc: "La capacité d'entretenir un rapport réfléchi à ses pensées, ses émotions, ses désirs et ses actes, de garder une image de soi réaliste et de s'auto-réguler.",
    teacher: ["Quelles situations en classe me déséquilibrent – et qu'y a-t-il derrière ?", "Comment est-ce que je réagis sous stress, et qu'en perçoit ma classe ?"],
    students: ["À quoi remarques-tu dans ton corps que tu deviens fâché ou nerveux ?", "Qu'est-ce que tu sais bien faire – et comment le sais-tu ?"],
    ideas: ["Un point météo des émotions en début de leçon, avec des cartes ou une échelle de 1 à 5.", "Un journal d'apprentissage avec une question hebdomadaire : qu'est-ce qui m'a aidé aujourd'hui, qu'est-ce qui m'a freiné ?"],
    subjects: ["Heure de classe", "Sciences humaines et naturelles", "Éducation physique"],
    exercise: { title: "Météo intérieure", text: "Fermer les yeux, trois respirations. Quel temps fait-il en moi – ensoleillé, nuageux, orageux ? Qui veut le partage en un mot." } },
  { id: "praesenz", dim: "being", name: "Présence", icon: "praesenz",
    desc: "La capacité d'être pleinement présent ici et maintenant, d'accepter la réalité telle qu'elle est et d'y répondre de manière sensée.",
    teacher: ["Combien de fois suis-je déjà, pendant la leçon, en pensée à la suivante ?", "Quand ai-je vraiment écouté une ou un élève aujourd'hui – sans déjà connaître la réponse ?"],
    students: ["Quand as-tu été si absorbé que tu as oublié l'heure ?", "Qu'entends-tu maintenant si tu restes une minute complètement immobile ?"],
    ideas: ["Une minute de silence comme rituel fixe après la récréation.", "Observation attentive dans la nature ou devant une œuvre : cinq minutes à seulement regarder, puis décrire."],
    subjects: ["Éducation physique", "Arts visuels", "Musique", "Sciences humaines et naturelles"],
    exercise: { title: "Cinq sens", text: "L'un après l'autre : que vois-je, qu'entends-je, que sens-je, qu'est-ce que je hume, qu'est-ce que je goûte ? Trente secondes chaque fois, sans juger." } },

  { id: "kritisches-denken", dim: "thinking", name: "Pensée critique", icon: "kritisches-denken",
    desc: "La capacité de réfléchir à la validité des idées, des preuves, des hypothèses et des projets.",
    teacher: ["Quelles hypothèses sur ma classe n'ai-je pas remises en question récemment ?", "Où est-ce que j'autorise la contradiction en classe – et où est-ce que je l'étouffe sans le vouloir ?"],
    students: ["Comment sais-tu que c'est vrai ?", "Qui a intérêt à ce que tu le croies ?"],
    ideas: ["Vérification d'infox : comparer deux dépêches, examiner les sources, élaborer des critères.", "Un format de débat avec changement de camp – chaque position est défendue une fois."],
    subjects: ["Médias et informatique", "Français", "Histoire et géographie", "Sciences et technique"],
    exercise: { title: "Trois questions pour une affirmation", text: "Une affirmation au tableau. En groupes : d'où vient-elle ? Qu'est-ce qui la contredit ? Que faudrait-il savoir pour en être sûr ?" } },
  { id: "perspektivische-faehigkeiten", dim: "thinking", name: "Capacités de mise en perspective", icon: "perspektivische-faehigkeiten",
    desc: "La capacité de prendre en compte des perspectives différentes et de faire entrer ces apports dans une compréhension et une action réfléchies.",
    teacher: ["À quoi ressemble ma leçon vue par l'enfant le plus silencieux ?", "Quelle histoire est-ce que je me raconte sur ma classe – et tient-elle encore ?"],
    students: ["Comment sonnerait cette histoire si un autre personnage la racontait ?", "Que pourrait penser quelqu'un dont la vie est très différente de la tienne ?"],
    ideas: ["Raconter à nouveau des textes ou des événements historiques du point de vue d'un personnage secondaire.", "Ligne de position : se placer dans la salle par rapport à une affirmation et échanger avec quelqu'un à l'autre bout."],
    subjects: ["Français", "Histoire et géographie", "Langues étrangères", "Éthique et vie en société"],
    exercise: { title: "Changement de chaise", text: "Discuter d'un sujet à deux. Après deux minutes, échanger les places – et poursuivre la position de l'autre." } },
  { id: "systemisches-denken", dim: "thinking", name: "Pensée systémique", icon: "systemisches-denken",
    desc: "La capacité de comprendre les interdépendances complexes et les propriétés des systèmes et de les utiliser activement.",
    teacher: ["Quel problème dans ma classe est-ce que j'essaie de régler par une solution simple alors qu'il a de multiples causes ?", "Quels liens hors de l'école agissent dans mon enseignement ?"],
    students: ["Qu'est-ce qui se passe, en tout, quand une chose se passe ?", "Quel schéma reconnais-tu ici – et où l'as-tu déjà vu ?"],
    ideas: ["Un réseau d'effets plutôt qu'un résumé : un thème (bruit en classe, plastique) au centre, causes et conséquences en flèches – dessiner les liens au lieu de les énumérer.", "Un jeu systémique : chacun fait partie d'un cycle et éprouve comment un changement se transmet. Ensuite, chercher où se trouve le levier."],
    subjects: ["Sciences humaines et naturelles", "Histoire et géographie", "Économie et vie pratique", "Sciences et technique"],
    exercise: { title: "Et ensuite ?", text: "Nommer un changement (par ex. « plus de devoirs à la maison »). Demander en cercle : et ensuite ? Cinq tours, jusqu'à ce que les conséquences surprennent." } },
  { id: "langfristige-orientierung", dim: "thinking", name: "Orientation et vision à long terme", icon: "langfristige-orientierung",
    desc: "Développer des objectifs à long terme et les poursuivre d'une manière qui favorise le bien-être social et écologique.",
    teacher: ["Que devraient encore porter mes élèves de mon enseignement dans vingt ans ?", "Où est-ce que j'optimise pour la prochaine épreuve plutôt que pour une compréhension durable ?"],
    students: ["À quoi devrait ressembler ton quartier dans 30 ans ?", "Qu'aimerais-tu qu'on dise plus tard de ta génération ?"],
    ideas: ["Commencer la leçon par « pourquoi apprenons-nous cela ? » et laisser la classe y répondre à la fin – qu'est-ce qui dure au-delà de l'année scolaire ?", "Un atelier du futur : critique – vision – mise en œuvre, sur un thème qui concerne la classe."],
    subjects: ["Histoire et géographie", "Français", "Travail de projet", "Orientation professionnelle"],
    exercise: { title: "Voyage dans le temps", text: "Fermer les yeux : nous sommes en 2050. Qu'est-ce qui s'est amélioré ? Qui y a contribué ? Une phrase par personne." } },
  { id: "kreativitaet", dim: "thinking", name: "Créativité", icon: "kreativitaet",
    desc: "La capacité de penser au-delà des schémas conventionnels, de développer de nouvelles possibilités et de les traduire en idées transformatrices.",
    teacher: ["Quand mes élèves ont-ils pu, pour la dernière fois, faire quelque chose qui n'existe pas encore ?", "Quelle tâche ai-je posée cette semaine de sorte qu'une seule réponse soit juste – fallait-il que ce soit ainsi ?"],
    students: ["Comment pourrait-on résoudre cela tout autrement ?", "Qu'inventerais-tu si tout était possible ?"],
    ideas: ["Des tâches ouvertes avec plusieurs chemins de solution – en mathématiques notamment.", "Exercice d'inversion : un objet du quotidien reçoit un nouvel usage."],
    subjects: ["Arts visuels", "Mathématiques", "Arts appliqués", "Musique"],
    exercise: { title: "30 cercles", text: "Une feuille avec 30 cercles vides. En trois minutes, en transformer le plus possible – ballon, montre, pizza. La quantité avant la qualité." } },

  { id: "wertschaetzung", dim: "relating", name: "Respect", icon: "wertschaetzung",
    desc: "Aller vers les personnes et vers la planète Terre avec appréciation, joie et gratitude.",
    teacher: ["À qui, dans ma classe, n'ai-je encore rien dit de valorisant cette semaine ?", "De quoi suis-je reconnaissant dans mon métier – même les jours difficiles ?"],
    students: ["Qui t'a aidé aujourd'hui sans que cela se remarque ?", "Qu'est-ce que tu tiens pour acquis alors que c'est en fait précieux ?"],
    ideas: ["Douche chaude : une personne s'assied au milieu, tout le monde nomme ce qu'il apprécie chez elle.", "Un mur de la gratitude en classe, complété chaque semaine."],
    subjects: ["Heure de classe", "Éthique et vie en société", "Français"],
    exercise: { title: "Trois bonnes choses", text: "Chacune et chacun note trois choses qui ont été bonnes aujourd'hui – aussi petites soient-elles. En partager une avec son voisin ou sa voisine." } },
  { id: "verbundenheit", dim: "relating", name: "Connectivité", icon: "verbundenheit",
    desc: "Le sentiment d'appartenir à un tout plus vaste : l'humanité, la toile du vivant sur la planète et les dimensions spirituelles de l'existence.",
    teacher: ["Chaque enfant de ma classe se sent-il partie du groupe ? À quoi le vois-je ?", "Où est-ce que je ressens moi-même un lien – avec l'équipe, l'école, le lieu ?"],
    students: ["À qui ou à quoi appartiens-tu ?", "Qu'est-ce qui te relie à un enfant d'un autre continent ?"],
    ideas: ["Remonter à l'origine d'un objet du quotidien : qui a contribué à sa fabrication ?", "Un partenariat de classe avec une école d'un autre pays ou d'une autre région."],
    subjects: ["Sciences humaines et naturelles", "Histoire et géographie", "Langues étrangères"],
    exercise: { title: "La toile de laine", text: "En cercle : on se lance une pelote de laine. Qui l'attrape nomme un point commun avec la personne qui l'a lancée. À la fin, tout le monde tient une toile." } },
  { id: "demut-und-bescheidenheit", dim: "relating", name: "Humilité et modestie", icon: "demut-und-bescheidenheit",
    desc: "Être capable de répondre aux exigences d'une situation sans mettre en avant sa propre importance.",
    teacher: ["Combien est-ce que je parle pendant une leçon, et combien la classe ?", "Quand ai-je pour la dernière fois préféré l'idée d'une ou d'un élève à la mienne ?"],
    students: ["Quand est-il plus important que le groupe avance plutôt que d'avoir raison ?", "Que font les autres mieux que toi – et quel effet cela te fait-il ?"],
    ideas: ["Discussion silencieuse sur papier : chaque voix reçoit la même place.", "Faire tourner les rôles dans les travaux de groupe, y compris les plus discrets."],
    subjects: ["Heure de classe", "Éducation physique", "Toutes les disciplines"],
    exercise: { title: "Écouter sans répondre", text: "À deux : une personne raconte deux minutes, l'autre écoute seulement – ni commentaire, ni conseil. Puis échanger. Comment était-ce ?" } },
  { id: "empathie-und-mitgefuehl", dim: "relating", name: "Empathie et compassion", icon: "empathie-und-mitgefuehl",
    desc: "Se relier aux autres, à soi-même et à la nature avec bienveillance, sollicitude et amour – avec le but et l'intention de réduire la souffrance.",
    teacher: ["Quel comportement dans ma classe m'agace – et quel besoin pourrait se cacher derrière ?", "Comment est-ce que je me traite moi-même quand une leçon échoue ?"],
    students: ["À quoi remarques-tu que quelqu'un ne va pas bien ?", "Qu'est-ce qui te fait du bien quand tu es triste – et cela pourrait-il aider d'autres ?"],
    ideas: ["Élargir le vocabulaire des émotions : décrire des images ou des scènes, rassembler des mots précis.", "Changement de perspective dans les conflits : chaque partie écrit ce que l'autre a probablement ressenti."],
    subjects: ["Français", "Éthique et vie en société", "Heure de classe", "Arts visuels"],
    exercise: { title: "Une pensée bienveillante", text: "Chacune et chacun pense à quelqu'un qui traverse une période difficile. Formuler en silence un bon souhait. Puis adresser le même souhait à soi-même." } },
  { id: "vergebung", dim: "relating", name: "Pardon", icon: "vergebung",
    desc: "La disposition à surmonter les hostilités, à traverser les traumatismes et à créer un espace pour la guérison.",
    teacher: ["À quel enfant est-ce que je m'adresse encore avec le conflit de la semaine passée en tête ?", "Comment est-ce que je montre qu'une affaire est close pour moi – et la classe le remarque-t-elle ?"],
    students: ["Que faut-il pour qu'une affaire soit vraiment close pour toi ?", "En veux-tu encore à quelqu'un ? Qu'est-ce qui rendrait cela plus léger ?"],
    ideas: ["Clore les conflits par une réparation plutôt que par une punition : de quoi la personne touchée a-t-elle besoin pour que cela redevienne juste ?", "Un rituel de nouveau départ : après une dispute, chaque partie dit ce qu'elle fera autrement la prochaine fois – personne n'a à s'excuser."],
    subjects: ["Éthique et vie en société", "Heure de classe", "Français"],
    exercise: { title: "Affaire close", text: "Chacune et chacun écrit une chose qui le préoccupe encore et décide pour soi : la garder ou la laisser partir. Les billets « laisser partir » sont ramassés sans être lus et jetés." } },

  { id: "beziehungen-aufbauen", dim: "collaborating", name: "Construire des relations", icon: "beziehungen-aufbauen",
    desc: "L'entretien de relations avec intelligence émotionnelle, fondées sur la confiance, le respect, la compréhension mutuelle et un esprit de coopération.",
    teacher: ["Avec quel enfant de ma classe n'ai-je presque aucune relation – et quand aurais-je deux minutes pour cela ?", "Où est-ce que je contrôle alors que je pourrais faire confiance ?"],
    students: ["À quoi remarques-tu que quelqu'un t'apprécie, même sans qu'il le dise ?", "Que faudrait-il pour que tu refasses confiance à quelqu'un ?"],
    ideas: ["La règle des deux minutes : pendant dix jours, deux minutes par jour avec l'enfant dont la relation est la plus ténue – sur tout sauf l'école.", "Confier des responsabilités : charges de classe, gestion du matériel, organisation de la récréation, sans contrôle."],
    subjects: ["Heure de classe", "Éducation physique", "Toutes les disciplines"],
    exercise: { title: "Guider à l'aveugle", text: "À deux : une personne ferme les yeux, l'autre la guide dans la salle uniquement à la voix. Échanger. Qu'est-ce qui a aidé ?" } },
  { id: "inklusive-denkweise", dim: "collaborating", name: "Mentalité inclusive et compétences interculturelles", icon: "inklusive-denkweise",
    desc: "Le désir et la capacité de reconnaître et de vivre la diversité, et d'inclure des personnes et des communautés aux perspectives et aux origines différentes.",
    teacher: ["Qui, dans ma classe, apparaît dans les exemples, les images et les textes – et qui n'y apparaît pas ?", "Quelle normalité est-ce que je présuppose sans m'en rendre compte ?"],
    students: ["Qu'est-ce qui est différent chez toi par rapport aux autres – et qu'est-ce que tu aimes là-dedans ?", "Quand t'es-tu déjà senti exclu ?"],
    ideas: ["Portrait linguistique : chacune et chacun dessine ses langues dans une silhouette et la présente.", "Intégrer au calendrier de l'année les fêtes et rituels présents dans la classe."],
    subjects: ["Langues étrangères", "Éthique et vie en société", "Histoire et géographie", "Musique"],
    exercise: { title: "Semblables et différents", text: "À deux, trouver en deux minutes trois points communs et trois différences. Lesquels ont surpris ?" } },
  { id: "gemeinsam-gestalten", dim: "collaborating", name: "Co-créer", icon: "gemeinsam-gestalten",
    desc: "Favoriser les processus de coopération avec différentes parties prenantes, encourager le travail d'équipe et la sécurité psychologique, et être conscient des rapports de pouvoir.",
    teacher: ["Sur quoi mes élèves peuvent-ils réellement décider – et sur quoi seulement en apparence ?", "Chacune et chacun se sent-il assez en sécurité pour exprimer une idée à moitié aboutie ?"],
    students: ["Qui parle le plus dans votre groupe – et qui décide à la fin ?", "De quoi as-tu besoin pour oser dire une idée inachevée ?"],
    ideas: ["Planifier ensemble un projet de classe, de l'idée à la réalisation – l'enseignant comme accompagnant.", "Rendre visible le temps de parole : pendant un travail de groupe, une personne note qui parle combien. Regarder le résultat ensemble."],
    subjects: ["Travail de projet", "Arts appliqués", "Heure de classe"],
    exercise: { title: "Construire ensemble", text: "Les groupes reçoivent dix feuilles de papier et construisent la tour la plus haute – sans parler. Ensuite : qui a contribué et comment ?" } },
  { id: "kommunizieren", dim: "collaborating", name: "Communiquer", icon: "kommunizieren",
    desc: "La capacité d'écouter attentivement, d'encourager un véritable dialogue, de défendre ses propres vues avec habileté, de gérer les conflits de manière constructive et d'adapter sa communication à différents groupes.",
    teacher: ["Combien de mes questions en classe sont de vraies questions dont j'ignore la réponse ?", "Comment est-ce que je parle autrement aux parents qu'aux élèves – et qu'y a-t-il d'utile là-dedans ?"],
    students: ["À quoi remarques-tu que quelqu'un t'écoute vraiment ?", "Comment dis-tu à quelqu'un que quelque chose te dérange, sans le blesser ?"],
    ideas: ["Élaborer ensemble des règles de discussion et les afficher.", "Un conseil de classe avec des rôles fixes : présidence, procès-verbal, temps, ambiance."],
    subjects: ["Français", "Langues étrangères", "Heure de classe"],
    exercise: { title: "Reformuler", text: "À deux : A raconte une minute. B résume : « J'ai compris que… » A corrige ou confirme. Échanger." } },
  { id: "mobilisieren", dim: "collaborating", name: "Mobiliser", icon: "mobilisieren",
    desc: "Inspirer les autres et leur donner les moyens de s'engager pour des objectifs communs et une action collective.",
    teacher: ["Qu'est-ce qui m'enthousiasme dans ma discipline – et ma classe voit-elle cet enthousiasme ?", "Comment est-ce que je gagne des collègues à une idée, plutôt que de les convaincre ?"],
    students: ["Pour quoi voudrais-tu enthousiasmer les autres ?", "Qui t'a déjà entraîné – comment cette personne s'y est-elle prise ?"],
    ideas: ["Les élèves planifient une action pour l'école (collecte, kiosque de récréation, exposition) et font campagne pour elle.", "Discours courts : convaincre pour une cause en 60 secondes."],
    subjects: ["Français", "Travail de projet", "Économie et vie pratique"],
    exercise: { title: "Le pitch d'une minute", text: "Chacune et chacun choisit une petite amélioration pour la classe. Une minute pour la défendre. La classe vote – et met en œuvre la gagnante." } },

  { id: "mut", dim: "acting", name: "Courage", icon: "mut",
    desc: "Défendre des valeurs fondamentales, prendre des décisions, passer à l'action et, si nécessaire, remettre en question et faire bouger des structures et des opinions établies.",
    teacher: ["Que changerais-je dans mon enseignement si je n'avais pas peur des critiques ?", "Quand ai-je pour la dernière fois exprimé un désaccord au sein de l'équipe ?"],
    students: ["Quand as-tu osé dire quelque chose alors que c'était difficile ?", "Quelle est la différence entre courageux et imprudent ?"],
    ideas: ["Rassembler des histoires de courage : les enfants racontent de petits moments courageux – pas des exploits.", "Exercer des scènes de courage civique en jeu de rôle : que dis-je quand quelqu'un se fait moquer ?"],
    subjects: ["Éthique et vie en société", "Français", "Théâtre", "Éducation physique"],
    exercise: { title: "Un petit courage", text: "Chacune et chacun réfléchit : quel serait aujourd'hui un petit pas courageux pour moi ? L'écrire, plier le papier. Demain : qui l'a fait ?" } },
  { id: "hoffnung-und-optimismus", dim: "acting", name: "Espoir et optimisme", icon: "hoffnung-und-optimismus",
    desc: "La conviction partagée qu'un avenir plus juste, plus inclusif et plus durable peut être créé, construit et maintenu.",
    teacher: ["Quel avenir est-ce que je transmets à ma classe – un avenir qu'on façonne, ou un avenir qu'on subit ?", "Qu'est-ce qui me donne de l'espoir dans mon métier ?"],
    students: ["Qu'est-ce qui s'est amélioré ces dernières années ?", "Que pourrions-nous réussir en tant que classe qu'une seule personne ne réussirait pas ?"],
    ideas: ["Bonnes nouvelles de la semaine : les élèves cherchent ce qui évolue positivement.", "Des histoires de solutions plutôt que de problèmes : qui a déjà résolu un problème semblable – et comment ?"],
    subjects: ["Médias et informatique", "Sciences humaines et naturelles", "Français"],
    exercise: { title: "Malgré tout", text: "Chacune et chacun nomme un souci en une phrase. Le voisin ou la voisine répond par une phrase commençant par « Malgré tout… »." } },
  { id: "bewusster-umgang-mit-ressourcen", dim: "acting", name: "Usage conscient des ressources", icon: "bewusster-umgang-mit-ressourcen",
    desc: "Agir en ayant conscience des ressources naturelles limitées de notre planète, en mettant l'accent sur la préservation, la régénération et la sobriété, afin d'éviter une consommation nuisible.",
    teacher: ["Qu'est-ce que je consomme dans mon enseignement sans y penser – papier, électricité, matériel ?", "Est-ce que je parle de durabilité, ou est-elle aussi visible dans la salle de classe ?"],
    students: ["Qu'est-ce qui finit à la poubelle chez toi en fin de journée – et où cela pourrait-il aller autrement ?", "De tout ce que tu possèdes, qu'est-ce dont tu as vraiment besoin ?"],
    ideas: ["Audit des déchets : pendant une semaine, rassembler ce qui est jeté en classe, puis trier et en déduire des règles.", "Réparer plutôt que remplacer : apporter des objets cassés de la maison et les réparer ensemble."],
    subjects: ["Sciences et technique", "Économie et vie pratique", "Arts appliqués", "Sciences humaines et naturelles"],
    exercise: { title: "Un objet, trois vies", text: "Choisir un objet de sa trousse. D'où vient-il, que devient-il une fois cassé ? À deux, raconter son histoire en deux minutes." } },
  { id: "proaktiv-handeln", dim: "acting", name: "Agir de manière proactive", icon: "proaktiv-handeln",
    desc: "Les défis mondiaux actuels exigent une action tournée vers l'avenir et responsable, fondée sur la solidarité et le respect de la dignité humaine et de la Terre vivante.",
    teacher: ["Où est-ce que j'attends que quelqu'un d'autre résolve un problème que je vois depuis longtemps ?", "Quelle responsabilité est-ce que je confie à ma classe – et laquelle est-ce que je lui retire ?"],
    students: ["Qu'est-ce qui te dérange à l'école au point que tu ferais quelque chose contre ?", "Que pourrais-tu faire dès demain sans que personne te le demande ?"],
    ideas: ["Reprendre une préoccupation réelle de l'école et l'accompagner jusqu'à la réalisation – avec une lettre à la direction, pas seulement une affiche.", "Attribuer durablement des responsabilités : chacune et chacun assume pour un trimestre une tâche qui sert la communauté."],
    subjects: ["Histoire et géographie", "Travail de projet", "Éthique et vie en société", "Économie et vie pratique"],
    exercise: { title: "De l'agacement à l'action", text: "Chacune et chacun nomme quelque chose qui l'agace. Le voisin ou la voisine répond par un premier pas possible dès aujourd'hui." } },
  { id: "resilienz", dim: "acting", name: "Résilience", icon: "resilienz",
    desc: "Aborder les adversités et les obstacles avec souplesse, engagement et endurance, même lorsque les progrès sont lents ou incertains.",
    teacher: ["Quel enfant est-ce que j'abandonne un peu intérieurement – et que faudrait-il pour rester présent ?", "Quel projet ai-je laissé tomber trop tôt – et lequel aurais-je dû adapter plus tôt ?"],
    students: ["Que sais-tu faire aujourd'hui que tu ne savais pas faire avant ? Comment l'as-tu appris ?", "Que fais-tu quand quelque chose échoue pour la troisième fois – continuer ou essayer autrement ?"],
    ideas: ["Rendre les progrès visibles : poser côte à côte des travaux de septembre et de juin.", "Un projet long sur un semestre avec des étapes intermédiaires – plantes, journal, entraînement d'une habileté."],
    subjects: ["Mathématiques", "Musique", "Éducation physique", "Sciences et technique"],
    exercise: { title: "Pas encore", text: "Rassembler des phrases avec « je n'y arrive pas » et y ajouter un mot à voix haute : « je n'y arrive pas encore ». Que change ce petit mot ?" } }
];

export default { ui, dimensions, skills };
