// Italiano. Contenuto: Inner Development Guide 2.0 (versione 7.2) — 25 competenze in
// cinque dimensioni. Lo strato del quadro di riferimento (nomi e sottotitoli delle
// dimensioni, introduzioni, nomi e descrizioni delle competenze) è ripreso alla lettera
// dall'edizione italiana ufficiale.
//
// Un intervento sulla fonte: l'apostrofo tipografico usato lì (U+02BC) è normalizzato
// nell'apostrofo dritto impiegato ovunque in questo file.
//
// Le domande di riflessione, le idee per la classe, i collegamenti con le discipline e
// i miniesercizi non fanno parte del quadro IDG: sono stati scritti per questa app e
// tradotti dal tedesco. Le discipline del piano di studi svizzero sono state
// generalizzate.
export const ui = {
  appName: "Inner Development Guide",
  appNameSub: "in classe",
  tagline: "25 competenze. Una carta alla volta.",
  intro: "L'Inner Development Guide 2.0 descrive le capacità interiori di cui abbiamo bisogno per dare forma al cambiamento. Queste carte le traducono nella tua giornata di scuola.",
  tabs: { stack: "Mazzo", dimensions: "Dimensioni", saved: "Salvate", settings: "Impostazioni" },
  language: "Lingua",
  cardDesign: "Aspetto delle carte",
  variantFarbe: "Carta a colori",
  variantPapier: "Carta di carta",
  flipDirection: "Girare",
  flipH: "Orizzontale",
  flipV: "Verticale",
  clearSaved: "Svuota le salvate",
  cleared: "Salvate svuotate",
  about: "Questa app avvicina l'Inner Development Guide agli insegnanti: 25 competenze, ciascuna con domande di riflessione per te e per la tua classe, oltre a idee per la lezione.",
  cardOfDay: "Carta del giorno",
  random: "Carta a caso",
  flipHint: "Tocca per girare",
  swipeHint: "Scorri a destra per salvare",
  savedToast: "Salvata",
  front: "Competenza",
  back: "Per la lezione",
  forMe: "Per me",
  forStudents: "Per la mia classe",
  ideas: "In classe",
  sheetSub: "Idee, collegamenti disciplinari e miniesercizio",
  subjects: "Collegamenti disciplinari",
  exercise: "Miniesercizio · 5 minuti",
  save: "Salva",
  saved: "Salvata",
  share: "Condividi",
  shared: "Copiato",
  next: "Successiva",
  prev: "Indietro",
  emptySaved: "Nessuna carta salvata finora.",
  emptySavedHint: "Tocca «Salva» quando una carta deve accompagnarti.",
  skillsCount: "competenze",
  ofCards: "di",
  attribution: "Questo lavoro si ispira all'Inner Development Guide. Maggiori informazioni su innerdevelopmentgoals.org",
  dimensionLabel: "Dimensione",
  allCards: "Tutte le carte",
  close: "Chiudi",
  level: "Dalla primaria alla secondaria di secondo grado",
  orderRandom: "Ordine casuale",
  orderGuide: "Ordine della guida",
  on: "Attivo",
  off: "Disattivo",
  tapNext: "Tocca per la domanda successiva",
  // Il tour introduttivo in quattro passi (IdgCards.jsx#tourSteps) — vedi il
  // commento in content/de.js. `ofCards` (sopra, "di") fornisce la parola di
  // collegamento per l'indicatore di passo «{n} di {tourSteps.length}».
  tourStep1Title: "Girare la carta",
  tourStep1Text: "Tocca la carta: la competenza davanti, domande di riflessione per te e per la tua classe dietro.",
  tourStep2Title: "Sfogliare il mazzo",
  tourStep2Text: "Scorri la carta a sinistra o a destra. I puntini in alto mostrano la tua posizione nel mazzo.",
  tourStep3Title: "Salvare le carte",
  tourStep3Text: "Il cerchio in alto a destra della carta si riempie e la aggiunge alle tue salvate.",
  tourStep4Title: "Tutto il resto nel menu",
  tourStep4Text: "Dietro gli anelli in alto a destra trovi le dimensioni, le salvate, l'ordine e le impostazioni.",
  tourSkip: "Salta",
  tourNext: "Avanti",
  tourDone: "Iniziamo"
};

export const dimensions = [
  { id: "being", num: 1, name: "Essere", subtitle: "Coltivare la nostra vita interiore", color: "#D4B88C",
    intro: "Coltivare una maggiore consapevolezza delle nostre esperienze personali e del loro rapporto dinamico con ciò che ci circonda, ci aiutano a vivere con più presenza, chiarezza di intenti e capacità di rispondere con lucidità alle situazioni complesse." },
  { id: "thinking", num: 2, name: "Pensare", subtitle: "Comprendere le complessità del mondo", color: "#E585A1",
    intro: "Alimentare i processi di apertura a punti di vista diversi e sviluppare la capacità di immaginare le conseguenze a lungo termine, ci aiutano a gestire la complessità e a prendere decisioni più sagge in un mondo interconnesso." },
  { id: "relating", num: 3, name: "Relazionarsi", subtitle: "Prendersi cura degli altri e del mondo", color: "#EF4136",
    intro: "Entrare in contatto con il pianeta vivente, le generazioni future e le comunità con gentilezza, compassione e senso di appartenenza condivisa, ci aiutano a creare un mondo più giusto, inclusivo e prospero." },
  { id: "collaborating", num: 4, name: "Collaborare", subtitle: "Creare fiducia e lavorare insieme", color: "#FF7E2A",
    intro: "Sviluppare relazioni di fiducia, riconoscendo la diversità di valori, competenze e prospettive, e creare spazi sicuri, consentono a tutti di contribuire a obiettivi comuni e raggiungere un impatto collettivo." },
  { id: "acting", num: 5, name: "Agire", subtitle: "Guidare e facilitare il cambiamento", color: "#661A30",
    intro: "Andare avanti con coraggio e ottimismo, collaborare con gli altri e agire con determinazione aiutano a trasformare le idee in cambiamenti concreti, anche nei momenti difficili." }
];

export const skills = [
  { id: "innerer-kompass", dim: "being", name: "Bussola Interiore", icon: "innerer-kompass",
    desc: "Un impegno profondo e autentico a vivere e agire secondo valori e scopi che contribuiscono al bene di tutti.",
    teacher: ["Quale valore ha guidato oggi le mie decisioni in classe – e dove me ne sono allontanato?", "Perché sono diventato insegnante? Quanto di questo si è sentito questa settimana?"],
    students: ["Che cosa conta per te al punto da difenderlo?", "Da che cosa capisci che qualcosa è giusto o sbagliato per te?"],
    ideas: ["Mappa dei valori: la classe raccoglie valori su cartoncini e li ordina insieme – che cosa ci unisce, in che cosa ci distinguiamo?", "Non dare le regole di classe già pronte, ma ricavarle dai valori condivisi."],
    subjects: ["Etica e convivenza", "Ora di classe", "Italiano"],
    exercise: { title: "La mia frase di oggi", text: "Ognuno scrive in una frase che cosa gli sta a cuore oggi. Leggerla ad alta voce è facoltativo. A fine giornata una verifica breve: era vero?" } },
  { id: "integritaet-und-authentizitaet", dim: "being", name: "Integrità e Autenticità", icon: "integritaet-und-authentizitaet",
    desc: "Un impegno sincero a vivere con onestà e a lasciarsi guidare da valori solidi, interiorizzati, espressi con coerenza attraverso le proprie azioni.",
    teacher: ["Quand'è stata l'ultima volta che ho ammesso davanti alla classe di non sapere qualcosa o di aver sbagliato?", "Dove dico cose che in fondo non penso davvero – e perché?"],
    students: ["Quando ti risulta difficile essere sincero?", "Che cosa significa per te essere te stesso?"],
    ideas: ["Rendere visibile la cultura dell'errore: una parete con «errori da cui abbiamo imparato».", "Discutere storie-dilemma: che cosa faresti se nessuno lo venisse a sapere?"],
    subjects: ["Etica e convivenza", "Italiano", "Ora di classe"],
    exercise: { title: "Una risposta sincera", text: "Alla domanda «come stai?» per una volta tutti rispondono davvero invece di dire «bene». Due minuti di silenzio, poi scambio a coppie." } },
  { id: "offenheit-und-lernbereitschaft", dim: "being", name: "Apertura mentale e attitudine all'apprendimento", icon: "offenheit-und-lernbereitschaft",
    desc: "Un atteggiamento curioso e flessibile, che si esprime nella disponibilità ad accogliere punti di vista diversi, ad aprirsi con autenticità, ad abbracciare il cambiamento e a crescere.",
    teacher: ["Che cosa ho imparato questa settimana dai miei allievi?", "Quale routine di lezione mantengo solo perché ho sempre fatto così?"],
    students: ["Quand'è stata l'ultima volta che hai cambiato idea? Che cosa ti ha convinto?", "Che cosa vorresti imparare, anche se nessuno te lo chiede?"],
    ideas: ["Scambio di ruoli: gli allievi insegnano all'insegnante qualcosa che sanno fare bene.", "Introdurre i cartoncini «non lo so ancora» come risposta ammessa in classe."],
    subjects: ["Tutte le discipline", "Ora di classe", "Lavoro per progetti"],
    exercise: { title: "Una domanda curiosa", text: "Ognuno annota una domanda a cui non sa rispondere. Le domande vanno alla parete: una viene scelta insieme e seguita durante la settimana." } },
  { id: "selbsterkenntnis", dim: "being", name: "Consapevolezza di sé", icon: "selbsterkenntnis",
    desc: "Capacità di entrare in contatto profondo con i propri pensieri, emozioni, desideri e comportamenti; mantenendo una visione realistica di sé e gestendo le proprie reazioni in modo equilibrato.",
    teacher: ["Quali situazioni in classe mi fanno perdere l'equilibrio – e che cosa c'è dietro?", "Come reagisco sotto stress, e quanto ne percepisce la mia classe?"],
    students: ["Da che cosa senti nel corpo che ti stai arrabbiando o innervosendo?", "In che cosa sei bravo – e come fai a saperlo?"],
    ideas: ["Un check delle emozioni a inizio lezione, con le carte del meteo o una scala da 1 a 5.", "Diario di apprendimento con una domanda settimanale: che cosa mi ha aiutato oggi, che cosa mi ha frenato?"],
    subjects: ["Ora di classe", "Scienze e società", "Educazione fisica"],
    exercise: { title: "Il mio meteo interiore", text: "Chiudere gli occhi, tre respiri. Che tempo fa dentro di me: sereno, nuvoloso, in tempesta? Chi vuole lo condivide con una parola." } },
  { id: "praesenz", dim: "being", name: "Presenza", icon: "praesenz",
    desc: "Capacità di essere pienamente presente nel qui e ora, accogliere la realtà così com'è e rispondere in modo significativo.",
    teacher: ["Quante volte durante la lezione sono già con la testa a quella dopo?", "Quando ho davvero ascoltato un allievo oggi – senza conoscere già la risposta?"],
    students: ["Quand'è stata l'ultima volta che eri così assorbito da perdere la cognizione del tempo?", "Che cosa senti proprio ora, se resti in silenzio per un minuto?"],
    ideas: ["Un minuto di silenzio come rituale fisso dopo la ricreazione.", "Osservazione attenta nella natura o davanti a un'opera: cinque minuti solo a guardare, poi descrivere."],
    subjects: ["Educazione fisica", "Arte e immagine", "Musica", "Scienze e società"],
    exercise: { title: "Cinque sensi", text: "Uno dopo l'altro: che cosa vedo, sento, percepisco, odoro, assaporo? Trenta secondi ciascuno, senza giudicare." } },

  { id: "kritisches-denken", dim: "thinking", name: "Pensiero Critico", icon: "kritisches-denken",
    desc: "Capacità di analizzare e mettere in discussione idee, informazioni e piani.",
    teacher: ["Quali convinzioni sulla mia classe non ho più verificato di recente?", "Dove ammetto il disaccordo in classe – e dove lo soffoco senza accorgermene?"],
    students: ["Come fai a sapere che è vero?", "A chi conviene che tu ci creda?"],
    ideas: ["Verifica delle notizie false: confrontare due notizie, esaminare le fonti, ricavarne criteri.", "Formato dibattito con scambio di parte: ogni posizione viene sostenuta una volta."],
    subjects: ["Media e informatica", "Italiano", "Storia e geografia", "Scienze e tecnologia"],
    exercise: { title: "Tre domande a un'affermazione", text: "Un'affermazione alla lavagna. In gruppi: da dove viene? Che cosa la smentisce? Che cosa dovremmo sapere per esserne sicuri?" } },
  { id: "perspektivische-faehigkeiten", dim: "thinking", name: "Capacità di Mettere in Prospettiva", icon: "perspektivische-faehigkeiten",
    desc: "Capacità di apprendere da prospettive diverse e di integrare gli spunti ricevuti in una riflessione profonda che guida l'azione.",
    teacher: ["Come appare la mia lezione dalla prospettiva del bambino più silenzioso?", "Quale storia mi racconto sulla mia classe – ed è ancora vera?"],
    students: ["Come suonerebbe questa storia se la raccontasse un altro personaggio?", "Che cosa potrebbe pensare qualcuno che vive in modo molto diverso da te?"],
    ideas: ["Raccontare di nuovo testi o fatti storici dal punto di vista di un personaggio secondario.", "Linea delle posizioni: collocarsi nell'aula rispetto a un'affermazione e parlare con qualcuno dall'altro capo."],
    subjects: ["Italiano", "Storia e geografia", "Lingue straniere", "Etica e convivenza"],
    exercise: { title: "Cambio di sedia", text: "Discutere un tema a coppie. Dopo due minuti scambiarsi di posto – e portare avanti la posizione dell'altro." } },
  { id: "systemisches-denken", dim: "thinking", name: "Pensiero Sistemico", icon: "systemisches-denken",
    desc: "Abilità a riconoscere la natura sistemica dei fenomeni e a gestire relazioni complesse tra elementi interdipendenti.",
    teacher: ["Quale problema della mia classe cerco di risolvere con una soluzione semplice, benché abbia molte cause?", "Quali legami esterni alla scuola entrano nella mia lezione?"],
    students: ["Che cosa succede, in tutto, quando succede una cosa sola?", "Quale schema riconosci qui – e dove lo hai già visto?"],
    ideas: ["Una rete di effetti al posto di un riassunto: un tema (rumore in classe, plastica) al centro, cause e conseguenze come frecce – disegnare i legami invece di elencarli.", "Gioco dei sistemi: tutti fanno parte di un ciclo e sperimentano come un cambiamento si trasmette. Poi cercare dove sta la leva."],
    subjects: ["Scienze e società", "Storia e geografia", "Economia e vita pratica", "Scienze e tecnologia"],
    exercise: { title: "E poi?", text: "Nominare un cambiamento (per esempio «non ci sono più i compiti»). Chiedere in cerchio: e poi? Cinque giri, finché le conseguenze sorprendono." } },
  { id: "langfristige-orientierung", dim: "thinking", name: "Orientamento e Visione al Futuro", icon: "langfristige-orientierung",
    desc: "Capacità di immaginare obiettivi di lungo periodo e mantenerne l'impegno, contribuendo al benessere collettivo e ambientale.",
    teacher: ["Che cosa dovrebbero portarsi ancora dietro i miei allievi fra vent'anni dalla mia lezione?", "Dove ottimizzo per la prossima verifica invece che per una comprensione duratura?"],
    students: ["Come dovrebbe essere il tuo quartiere fra 30 anni?", "Che cosa vorresti che si dicesse un giorno della tua generazione?"],
    ideas: ["Iniziare la lezione con «perché stiamo imparando questo?» e lasciare che la classe risponda alla fine – che cosa di questo dura oltre l'anno scolastico?", "Laboratorio del futuro: critica – visione – realizzazione, su un tema che riguarda la classe."],
    subjects: ["Storia e geografia", "Italiano", "Lavoro per progetti", "Orientamento professionale"],
    exercise: { title: "Viaggio nel tempo", text: "Chiudere gli occhi: siamo nel 2050. Che cosa è migliorato? Chi ci ha contribuito? Una frase a testa." } },
  { id: "kreativitaet", dim: "thinking", name: "Creatività", icon: "kreativitaet",
    desc: "Capacità di superare gli schemi abituali, immaginare nuove possibilità e trasformarle in idee innovative.",
    teacher: ["Quand'è stata l'ultima volta che i miei allievi hanno potuto fare qualcosa che ancora non esiste?", "Quale compito ho assegnato questa settimana in modo che ci fosse una sola risposta giusta – ed era necessario?"],
    students: ["Come si potrebbe risolvere in un modo completamente diverso?", "Che cosa inventeresti se tutto fosse possibile?"],
    ideas: ["Compiti aperti con più vie di soluzione – soprattutto in matematica.", "Esercizio di rovesciamento: un oggetto quotidiano riceve un nuovo scopo."],
    subjects: ["Arte e immagine", "Matematica", "Tecnologia e design", "Musica"],
    exercise: { title: "30 cerchi", text: "Un foglio con 30 cerchi vuoti. In tre minuti trasformarne il più possibile in qualcosa: palla, orologio, pizza. Quantità prima della qualità." } },

  { id: "wertschaetzung", dim: "relating", name: "Apprezzamento", icon: "wertschaetzung",
    desc: "Relazionarsi con gli esseri umani e il pianeta Terra con un profondo senso di gratitudine, stima positiva e gioia.",
    teacher: ["A chi della mia classe non ho ancora detto nulla di apprezzante questa settimana?", "Di che cosa sono grato nel mio mestiere – anche nei giorni difficili?"],
    students: ["Chi ti ha aiutato oggi senza che si notasse?", "Che cosa dai per scontato, anche se in realtà è speciale?"],
    ideas: ["Doccia calda: una persona siede al centro, tutti nominano qualcosa che apprezzano di lei.", "Una parete della gratitudine in aula, completata ogni settimana."],
    subjects: ["Ora di classe", "Etica e convivenza", "Italiano"],
    exercise: { title: "Tre cose belle", text: "Ognuno scrive tre cose che oggi sono andate bene, per quanto piccole. Condividerne una con il compagno di banco." } },
  { id: "verbundenheit", dim: "relating", name: "Connessione", icon: "verbundenheit",
    desc: "Sentire un senso di appartenenza a un tutto più grande, come l'umanità, la rete della vita del pianeta e le dimensioni spirituali dell'esistenza.",
    teacher: ["Ogni bambino della mia classe si sente parte del gruppo? Da che cosa lo capisco?", "Dove sento io stesso un legame – con i colleghi, la scuola, il luogo?"],
    students: ["A chi o a che cosa appartieni?", "Che cosa ti lega a un bambino di un altro continente?"],
    ideas: ["Risalire all'origine di un oggetto quotidiano: chi ha contribuito a farlo?", "Un gemellaggio di classe con una scuola di un altro paese o di un'altra regione."],
    subjects: ["Scienze e società", "Storia e geografia", "Lingue straniere"],
    exercise: { title: "La rete di lana", text: "In cerchio si lancia un gomitolo di lana. Chi lo prende dice qualcosa che ha in comune con chi glielo ha lanciato. Alla fine tutti reggono una rete." } },
  { id: "demut-und-bescheidenheit", dim: "relating", name: "Umiltà", icon: "demut-und-bescheidenheit",
    desc: "Capacità di rispondere in modo adeguato alle esigenze della situazione senza che la considerazione della propria importanza personale interferisca nel processo.",
    teacher: ["Quanto parlo io durante una lezione, e quanto parla la classe?", "Quand'è stata l'ultima volta che ho preferito l'idea di un allievo alla mia?"],
    students: ["Quando conta di più che il gruppo vada avanti piuttosto che avere ragione tu?", "Che cosa sanno fare gli altri meglio di te – e che effetto ti fa?"],
    ideas: ["Discussione silenziosa su carta: ogni voce riceve lo stesso spazio.", "Far ruotare i ruoli nei lavori di gruppo, anche quelli meno appariscenti."],
    subjects: ["Ora di classe", "Educazione fisica", "Tutte le discipline"],
    exercise: { title: "Ascoltare senza rispondere", text: "A coppie: una persona racconta per due minuti, l'altra ascolta soltanto – nessun commento, nessun consiglio. Poi si scambiano. Com'è stato?" } },
  { id: "empathie-und-mitgefuehl", dim: "relating", name: "Empatia e compassione", icon: "empathie-und-mitgefuehl",
    desc: "Connettersi agli altri, a se stessi e alla natura con gentilezza, cura e amore, guidati dall'intenzione di ridurre la sofferenza.",
    teacher: ["Quale comportamento della mia classe mi dà fastidio – e quale bisogno potrebbe esserci dietro?", "Come tratto me stesso quando una lezione va male?"],
    students: ["Da che cosa capisci che qualcuno non sta bene?", "Che cosa ti fa bene quando sei triste – e potrebbe aiutare anche altri?"],
    ideas: ["Ampliare il vocabolario delle emozioni: descrivere immagini o scene, raccogliere parole precise.", "Cambio di prospettiva nei conflitti: entrambe le parti scrivono che cosa avrà provato l'altra."],
    subjects: ["Italiano", "Etica e convivenza", "Ora di classe", "Arte e immagine"],
    exercise: { title: "Un pensiero gentile", text: "Tutti pensano a qualcuno che sta passando un momento difficile. Formulare in silenzio un buon augurio. Poi rivolgere lo stesso augurio a se stessi." } },
  { id: "vergebung", dim: "relating", name: "Perdono", icon: "vergebung",
    desc: "Disponibilità ad andare oltre l'ostilità, elaborare il trauma e generare uno spazio favorevole ai processi di guarigione.",
    teacher: ["A quale bambino mi rivolgo ancora con il conflitto della settimana scorsa in testa?", "Come mostro che per me una cosa è chiusa – e la classe se ne accorge?"],
    students: ["Che cosa deve succedere perché una cosa sia davvero chiusa per te?", "Porti rancore a qualcuno? Che cosa lo renderebbe più leggero?"],
    ideas: ["Chiudere i conflitti con una riparazione invece che con una punizione: di che cosa ha bisogno la persona coinvolta perché torni a andare bene?", "Un rito per ricominciare: dopo un litigio ogni parte dice che cosa farà diversamente la prossima volta – nessuno deve scusarsi."],
    subjects: ["Etica e convivenza", "Ora di classe", "Italiano"],
    exercise: { title: "Chiuso", text: "Ognuno scrive una cosa che lo occupa ancora e decide per sé: tenerla o lasciarla andare. I foglietti da lasciare andare vengono raccolti senza essere letti e buttati." } },

  { id: "beziehungen-aufbauen", dim: "collaborating", name: "Abilità nel costruire relazioni", icon: "beziehungen-aufbauen",
    desc: "Coltivare relazioni con intelligenza emotiva, fondate sulla fiducia, sul rispetto, sulla comprensione reciproca e su uno spirito di collaborazione.",
    teacher: ["Con quale bambino della mia classe non ho quasi nessuna relazione – e quando avrei due minuti per farlo?", "Dove controllo, benché potrei fidarmi?"],
    students: ["Da che cosa capisci che qualcuno ti vuole bene, anche se non lo dice?", "Che cosa dovrebbe succedere perché tu torni a fidarti di qualcuno?"],
    ideas: ["La regola dei due minuti: per dieci giorni, due minuti al giorno con il bambino con cui la relazione è più sottile – su tutto tranne la scuola.", "Consegnare responsabilità: incarichi di classe, gestione del materiale, organizzazione della ricreazione, senza controllo."],
    subjects: ["Ora di classe", "Educazione fisica", "Tutte le discipline"],
    exercise: { title: "Guidare alla cieca", text: "A coppie: una persona chiude gli occhi, l'altra la guida per l'aula con la sola voce. Poi si scambiano. Che cosa ha aiutato?" } },
  { id: "inklusive-denkweise", dim: "collaborating", name: "Mentalità inclusiva e competenza interculturale", icon: "inklusive-denkweise",
    desc: "Disponibilità e competenza nel cogliere il valore della diversità e nell'includere individui e comunità con differenti prospettive e percorsi di vita.",
    teacher: ["Chi della mia classe compare negli esempi, nelle immagini e nei testi – e chi no?", "Quale normalità do per scontata senza accorgermene?"],
    students: ["Che cosa è diverso a casa tua rispetto a quella degli altri – e che cosa ti piace di questo?", "Quando ti sei sentito escluso, qualche volta?"],
    ideas: ["Ritratto linguistico: ognuno disegna le proprie lingue in una sagoma del corpo e la presenta.", "Portare nel calendario dell'anno le feste e i riti presenti nella classe."],
    subjects: ["Lingue straniere", "Etica e convivenza", "Storia e geografia", "Musica"],
    exercise: { title: "Uguali e diversi", text: "A coppie, trovare in due minuti tre cose in comune e tre differenze. Quali hanno sorpreso?" } },
  { id: "gemeinsam-gestalten", dim: "collaborating", name: "Capacità di co-creazione", icon: "gemeinsam-gestalten",
    desc: "Facilitare processi collaborativi con gruppi diversi, promuovere il lavoro di squadra e un ambiente sicuro psicologicamente in cui esprimersi ed essere consapevoli delle dinamiche di potere.",
    teacher: ["Su che cosa possono decidere davvero i miei allievi – e su che cosa solo in apparenza?", "Si sentono tutti abbastanza sicuri da dire un'idea a metà?"],
    students: ["Chi parla di più nel vostro gruppo – e chi decide alla fine?", "Di che cosa hai bisogno per osare dire un'idea non finita?"],
    ideas: ["Progettare insieme un progetto di classe dall'idea alla realizzazione – l'insegnante come accompagnatore.", "Rendere visibile il tempo di parola: durante un lavoro di gruppo una persona segna chi parla quanto. Poi si guarda insieme."],
    subjects: ["Lavoro per progetti", "Tecnologia e design", "Ora di classe"],
    exercise: { title: "Costruire insieme", text: "I gruppi ricevono dieci fogli di carta e costruiscono la torre più alta – senza parlare. Dopo: chi ha contribuito e come?" } },
  { id: "kommunizieren", dim: "collaborating", name: "Capacità di comunicazione", icon: "kommunizieren",
    desc: "Capacità di ascoltare in profondità, favorire un dialogo autentico, argomentare le proprie posizioni con abilità, gestire i conflitti in modo costruttivo e adattare la comunicazione a gruppi diversi.",
    teacher: ["Quante delle mie domande in classe sono domande vere, di cui non conosco la risposta?", "Come parlo ai genitori in modo diverso che agli allievi – e che cosa di questo è utile?"],
    students: ["Da che cosa capisci che qualcuno ti ascolta davvero?", "Come dici a qualcuno che qualcosa ti disturba, senza ferirlo?"],
    ideas: ["Elaborare insieme le regole della conversazione e appenderle come cartellone.", "Consiglio di classe con ruoli fissi: conduzione, verbale, tempo, clima."],
    subjects: ["Italiano", "Lingue straniere", "Ora di classe"],
    exercise: { title: "Rispecchiare", text: "A coppie: A racconta per un minuto. B riassume: «Ho capito che…». A corregge o conferma. Poi si scambiano." } },
  { id: "mobilisieren", dim: "collaborating", name: "Capacità di mobilitazione", icon: "mobilisieren",
    desc: "Ispirare gli altri e metterli nelle condizioni di impegnarsi in obiettivi comuni e in azioni collettive.",
    teacher: ["Che cosa mi entusiasma della mia materia – e la mia classe vede questo entusiasmo?", "Come conquisto i colleghi a un'idea, invece di convincerli?"],
    students: ["Per che cosa vorresti entusiasmare gli altri?", "Chi ti ha già trascinato qualche volta – come ha fatto?"],
    ideas: ["Gli allievi progettano un'azione per la scuola (una raccolta, un chiosco della ricreazione, una mostra) e fanno campagna per essa.", "Discorsi brevi: conquistare consenso per una causa in 60 secondi."],
    subjects: ["Italiano", "Lavoro per progetti", "Economia e vita pratica"],
    exercise: { title: "Il discorso di un minuto", text: "Ognuno sceglie un piccolo miglioramento per la classe. Un minuto per sostenerlo. La classe vota – e realizza il vincitore." } },

  { id: "mut", dim: "acting", name: "Coraggio", icon: "mut",
    desc: "Difendere i valori fondamentali, decidere e agire, mettendo in discussione le strutture e le visioni consolidate quando necessario.",
    teacher: ["Che cosa cambierei nella mia lezione se non avessi paura delle critiche?", "Quand'è stata l'ultima volta che ho espresso disaccordo tra colleghi?"],
    students: ["Quando hai avuto il coraggio di dire qualcosa, anche se era difficile?", "Qual è la differenza fra coraggioso e avventato?"],
    ideas: ["Raccogliere storie di coraggio: i bambini raccontano piccoli momenti coraggiosi – non imprese eroiche.", "Provare scene di coraggio civile nel gioco di ruolo: che cosa dico quando qualcuno viene deriso?"],
    subjects: ["Etica e convivenza", "Italiano", "Teatro", "Educazione fisica"],
    exercise: { title: "Un piccolo coraggio", text: "Ognuno riflette: quale sarebbe oggi un piccolo passo coraggioso per me? Scriverlo, piegare il foglio. Domani: chi l'ha fatto?" } },
  { id: "hoffnung-und-optimismus", dim: "acting", name: "Speranza e Ottimismo", icon: "hoffnung-und-optimismus",
    desc: "Creare e mantenere fiducia nella nostra capacità di costruire insieme un futuro più giusto, inclusivo e sostenibile.",
    teacher: ["Quale futuro trasmetto alla mia classe – uno che si può dare forma o uno che si deve sopportare?", "Che cosa mi dà speranza nel mio mestiere?"],
    students: ["Che cosa è migliorato negli ultimi anni?", "Che cosa potremmo riuscire a fare come classe che una persona da sola non riesce?"],
    ideas: ["Le buone notizie della settimana: gli allievi cercano che cosa si sta sviluppando in modo positivo.", "Storie di soluzioni invece che storie di problemi: chi ha già risolto un problema simile – e come?"],
    subjects: ["Media e informatica", "Scienze e società", "Italiano"],
    exercise: { title: "Eppure", text: "Ognuno nomina una preoccupazione in una frase. Il compagno di banco risponde con una frase che inizia con «Eppure…»." } },
  { id: "bewusster-umgang-mit-ressourcen", dim: "acting", name: "Uso Consapevole delle Risorse", icon: "bewusster-umgang-mit-ressourcen",
    desc: "Agire con consapevolezza verso l'ambiente, evitando sprechi e consumi dannosi, e dando priorità alla conservazione, al recupero e alla protezione delle risorse naturali.",
    teacher: ["Che cosa consumo nella mia lezione senza pensarci: carta, elettricità, materiale?", "Parlo di sostenibilità, o si vede anche in aula?"],
    students: ["Che cosa finisce nel tuo cestino a fine giornata – e dove potrebbe andare invece?", "Di tutto quello che possiedi, che cosa ti serve davvero?"],
    ideas: ["Audit dei rifiuti: per una settimana raccogliere ciò che viene buttato in aula, poi separarlo e ricavarne delle regole.", "Riparare invece di sostituire: portare da casa cose rotte e aggiustarle insieme."],
    subjects: ["Scienze e tecnologia", "Economia e vita pratica", "Tecnologia e design", "Scienze e società"],
    exercise: { title: "Un oggetto, tre vite", text: "Scegliere un oggetto dall'astuccio. Da dove è venuto, che cosa ne sarà quando si rompe? A coppie, raccontarne la storia in due minuti." } },
  { id: "proaktiv-handeln", dim: "acting", name: "Proattività", icon: "proaktiv-handeln",
    desc: "Affrontare le sfide del nostro tempo con responsabilità e orientamento al futuro, basandosi su principi di solidarietà, cura della dignità umana e della Terra vivente.",
    teacher: ["Dove aspetto che qualcun altro risolva un problema che vedo da tempo?", "Quale responsabilità affido alla mia classe – e quale le tolgo?"],
    students: ["Che cosa ti dà fastidio della scuola al punto da farci qualcosa?", "Che cosa potresti fare già domani, senza che nessuno te lo chieda?"],
    ideas: ["Riprendere una questione reale della scuola e accompagnarla fino alla realizzazione – con una lettera alla direzione, non solo con un cartellone.", "Assegnare responsabilità in modo stabile: ognuno si prende per un trimestre un compito che serve alla comunità."],
    subjects: ["Storia e geografia", "Lavoro per progetti", "Etica e convivenza", "Economia e vita pratica"],
    exercise: { title: "Dal fastidio all'azione", text: "Ognuno nomina qualcosa che lo infastidisce. Il compagno di banco risponde con un primo passo possibile già oggi." } },
  { id: "resilienz", dim: "acting", name: "Resilienza", icon: "resilienz",
    desc: "Reagire alle avversità con perseveranza, anche quando i progressi sono lenti o incerti.",
    teacher: ["Su quale bambino sto un po' rinunciando dentro di me – e che cosa servirebbe per restarci?", "Quale proposito ho lasciato cadere troppo presto – e quale avrei dovuto adattare prima?"],
    students: ["Che cosa sai fare oggi che prima non sapevi fare? Come l'hai imparato?", "Che cosa fai quando qualcosa non riesce per la terza volta: continui o provi in un altro modo?"],
    ideas: ["Rendere visibili i progressi: mettere uno accanto all'altro lavori di settembre e di giugno.", "Un progetto lungo su un semestre con tappe intermedie: piante, un diario, esercitare un'abilità."],
    subjects: ["Matematica", "Musica", "Educazione fisica", "Scienze e tecnologia"],
    exercise: { title: "Non ancora", text: "Raccogliere frasi con «non ne sono capace» e aggiungere ad alta voce una parola: «non ne sono ancora capace». Che cosa cambia quella parolina?" } }
];

export default { ui, dimensions, skills };
