// Svenska. Innehåll: Inner Development Guide 2.0 (version 7.2) – 25 förmågor i fem
// dimensioner. Ramverksskiktet (dimensionernas namn och underrubriker, inledningar,
// förmågornas namn och beskrivningar) är ordagrant hämtat ur den officiella svenska
// utgåvan.
//
// En ändring i källan: tankstrecket efter «Inkluderande hållning och interkulturell
// kompetens –» är borttaget, det hörde till sidans layout och inte till namnet.
//
// Reflektionsfrågorna, klassrumsidéerna, ämneskopplingarna och miniövningarna ingår
// inte i IDG-ramverket – de skrevs för den här appen och är översatta från tyskan.
// De schweiziska läroplansämnena har generaliserats.
export const ui = {
  appName: "Inner Development Guide",
  appNameSub: "i skolvardagen",
  tagline: "25 förmågor. Ett kort i taget.",
  intro: "Inner Development Guide 2.0 beskriver inre förmågor som vi behöver för att kunna forma förändring. De här korten översätter dem till din skolvardag.",
  tabs: { stack: "Kortlek", dimensions: "Dimensioner", saved: "Sparade", settings: "Inställningar" },
  language: "Språk",
  cardDesign: "Kortens utseende",
  variantFarbe: "Färgkort",
  variantPapier: "Papperskort",
  flipDirection: "Vänd",
  flipH: "Vågrätt",
  flipV: "Lodrätt",
  clearSaved: "Töm sparade",
  cleared: "Sparade tömda",
  about: "Den här appen gör Inner Development Guide tillgängligt för lärare: 25 förmågor, var och en med reflektionsfrågor för dig och för din klass samt idéer för undervisningen.",
  cardOfDay: "Dagens kort",
  random: "Slumpkort",
  flipHint: "Tryck för att vända",
  swipeHint: "Svep åt höger för att spara",
  savedToast: "Sparat",
  front: "Förmåga",
  back: "För undervisningen",
  forMe: "För mig",
  forStudents: "För min klass",
  ideas: "I undervisningen",
  sheetSub: "Idéer, ämneskopplingar och en miniövning",
  subjects: "Ämneskopplingar",
  exercise: "Miniövning · 5 minuter",
  save: "Spara",
  saved: "Sparat",
  share: "Dela",
  shared: "Kopierat",
  next: "Nästa",
  prev: "Tillbaka",
  emptySaved: "Inga kort sparade ännu.",
  emptySavedHint: "Tryck på ”Spara” när ett kort ska följa med dig.",
  skillsCount: "förmågor",
  ofCards: "av",
  attribution: "Det här arbetet är inspirerat av Inner Development Guide. Mer på innerdevelopmentgoals.org",
  dimensionLabel: "Dimension",
  allCards: "Alla kort",
  close: "Stäng",
  level: "Grundskola till gymnasium",
  orderRandom: "Slumpmässig ordning",
  orderGuide: "Ordning enligt guiden",
  on: "På",
  off: "Av",
  tapNext: "Tryck för nästa fråga"
};

export const dimensions = [
  { id: "being", num: 1, name: "Vara", subtitle: "Odla vårt inre liv", color: "#D4B88C",
    intro: "Att fördjupa vår medvetenhet om inre upplevelser och deras dynamiska relation till världen runt oss främjar förkroppsligad närvaro, tydlighet i syfte och eftertänksam respons när vi möter komplexitet." },
  { id: "thinking", num: 2, name: "Tänka", subtitle: "Förstå vår komplexa värld", color: "#E585A1",
    intro: "Att öka klarheten, beakta olika perspektiv och föreställa sig långsiktiga konsekvenser hjälper oss att navigera i komplexitet och fatta klokare beslut i vår sammankopplade värld." },
  { id: "relating", num: 3, name: "Relatera", subtitle: "Omsorg om andra och världen", color: "#EF4136",
    intro: "Att knyta an till gemenskaper, vår levande planet och framtida generationer med vänlighet, medkänsla och tillhörighet hjälper oss att skapa en mer rättvis, inkluderande och blomstrande värld." },
  { id: "collaborating", num: 4, name: "Samarbeta", subtitle: "Bygga tillit och arbeta tillsammans", color: "#FF7E2A",
    intro: "Att utveckla tillitsfulla relationer, erkänna olika värderingar, förmågor och perspektiv samt skapa trygga rum gör det möjligt för alla att bidra till gemensamma syften och kollektiv påverkan." },
  { id: "acting", num: 5, name: "Agera", subtitle: "Leda och möjliggöra förändring", color: "#661A30",
    intro: "Att gå framåt med mod och optimism, bygga kollektiv handlingskraft och agera med syfte och uthållighet förvandlar visioner till meningsfull förändring i osäkra tider." }
];

export const skills = [
  { id: "innerer-kompass", dim: "being", name: "Inre kompass", icon: "innerer-kompass",
    desc: "Ett djupt känt engagemang att leva och agera i enlighet med värderingar och syften som tjänar helheten bäst.",
    teacher: ["Vilket värde styrde mina beslut i klassrummet i dag – och var avvek jag från det?", "Varför blev jag lärare? Hur mycket av det märktes den här veckan?"],
    students: ["Vad är så viktigt för dig att du skulle stå upp för det?", "Hur märker du att något känns rätt eller fel för dig?"],
    ideas: ["Värdekarta: klassen samlar värden på kort och ordnar dem tillsammans – vad förenar oss, var skiljer vi oss?", "Ge inte klassreglerna färdiga, utan härled dem ur de gemensamma värdena."],
    subjects: ["Etik och samhälle", "Klassens tid", "Svenska"],
    exercise: { title: "Min mening för i dag", text: "Alla skriver i en mening vad som är viktigt för dem i dag. Att läsa upp är frivilligt. I slutet av dagen: stämde det?" } },
  { id: "integritaet-und-authentizitaet", dim: "being", name: "Integritet och äkthet", icon: "integritaet-und-authentizitaet",
    desc: "Ett uppriktigt engagemang för ärlighet och fast förankrade värderingar, uttryckt och förkroppsligat i handling.",
    teacher: ["När erkände jag senast inför klassen att jag inte visste något eller hade gjort fel?", "Var säger jag saker som jag inte riktigt menar – och varför?"],
    students: ["När är det svårt för dig att vara ärlig?", "Vad betyder det för dig att vara dig själv?"],
    ideas: ["Gör felkulturen synlig: en vägg med ”misstag vi har lärt oss av”.", "Diskutera dilemmaberättelser: vad skulle du göra om ingen fick veta det?"],
    subjects: ["Etik och samhälle", "Svenska", "Klassens tid"],
    exercise: { title: "Ett ärligt svar", text: "På frågan ”hur mår du?” svarar alla för en gångs skull ärligt i stället för ”bra”. Två minuters tystnad, sedan samtal två och två." } },
  { id: "offenheit-und-lernbereitschaft", dim: "being", name: "Öppenhet och ett lärande förhållningssätt", icon: "offenheit-und-lernbereitschaft",
    desc: "En nyfiken, anpassningsbar hållning uttryckt genom viljan att utbyta perspektiv, vara sårbar, välkomna förändring och växa.",
    teacher: ["Vad har jag lärt mig av mina elever den här veckan?", "Vilken undervisningsrutin behåller jag bara för att jag alltid har gjort så?"],
    students: ["När ändrade du senast åsikt? Vad övertygade dig?", "Vad skulle du vilja lära dig även om ingen bad dig om det?"],
    ideas: ["Rollbyte: eleverna undervisar läraren i något de är bra på.", "Inför ”jag vet inte än”-kort som ett tillåtet svar i klassrummet."],
    subjects: ["Alla ämnen", "Klassens tid", "Projektarbete"],
    exercise: { title: "En nyfiken fråga", text: "Var och en skriver ned en fråga de inte har svar på. Frågorna sätts upp på väggen – en väljs gemensamt och följs under veckan." } },
  { id: "selbsterkenntnis", dim: "being", name: "Självmedvetenhet", icon: "selbsterkenntnis",
    desc: "Förmågan att vara i reflekterande kontakt med tankar, känslor, önskningar och handlingar; att upprätthålla en realistisk självbild och reglera sig själv.",
    teacher: ["Vilka situationer i klassrummet får mig ur balans – och vad ligger bakom det?", "Hur reagerar jag under stress, och hur mycket av det uppfattar klassen?"],
    students: ["Hur märker du i kroppen att du blir arg eller nervös?", "Vad är du bra på – och hur vet du det?"],
    ideas: ["Känslocheck i början av lektionen med väderkort eller en skala från 1 till 5.", "Lärlogg med en veckofråga: vad hjälpte mig i dag, vad bromsade mig?"],
    subjects: ["Klassens tid", "Naturkunskap och samhälle", "Idrott och hälsa"],
    exercise: { title: "Inre väder", text: "Slut ögonen, tre andetag. Hur är mitt väder just nu – soligt, molnigt, stormigt? Den som vill delar det med ett ord." } },
  { id: "praesenz", dim: "being", name: "Närvaro", icon: "praesenz",
    desc: "Förmågan att vara fullt närvarande här och nu, att acceptera verkligheten som den utvecklas och att svara på meningsfulla sätt.",
    teacher: ["Hur ofta är jag under lektionen redan i tankarna hos nästa?", "När lyssnade jag i dag verkligen på en elev – utan att redan veta svaret?"],
    students: ["När var du senast så uppslukad att du glömde tiden?", "Vad hör du just nu om du är alldeles tyst i en minut?"],
    ideas: ["En tyst minut som fast rutin efter rasten.", "Uppmärksamt betraktande i naturen eller framför ett konstverk: fem minuter av bara tittande, sedan beskrivning."],
    subjects: ["Idrott och hälsa", "Bild", "Musik", "Naturkunskap och samhälle"],
    exercise: { title: "Fem sinnen", text: "Ett i taget: vad ser jag, hör jag, känner jag, luktar jag, smakar jag? Trettio sekunder var, utan att värdera." } },

  { id: "kritisches-denken", dim: "thinking", name: "Kritiskt tänkande", icon: "kritisches-denken",
    desc: "Förmågan att reflektera över giltigheten i idéer, bevis, antaganden och planer.",
    teacher: ["Vilka antaganden om min klass har jag inte prövat på sistone?", "Var tillåter jag invändningar i klassrummet – och var kväver jag dem omedvetet?"],
    students: ["Hur vet du att det stämmer?", "Vem tjänar på att du tror det?"],
    ideas: ["Faktakoll: jämför två nyheter, granska källorna, ta fram kriterier.", "Debattformat med sidbyte – varje ståndpunkt företräds en gång."],
    subjects: ["Medier och IT", "Svenska", "Historia och geografi", "Naturvetenskap och teknik"],
    exercise: { title: "Tre frågor till ett påstående", text: "Ett påstående på tavlan. I grupper: varifrån kommer det? Vad talar emot? Vad skulle vi behöva veta för att vara säkra?" } },
  { id: "perspektivische-faehigkeiten", dim: "thinking", name: "Perspektivförmågor", icon: "perspektivische-faehigkeiten",
    desc: "Förmågor att lära av olika perspektiv och integrera insikter i reflekterande meningsskapande och handling.",
    teacher: ["Hur ser min lektion ut ur det tystaste barnets perspektiv?", "Vilken berättelse berättar jag för mig själv om min klass – och stämmer den fortfarande?"],
    students: ["Hur skulle den här berättelsen låta om en annan figur berättade den?", "Vad kan någon tänka som lever helt annorlunda än du?"],
    ideas: ["Återberätta texter eller historiska händelser ur en birolls perspektiv.", "Ståndpunktslinje: placera sig i rummet utifrån ett påstående och samtala med någon i andra änden."],
    subjects: ["Svenska", "Historia och geografi", "Moderna språk", "Etik och samhälle"],
    exercise: { title: "Stolsbyte", text: "Diskutera ett ämne två och två. Efter två minuter: byt plats – och för den andres ståndpunkt vidare." } },
  { id: "systemisches-denken", dim: "thinking", name: "Systemtänkande", icon: "systemisches-denken",
    desc: "Förmågan att förstå komplexitet och arbeta med systemens samband och egenskaper.",
    teacher: ["Vilket problem i klassen försöker jag lösa med en enkel lösning trots att det har många orsaker?", "Vilka samband utanför skolan verkar in i min undervisning?"],
    students: ["Vad allt händer när en sak händer?", "Vilket mönster känner du igen här – och var har du sett det förut?"],
    ideas: ["Ett verkansnät i stället för en sammanfattning: ett tema (klassrumsljud, plast) i mitten, orsaker och följder som pilar – rita sambanden i stället för att räkna upp dem.", "Systemlek: alla är del av ett kretslopp och får uppleva hur en förändring förs vidare. Leta sedan efter var hävstången finns."],
    subjects: ["Naturkunskap och samhälle", "Historia och geografi", "Hem- och konsumentkunskap", "Naturvetenskap och teknik"],
    exercise: { title: "Och sedan?", text: "Nämn en förändring (t.ex. ”det finns inga läxor längre”). Fråga runt i ringen: och sedan? Fem varv, tills följderna överraskar." } },
  { id: "langfristige-orientierung", dim: "thinking", name: "Långsiktig orientering och vision", icon: "langfristige-orientierung",
    desc: "Förmågan att föreställa sig långsiktiga mål och hålla fast vid dem på sätt som stödjer ett bredare samhälleligt och ekologiskt välbefinnande.",
    teacher: ["Vad ska mina elever fortfarande bära med sig från min undervisning om tjugo år?", "Var optimerar jag för nästa prov i stället för för långsiktig förståelse?"],
    students: ["Hur ska ditt kvarter se ut om 30 år?", "Vad vill du att människor senare säger om din generation?"],
    ideas: ["Inled lektionen med ”varför lär vi oss det här?” och låt klassen svara på det i slutet – vad av det bär längre än läsåret?", "Framtidsverkstad: kritik – vision – genomförande, kring ett tema som berör klassen."],
    subjects: ["Historia och geografi", "Svenska", "Projektarbete", "Studie- och yrkesvägledning"],
    exercise: { title: "Tidsresa", text: "Slut ögonen: det är år 2050. Vad har blivit bättre? Vem bidrog till det? En mening per person." } },
  { id: "kreativitaet", dim: "thinking", name: "Kreativitet", icon: "kreativitaet",
    desc: "Förmågan att tänka utanför konventionella mönster, föreställa sig nya möjligheter och forma dem till transformativa idéer.",
    teacher: ["När fick mina elever senast göra något som inte finns än?", "Vilken uppgift ställde jag den här veckan så att bara ett svar är rätt – behövde det vara så?"],
    students: ["Hur skulle man kunna lösa det här helt annorlunda?", "Vad skulle du uppfinna om allt vore möjligt?"],
    ideas: ["Öppna uppgifter med flera lösningsvägar – särskilt i matematiken.", "Omvändningsövning: ett vardagsföremål får ett nytt syfte."],
    subjects: ["Bild", "Matematik", "Slöjd", "Musik"],
    exercise: { title: "30 cirklar", text: "Ett blad med 30 tomma cirklar. Gör på tre minuter så många som möjligt till något – boll, klocka, pizza. Kvantitet före kvalitet." } },

  { id: "wertschaetzung", dim: "relating", name: "Uppskattning", icon: "wertschaetzung",
    desc: "Att relatera till människor och planeten Jorden med en djup känsla av tacksamhet, positiv uppskattning och glädje.",
    teacher: ["Vem i min klass har jag ännu inte sagt något uppskattande till den här veckan?", "Vad är jag tacksam för i mitt yrke – också på svåra dagar?"],
    students: ["Vem hjälpte dig i dag utan att det märktes?", "Vad tar du för givet som egentligen är särskilt?"],
    ideas: ["Varm dusch: en person sitter i mitten, alla nämner något de uppskattar hos hen.", "En tacksamhetsvägg i klassrummet som fylls på varje vecka."],
    subjects: ["Klassens tid", "Etik och samhälle", "Svenska"],
    exercise: { title: "Tre bra saker", text: "Var och en skriver ned tre saker som var bra i dag – hur små de än är. Dela en av dem med bänkgrannen." } },
  { id: "verbundenheit", dim: "relating", name: "Samhörighet", icon: "verbundenheit",
    desc: "Att känna en känsla av tillhörighet till en större helhet, såsom mänskligheten, planetens livsväv och existensens andliga dimensioner.",
    teacher: ["Känner sig varje barn i min klass som en del av gruppen? Hur märker jag det?", "Var känner jag själv samhörighet – med kollegiet, skolan, orten?"],
    students: ["Vem eller vad hör du till?", "Vad förbinder dig med ett barn på en annan kontinent?"],
    ideas: ["Spåra ett vardagsföremåls ursprung: vilka har alla medverkat till det?", "Klassvänskap med en skola i ett annat land eller en annan region."],
    subjects: ["Naturkunskap och samhälle", "Historia och geografi", "Moderna språk"],
    exercise: { title: "Garnnätet", text: "I ring: ett garnnystan kastas. Den som fångar nämner något hen har gemensamt med den som kastade. Till slut håller alla i ett nät." } },
  { id: "demut-und-bescheidenheit", dim: "relating", name: "Ödmjukhet", icon: "demut-und-bescheidenheit",
    desc: "Förmågan att svara på situationens behov utan att fästa vikt vid sin egen betydelse.",
    teacher: ["Hur mycket talar jag under en lektion, hur mycket talar klassen?", "När valde jag senast en elevs idé framför min egen?"],
    students: ["När är det viktigare att gruppen kommer vidare än att du har rätt?", "Vad kan andra bättre än du – och hur känns det?"],
    ideas: ["Tyst diskussion på papper: varje röst får lika mycket plats.", "Låt rollerna i grupparbeten rotera, också de obemärkta."],
    subjects: ["Klassens tid", "Idrott och hälsa", "Alla ämnen"],
    exercise: { title: "Lyssna utan att svara", text: "Två och två: en person berättar i två minuter, den andra bara lyssnar – ingen kommentar, inga råd. Byt sedan. Hur var det?" } },
  { id: "empathie-und-mitgefuehl", dim: "relating", name: "Empati och medkänsla", icon: "empathie-und-mitgefuehl",
    desc: "Att knyta an till andra, sig själv och naturen med vänlighet, omtanke och kärlek, vägledd av avsikten att minska lidande.",
    teacher: ["Vilket beteende i min klass irriterar mig – och vilket behov kan ligga bakom?", "Hur behandlar jag mig själv när en lektion misslyckas?"],
    students: ["Hur märker du att någon inte mår bra?", "Vad hjälper dig när du är ledsen – och skulle det kunna hjälpa andra också?"],
    ideas: ["Vidga känsloordförrådet: beskriv bilder eller scener, samla precisa ord.", "Perspektivbyte i konflikter: båda sidor skriver ned vad den andra troligen kände."],
    subjects: ["Svenska", "Etik och samhälle", "Klassens tid", "Bild"],
    exercise: { title: "En vänlig tanke", text: "Alla tänker på någon som har det svårt just nu. Formulera i tysthet en god önskan. Rikta sedan samma önskan till dig själv." } },
  { id: "vergebung", dim: "relating", name: "Förlåtelse", icon: "vergebung",
    desc: "Viljan att överskrida fientlighet, bearbeta trauma och skapa utrymme för läkning.",
    teacher: ["Vilket barn möter jag fortfarande med förra veckans konflikt i bakhuvudet?", "Hur visar jag att en sak är avslutad för mig – och märker klassen det?"],
    students: ["Vad måste hända för att en sak ska vara verkligt avslutad för dig?", "Bär du agg till någon? Vad skulle göra det lättare?"],
    ideas: ["Avsluta konflikter med gottgörelse i stället för straff: vad behöver den drabbade för att det ska kännas rätt igen?", "En rutin för nystart: efter ett gräl säger varje sida vad hen gör annorlunda nästa gång – ingen måste be om ursäkt."],
    subjects: ["Etik och samhälle", "Klassens tid", "Svenska"],
    exercise: { title: "Avslutat", text: "Alla skriver ned en sak som fortfarande tynger dem och avgör själva: behålla eller släppa. Släpp-lapparna samlas in olästa och slängs." } },

  { id: "beziehungen-aufbauen", dim: "collaborating", name: "Relationsbyggandeförmågor", icon: "beziehungen-aufbauen",
    desc: "Att vårda relationer med emotionell intelligens grundad i tillit, respekt, ömsesidig förståelse och en anda av samarbete.",
    teacher: ["Vilket barn i min klass har jag knappt någon relation till – och när skulle jag ha två minuter för det?", "Var kontrollerar jag fastän jag skulle kunna lita på?"],
    students: ["Hur märker du att någon tycker om dig, även utan att hen säger det?", "Vad skulle behöva hända för att du skulle lita på någon igen?"],
    ideas: ["Tvåminutersregeln: i tio dagar, två minuter om dagen med det barn relationen är tunnast till – om allt utom skolan.", "Lämna över ansvar: klassuppdrag, materialvård, rastorganisation utan kontroll."],
    subjects: ["Klassens tid", "Idrott och hälsa", "Alla ämnen"],
    exercise: { title: "Leda blint", text: "Två och två: en person blundar, den andra leder hen genom rummet enbart med rösten. Byt. Vad hjälpte?" } },
  { id: "inklusive-denkweise", dim: "collaborating", name: "Inkluderande hållning och interkulturell kompetens", icon: "inklusive-denkweise",
    desc: "Vilja och kompetens att omfamna mångfald och inkludera människor och grupper med olika perspektiv och bakgrunder.",
    teacher: ["Vem i min klass förekommer i exempel, bilder och texter – och vem gör det inte?", "Vilken normalitet förutsätter jag omedvetet?"],
    students: ["Vad är annorlunda hemma hos dig än hos andra – och vad tycker du om med det?", "När har du känt dig utanför någon gång?"],
    ideas: ["Språkporträtt: alla ritar in sina språk i en kroppssiluett och presenterar den.", "Ta in klassens högtider och ritualer i årskalendern."],
    subjects: ["Moderna språk", "Etik och samhälle", "Historia och geografi", "Musik"],
    exercise: { title: "Lika och olika", text: "Två och två: hitta på två minuter tre likheter och tre olikheter. Vilka var överraskande?" } },
  { id: "gemeinsam-gestalten", dim: "collaborating", name: "Samskapandeförmågor", icon: "gemeinsam-gestalten",
    desc: "Att underlätta samarbetsprocesser med olika aktörer, främja lagarbete och psykologisk trygghet samt vara medveten om maktdynamik.",
    teacher: ["Vad får mina elever faktiskt vara med och bestämma om – och vad bara skenbart?", "Känner sig alla trygga nog att säga en halvfärdig idé?"],
    students: ["Vem talar mest i er grupp – och vem bestämmer till slut?", "Vad behöver du för att våga säga en ofärdig idé?"],
    ideas: ["Planera ett klassprojekt tillsammans från idé till genomförande – läraren som coach.", "Gör taltiden synlig: under ett grupparbete räknar en person vem som talar hur mycket. Titta på det tillsammans efteråt."],
    subjects: ["Projektarbete", "Slöjd", "Klassens tid"],
    exercise: { title: "Bygga tillsammans", text: "Grupperna får tio pappersark och bygger det högsta tornet – utan att prata. Efteråt: vem bidrog med vad?" } },
  { id: "kommunizieren", dim: "collaborating", name: "Kommunikationsförmågor", icon: "kommunizieren",
    desc: "Förmågor att lyssna djupt, främja genuin dialog, framföra sina åsikter skickligt, hantera konflikter konstruktivt och anpassa kommunikationen till olika grupper.",
    teacher: ["Hur många av mina frågor i klassrummet är äkta frågor vars svar jag inte känner?", "Hur talar jag annorlunda med föräldrar än med elever – och vad av det är till hjälp?"],
    students: ["Hur märker du att någon verkligen lyssnar på dig?", "Hur säger du till någon att något stör dig, utan att såra?"],
    ideas: ["Ta fram samtalsregler tillsammans och sätt upp dem som affisch.", "Klassråd med fasta roller: ordförande, protokoll, tid, stämning."],
    subjects: ["Svenska", "Moderna språk", "Klassens tid"],
    exercise: { title: "Spegla", text: "Två och två: A berättar i en minut. B sammanfattar: ”Jag förstod att…” A rättar eller bekräftar. Byt." } },
  { id: "mobilisieren", dim: "collaborating", name: "Mobiliseringsförmågor", icon: "mobilisieren",
    desc: "Att inspirera och möjliggöra för andra att engagera sig i gemensamma syften och kollektiv handling.",
    teacher: ["Vad entusiasmerar mig i mitt ämne – och ser klassen den entusiasmen?", "Hur vinner jag kollegor för en idé i stället för att övertala dem?"],
    students: ["Vad skulle du vilja entusiasmera andra för?", "Vem har ryckt med dig någon gång – hur gjorde hen?"],
    ideas: ["Eleverna planerar en aktion för skolan (insamling, rastkiosk, utställning) och kampanjar för den.", "Korta tal: vinn stöd för en sak på 60 sekunder."],
    subjects: ["Svenska", "Projektarbete", "Hem- och konsumentkunskap"],
    exercise: { title: "Enminuterspitch", text: "Alla väljer en liten förbättring för klassen. En minut att kampanja för den. Klassen röstar – och genomför vinnaren." } },

  { id: "mut", dim: "acting", name: "Mod", icon: "mut",
    desc: "Att stå upp för grundläggande värderingar, fatta beslut, vidta åtgärder och, när det behövs, ifrågasätta och bryta upp etablerade strukturer och synsätt.",
    teacher: ["Vad skulle jag ändra i min undervisning om jag inte var rädd för kritik?", "När invände jag senast i kollegiet?"],
    students: ["När vågade du säga något trots att det var svårt?", "Vad är skillnaden mellan modig och dumdristig?"],
    ideas: ["Samla modshistorier: barnen berättar om små modiga ögonblick – inte hjältedåd.", "Öva civilkuragescener i rollspel: vad säger jag när någon blir utskrattad?"],
    subjects: ["Etik och samhälle", "Svenska", "Drama", "Idrott och hälsa"],
    exercise: { title: "Ett litet mod", text: "Alla funderar: vad vore i dag ett litet modigt steg för mig? Skriv ned det, vik ihop lappen. I morgon: vem gjorde det?" } },
  { id: "hoffnung-und-optimismus", dim: "acting", name: "Hopp och optimism", icon: "hoffnung-und-optimismus",
    desc: "Att utveckla och upprätthålla en gemensam tro på vår förmåga att skapa en mer rättvis, inkluderande och hållbar framtid.",
    teacher: ["Vilken framtid förmedlar jag till min klass – en som går att forma, eller en som man måste stå ut med?", "Vad ger mig hopp i mitt yrke?"],
    students: ["Vad har blivit bättre de senaste åren?", "Vad skulle vi kunna klara som klass som en person ensam inte klarar?"],
    ideas: ["Veckans goda nyheter: eleverna undersöker vad som utvecklas positivt.", "Lösningsberättelser i stället för problemberättelser: vem har redan löst ett liknande problem – och hur?"],
    subjects: ["Medier och IT", "Naturkunskap och samhälle", "Svenska"],
    exercise: { title: "Ändå", text: "Var och en nämner en oro i en mening. Bänkgrannen svarar med en mening som börjar med ”Ändå…”." } },
  { id: "bewusster-umgang-mit-ressourcen", dim: "acting", name: "Medvetet resursanvändande", icon: "bewusster-umgang-mit-ressourcen",
    desc: "Att agera medvetet om planetens begränsade naturresurser, prioritera bevarande, återanvändning, förnyelse och sparsamhet för att undvika skadlig konsumtion.",
    teacher: ["Vad förbrukar jag i min undervisning utan att tänka på det – papper, el, material?", "Talar jag om hållbarhet, eller syns den också i klassrummet?"],
    students: ["Vad hamnar i papperskorgen hos dig i slutet av dagen – och var skulle det annars kunna hamna?", "Av allt du äger: vad behöver du verkligen?"],
    ideas: ["Avfallsgranskning: samla under en vecka det som slängs i klassrummet, sortera det sedan och härled regler ur det.", "Laga i stället för att ersätta: ta med trasiga saker hemifrån och laga dem tillsammans."],
    subjects: ["Naturvetenskap och teknik", "Hem- och konsumentkunskap", "Slöjd", "Naturkunskap och samhälle"],
    exercise: { title: "Ett föremål, tre liv", text: "Välj ett föremål ur pennfacket. Varifrån kom det, vad händer med det när det går sönder? Berätta dess historia två och två på två minuter." } },
  { id: "proaktiv-handeln", dim: "acting", name: "Proaktivitet", icon: "proaktiv-handeln",
    desc: "Att utöva framtidsinriktat, ansvarsfullt förvaltarskap inför akuta utmaningar, grundat på solidaritet och omsorg om människans värdighet och vårt levande jordklot.",
    teacher: ["Var väntar jag på att någon annan ska lösa ett problem som jag sedan länge ser?", "Vilket ansvar anförtror jag min klass – och vilket tar jag ifrån den?"],
    students: ["Vad stör dig i skolan så mycket att du skulle göra något åt det?", "Vad skulle du kunna göra redan i morgon utan att någon ber dig om det?"],
    ideas: ["Ta upp ett verkligt ärende från skolhuset och följ det ända fram till genomförande – med brev till rektorn, inte bara med affisch.", "Fördela ansvar på riktigt: var och en tar under en termin på sig en uppgift som tjänar gemenskapen."],
    subjects: ["Historia och geografi", "Projektarbete", "Etik och samhälle", "Hem- och konsumentkunskap"],
    exercise: { title: "Från irritation till handling", text: "Var och en nämner något som irriterar hen. Bänkgrannen svarar med ett första steg som vore möjligt redan i dag." } },
  { id: "resilienz", dim: "acting", name: "Resiliens", icon: "resilienz",
    desc: "Att hantera motgångar med smidighet och fortsätta vara engagerad och uthållig även när framstegen är långsamma eller osäkra.",
    teacher: ["Vilket barn börjar jag i tysthet ge upp om – och vad skulle krävas för att hålla ut?", "Vilken föresats släppte jag för tidigt – och vilken borde jag ha ändrat tidigare?"],
    students: ["Vad kan du i dag som du inte kunde förr? Hur lärde du dig det?", "Vad gör du när något misslyckas för tredje gången – fortsätter eller provar annorlunda?"],
    ideas: ["Gör lärandet synligt: lägg arbeten från september och juni bredvid varandra.", "Ett långtidsprojekt över en termin med delmål – växter, dagbok, öva en färdighet."],
    subjects: ["Matematik", "Musik", "Idrott och hälsa", "Naturvetenskap och teknik"],
    exercise: { title: "Inte än", text: "Samla meningar med ”jag kan inte det” och lägg högt till ett ord: ”jag kan inte det än”. Vad ändrar det lilla ordet?" } }
];

export default { ui, dimensions, skills };
