// Svenska. Ramverksskiktet (dimensioner, förmågornas namn och beskrivningar)
// är hämtat ordagrant ur ”IDG Framework (Swedish).pdf”.
//
// Reflektionsfrågorna, klassrumsidéerna, ämneskopplingarna och
// miniövningarna ingår inte i IDG-ramverket – de skrevs för den här appen och
// är översatta från tyskan. De schweiziska läroplansämnena har generaliserats.
export const ui = {
  appName: "IDG i skolvardagen",
  tagline: "23 förmågor. Ett kort i taget.",
  intro: "Inner Development Goals beskriver inre förmågor som vi behöver för att kunna forma förändring. De här korten översätter dem till din skolvardag.",
  tabs: { stack: "Kortlek", dimensions: "Dimensioner", saved: "Sparade", settings: "Inställningar" },
  language: "Språk",
  cardDesign: "Kortens utseende",
  variantFarbe: "Färgkort",
  variantPapier: "Papperskort",
  flipDirection: "Vänd",
  flipH: "Vågrätt",
  flipV: "Lodrätt",
  clearSaved: "Töm sparade",
  cleared: "Sparade tömda",
  about: "Den här appen gör Inner Development Goals tillgängliga för lärare: 23 förmågor, var och en med reflektionsfrågor för dig och för din klass samt idéer för undervisningen.",
  cardOfDay: "Dagens kort",
  random: "Slumpkort",
  flipHint: "Tryck för att vända",
  swipeHint: "Svep åt höger för att spara",
  savedToast: "Sparat",
  front: "Förmåga",
  back: "För undervisningen",
  forMe: "För mig",
  forStudents: "För min klass",
  ideas: "I undervisningen",
  sheetSub: "Idéer, ämneskopplingar och en miniövning",
  subjects: "Ämneskopplingar",
  exercise: "Miniövning · 5 minuter",
  save: "Spara",
  saved: "Sparat",
  share: "Dela",
  shared: "Kopierat",
  next: "Nästa",
  prev: "Tillbaka",
  emptySaved: "Inga kort sparade ännu.",
  emptySavedHint: "Tryck på ”Spara” när ett kort ska följa med dig.",
  skillsCount: "förmågor",
  ofCards: "av",
  attribution: "Det här arbetet är inspirerat av Inner Development Goals. Mer på innerdevelopmentgoals.org",
  dimensionLabel: "Dimension",
  allCards: "Alla kort",
  close: "Stäng",
  level: "Grundskola till gymnasium",
  orderRandom: "Slumpmässig ordning",
  orderGuide: "Ordning enligt guiden",
  on: "På",
  off: "Av",
  tapNext: "Tryck för nästa fråga"
};

export const dimensions = [
  { id: "being", num: 1, name: "Vara", subtitle: "Relationen till sig själv", color: "#D4B88C",
    intro: "Att kultivera vårt inre liv samt utveckla och fördjupa relationen till våra tankar, känslor och kropp hjälper oss att vara närvarande, intentionella och icke-reaktiva när vi möter komplexitet." },
  { id: "thinking", num: 2, name: "Tänka", subtitle: "Kognitiva förmågor", color: "#E585A1",
    intro: "Att utveckla våra kognitiva förmågor genom att pröva olika perspektiv, utvärdera information samt skapa förståelse för världen som en sammankopplad helhet är grundläggande för klokt beslutsfattande." },
  { id: "relating", num: 3, name: "Relatera", subtitle: "Att bry sig om andra och omvärlden", color: "#EF4136",
    intro: "Att känna uppskattning, omtanke för och gemenskap med andra, såsom grannar, framtida generationer eller biosfären, hjälper oss att skapa mer rättvisa och hållbara system och samhällen för alla." },
  { id: "collaborating", num: 4, name: "Samarbeta", subtitle: "Sociala förmågor", color: "#FF7E2A",
    intro: "För att göra framsteg kring delade utmaningar behöver vi utveckla förmåga att inkludera, skapa utrymme för samt kommunicera med intressenter med skilda värderingar, förmågor och kompetenser." },
  { id: "acting", num: 5, name: "Agera", subtitle: "Att driva förändring", color: "#661A30",
    intro: "Egenskaper såsom mod och optimism hjälper oss att agera ur vårt fulla agentskap, bryta gamla mönster, generera nya idéer samt agera med uthållighet i osäkra tider." }
];

export const skills = [
  { id: "b1", dim: "being", name: "Inre kompass", icon: "b1-innerer-kompass",
    desc: "Att ha en djupt förankrad känsla av ansvar för och engagemang kring värden och mål i relation till vad helheten behöver.",
    teacher: ["Vilket värde styrde mina beslut i klassrummet i dag – och var avvek jag från det?", "Varför blev jag lärare? Hur mycket av det märktes den här veckan?"],
    students: ["Vad är så viktigt för dig att du skulle stå upp för det?", "Hur märker du att något känns rätt eller fel för dig?"],
    ideas: ["Värdekarta: klassen samlar värden på kort och ordnar dem tillsammans – vad förenar oss, var skiljer vi oss?", "Ge inte klassreglerna färdiga, utan härled dem ur de gemensamma värdena."],
    subjects: ["Etik och samhälle", "Klassens tid", "Svenska"],
    exercise: { title: "Min mening för i dag", text: "Alla skriver i en mening vad som är viktigt för dem i dag. Att läsa upp är frivilligt. I slutet av dagen: stämde det?" } },
  { id: "b2", dim: "being", name: "Integritet och autenticitet", icon: "b2-integritaet-und-authentizitaet",
    desc: "Ett engagemang kring och förmåga till att vara uppriktig, ärlig och agera med integritet.",
    teacher: ["När erkände jag senast inför klassen att jag inte visste något eller hade gjort fel?", "Var säger jag saker som jag inte riktigt menar – och varför?"],
    students: ["När är det svårt för dig att vara ärlig?", "Vad betyder det för dig att vara dig själv?"],
    ideas: ["Gör felkulturen synlig: en vägg med ”misstag vi har lärt oss av”.", "Diskutera dilemmaberättelser: vad skulle du göra om ingen fick veta det?"],
    subjects: ["Etik och samhälle", "Svenska", "Klassens tid"],
    exercise: { title: "Ett ärligt svar", text: "På frågan ”hur mår du?” svarar alla för en gångs skull ärligt i stället för ”bra”. Två minuters tystnad, sedan samtal två och två." } },
  { id: "b3", dim: "being", name: "Öppenhet och lärande", icon: "b3-offenheit-und-lernbereitschaft",
    desc: "Att ha en grundläggande inställning av nyfikenhet och en villighet att vara sårbar, omfamna förändring och att vilja utvecklas.",
    teacher: ["Vad har jag lärt mig av mina elever den här veckan?", "Vilken undervisningsrutin behåller jag bara för att jag alltid har gjort så?"],
    students: ["När ändrade du senast åsikt? Vad övertygade dig?", "Vad skulle du vilja lära dig även om ingen bad dig om det?"],
    ideas: ["Rollbyte: eleverna undervisar läraren i något de är bra på.", "Inför ”jag vet inte än”-kort som ett tillåtet svar i klassrummet."],
    subjects: ["Alla ämnen", "Klassens tid", "Projektarbete"],
    exercise: { title: "En nyfiken fråga", text: "Var och en skriver ned en fråga de inte har svar på. Frågorna sätts upp på väggen – en väljs gemensamt och följs under veckan." } },
  { id: "b4", dim: "being", name: "Självmedvetenhet", icon: "b4-selbsterkenntnis",
    desc: "Förmåga att vara i reflekterande kontakt med egna tankar, känslor och önskemål; att ha en realistisk självbild och förmåga att reglera sig själv.",
    teacher: ["Vilka situationer i klassrummet får mig ur balans – och vad ligger bakom det?", "Hur reagerar jag under stress, och hur mycket av det uppfattar klassen?"],
    students: ["Hur märker du i kroppen att du blir arg eller nervös?", "Vad är du bra på – och hur vet du det?"],
    ideas: ["Känslocheck i början av lektionen med väderkort eller en skala från 1 till 5.", "Lärlogg med en veckofråga: vad hjälpte mig i dag, vad bromsade mig?"],
    subjects: ["Klassens tid", "Naturkunskap och samhälle", "Idrott och hälsa"],
    exercise: { title: "Inre väder", text: "Slut ögonen, tre andetag. Hur är mitt väder just nu – soligt, molnigt, stormigt? Den som vill delar det med ett ord." } },
  { id: "b5", dim: "being", name: "Närvaro", icon: "b5-gegenwaertigkeit",
    desc: "Förmåga att vara här och nu, utan dömande och i ett tillstånd av utforskande och närvaro.",
    teacher: ["Hur ofta är jag under lektionen redan i tankarna hos nästa?", "När lyssnade jag i dag verkligen på en elev – utan att redan veta svaret?"],
    students: ["När var du senast så uppslukad att du glömde tiden?", "Vad hör du just nu om du är alldeles tyst i en minut?"],
    ideas: ["En tyst minut som fast rutin efter rasten.", "Uppmärksamt betraktande i naturen eller framför ett konstverk: fem minuter av bara tittande, sedan beskrivning."],
    subjects: ["Idrott och hälsa", "Bild", "Musik", "Naturkunskap och samhälle"],
    exercise: { title: "Fem sinnen", text: "Ett i taget: vad ser jag, hör jag, känner jag, luktar jag, smakar jag? Trettio sekunder var, utan att värdera." } },

  { id: "t1", dim: "thinking", name: "Kritiskt tänkande", icon: "t1-kritisches-denken",
    desc: "Förmåga att kritiskt granska åsikters, evidens och planers validitet.",
    teacher: ["Vilka antaganden om min klass har jag inte prövat på sistone?", "Var tillåter jag invändningar i klassrummet – och var kväver jag dem omedvetet?"],
    students: ["Hur vet du att det stämmer?", "Vem tjänar på att du tror det?"],
    ideas: ["Faktakoll: jämför två nyheter, granska källorna, ta fram kriterier.", "Debattformat med sidbyte – varje ståndpunkt företräds en gång."],
    subjects: ["Medier och IT", "Svenska", "Historia och geografi", "Naturvetenskap och teknik"],
    exercise: { title: "Tre frågor till ett påstående", text: "Ett påstående på tavlan. I grupper: varifrån kommer det? Vad talar emot? Vad skulle vi behöva veta för att vara säkra?" } },
  { id: "t2", dim: "thinking", name: "Komplexitetsmedvetenhet", icon: "t2-bewusstsein-fuer-komplexitaet",
    desc: "Förståelse för samt förmåga att arbeta med komplexa och systemiska förhållanden och orsakssamband.",
    teacher: ["Vilket problem i klassen försöker jag lösa med en enkel lösning trots att det har många orsaker?", "Vilka samband utanför skolan verkar in i min undervisning?"],
    students: ["Vad allt händer när en sak händer?", "Var leder en liten orsak till en stor verkan?"],
    ideas: ["Rita ett verkansnät: ett tema (klassrumsljud, plast) i mitten, orsaker och följder som pilar.", "Systemlek: alla är del av ett kretslopp och får uppleva hur en förändring förs vidare."],
    subjects: ["Naturkunskap och samhälle", "Historia och geografi", "Hem- och konsumentkunskap"],
    exercise: { title: "Och sedan?", text: "Nämn en förändring (t.ex. ”det finns inga läxor längre”). Fråga runt i ringen: och sedan? Fem varv, tills följderna överraskar." } },
  { id: "t3", dim: "thinking", name: "Perspektivförmågor", icon: "t3-perspektivische-faehigkeiten",
    desc: "Förmåga att söka upp, förstå samt aktivt använda insikter från vitt skilda perspektiv.",
    teacher: ["Hur ser min lektion ut ur det tystaste barnets perspektiv?", "Vems synsätt saknas i mitt undervisningsmaterial?"],
    students: ["Hur skulle den här berättelsen låta om en annan figur berättade den?", "Vad kan någon tänka som lever helt annorlunda än du?"],
    ideas: ["Återberätta texter eller historiska händelser ur en biroll's perspektiv.", "Ståndpunktslinje: placera sig i rummet utifrån ett påstående och samtala med någon i andra änden."],
    subjects: ["Svenska", "Historia och geografi", "Moderna språk", "Etik och samhälle"],
    exercise: { title: "Stolsbyte", text: "Diskutera ett ämne två och två. Efter två minuter: byt plats – och för den andres ståndpunkt vidare." } },
  { id: "t4", dim: "thinking", name: "Meningsskapande", icon: "t4-sinnstiftung",
    desc: "Förmåga att se mönster, strukturera det okända samt medvetet skapa mening och narrativ.",
    teacher: ["Vilken berättelse berättar jag för mig själv om min klass – och stämmer den fortfarande?", "Förstår mina elever varför vi lär oss det vi lär oss?"],
    students: ["Vad har det vi lärde oss i dag med ditt liv att göra?", "Vilket mönster känner du igen här?"],
    ideas: ["Inled lektionen med frågan ”varför lär vi oss det här?” och låt klassen svara på den i slutet.", "Tankekartor i stället för sammanfattningar: gör sambanden synliga."],
    subjects: ["Alla ämnen", "Svenska", "Matematik"],
    exercise: { title: "Den röda tråden", text: "Tre begrepp från förra veckan på tavlan. Två och två: vilken berättelse förbinder dem? Kortaste versionen vinner." } },
  { id: "t5", dim: "thinking", name: "Långsiktig orientering och visionerande", icon: "t5-langfristige-orientierung",
    desc: "Långsiktig orientering samt förmåga att formulera och upprätthålla engagemang kring visioner i relation till ett större sammanhang.",
    teacher: ["Vad ska mina elever fortfarande bära med sig från min undervisning om tjugo år?", "Var optimerar jag för nästa prov i stället för för långsiktig förståelse?"],
    students: ["Hur ska ditt kvarter se ut om 30 år?", "Vad vill du att människor senare säger om din generation?"],
    ideas: ["Skriv ett brev till dig själv om tio år och förvara det i skolan.", "Framtidsverkstad: kritik – vision – genomförande, kring ett tema som berör klassen."],
    subjects: ["Historia och geografi", "Svenska", "Projektarbete", "Studie- och yrkesvägledning"],
    exercise: { title: "Tidsresa", text: "Slut ögonen: det är år 2050. Vad har blivit bättre? Vem bidrog till det? En mening per person." } },

  { id: "r1", dim: "relating", name: "Uppskattning", icon: "r1-wertschaetzung",
    desc: "Att relatera till andra och till omvärlden med en grundläggande känsla av uppskattning, tacksamhet och glädje.",
    teacher: ["Vem i min klass har jag ännu inte sagt något uppskattande till den här veckan?", "Vad är jag tacksam för i mitt yrke – också på svåra dagar?"],
    students: ["Vem hjälpte dig i dag utan att det märktes?", "Vad tar du för givet som egentligen är särskilt?"],
    ideas: ["Varm dusch: en person sitter i mitten, alla nämner något de uppskattar hos hen.", "En tacksamhetsvägg i klassrummet som fylls på varje vecka."],
    subjects: ["Klassens tid", "Etik och samhälle", "Svenska"],
    exercise: { title: "Tre bra saker", text: "Var och en skriver ned tre saker som var bra i dag – hur små de än är. Dela en av dem med bänkgrannen." } },
  { id: "r2", dim: "relating", name: "Samhörighet", icon: "r2-verbundenheit",
    desc: "Att ha en djupt rotad känsla av samhörighet med andra och/eller att vara del av en större helhet, såsom samhället, mänskligheten eller det globala ekosystemet.",
    teacher: ["Känner sig varje barn i min klass som en del av gruppen? Hur märker jag det?", "Var känner jag själv samhörighet – med kollegiet, skolan, orten?"],
    students: ["Vem eller vad hör du till?", "Vad förbinder dig med ett barn på en annan kontinent?"],
    ideas: ["Spåra ett vardagsföremåls ursprung: vilka har alla medverkat till det?", "Klassvänskap med en skola i ett annat land eller en annan region."],
    subjects: ["Naturkunskap och samhälle", "Historia och geografi", "Moderna språk"],
    exercise: { title: "Garnnätet", text: "I ring: ett garnnystan kastas. Den som fångar nämner något hen har gemensamt med den som kastade. Till slut håller alla i ett nät." } },
  { id: "r3", dim: "relating", name: "Ödmjukhet", icon: "r3-bescheidenheit",
    desc: "Förmåga att agera i enlighet med vad en situation kräver utan att vara upptagen med ens egen betydelse.",
    teacher: ["Hur mycket talar jag under en lektion, hur mycket talar klassen?", "När valde jag senast en elevs idé framför min egen?"],
    students: ["När är det viktigare att gruppen kommer vidare än att du har rätt?", "Vad kan andra bättre än du – och hur känns det?"],
    ideas: ["Tyst diskussion på papper: varje röst får lika mycket plats.", "Låt rollerna i grupparbeten rotera, också de obemärkta."],
    subjects: ["Klassens tid", "Idrott och hälsa", "Alla ämnen"],
    exercise: { title: "Lyssna utan att svara", text: "Två och två: en person berättar i två minuter, den andra bara lyssnar – ingen kommentar, inga råd. Byt sedan. Hur var det?" } },
  { id: "r4", dim: "relating", name: "Empati och medkänsla", icon: "r4-einfuehlungsvermoegen-und-mitgefuehl",
    desc: "Förmåga att relatera till andra, sig själv samt naturen med vänlighet, empati och medkänsla samt att verka för att lindra lidande.",
    teacher: ["Vilket beteende i min klass irriterar mig – och vilket behov kan ligga bakom?", "Hur behandlar jag mig själv när en lektion misslyckas?"],
    students: ["Hur märker du att någon inte mår bra?", "Vad hjälper dig när du är ledsen – och skulle det kunna hjälpa andra också?"],
    ideas: ["Vidga känsloordförrådet: beskriv bilder eller scener, samla precisa ord.", "Perspektivbyte i konflikter: båda sidor skriver ned vad den andra troligen kände."],
    subjects: ["Svenska", "Etik och samhälle", "Klassens tid", "Bild"],
    exercise: { title: "En vänlig tanke", text: "Alla tänker på någon som har det svårt just nu. Formulera i tysthet en god önskan. Rikta sedan samma önskan till dig själv." } },

  { id: "c1", dim: "collaborating", name: "Kommunikationsfärdigheter", icon: "c1-kommunikationsfaehigkeiten",
    desc: "Förmåga att verkligen lyssna på andra, att främja genuin dialog, att framföra egna åsikter på konstruktiva sätt, att konstruktivt hantera konflikter samt att anpassa kommunikationen efter olika grupper.",
    teacher: ["Hur många av mina frågor i klassrummet är äkta frågor vars svar jag inte känner?", "Hur talar jag annorlunda med föräldrar än med elever – och vad av det är till hjälp?"],
    students: ["Hur märker du att någon verkligen lyssnar på dig?", "Hur säger du till någon att något stör dig, utan att såra?"],
    ideas: ["Ta fram samtalsregler tillsammans och sätt upp dem som affisch.", "Klassråd med fasta roller: ordförande, protokoll, tid, stämning."],
    subjects: ["Svenska", "Moderna språk", "Klassens tid"],
    exercise: { title: "Spegla", text: "Två och två: A berättar i en minut. B sammanfattar: ”Jag förstod att…” A rättar eller bekräftar. Byt." } },
  { id: "c2", dim: "collaborating", name: "Samskapande", icon: "c2-mitgestaltungsfaehigkeiten",
    desc: "Förmåga och motivation att med olika intressenter bygga, utveckla och facilitera samskapande relationer, karakteriserade av psykologisk trygghet och genuin samarbetsvillighet.",
    teacher: ["Vad får mina elever faktiskt vara med och bestämma om – och vad bara skenbart?", "Känner sig alla trygga nog att säga en halvfärdig idé?"],
    students: ["När kändes ett grupparbete verkligen bra? Vad var annorlunda?", "Vad behöver du för att våga säga en ofärdig idé?"],
    ideas: ["Planera ett klassprojekt tillsammans från idé till genomförande – läraren som coach.", "”Ja, och…”-regeln vid idésamlingar: bygg först, värdera sedan."],
    subjects: ["Projektarbete", "Slöjd", "Klassens tid"],
    exercise: { title: "Bygga tillsammans", text: "Grupperna får tio pappersark och bygger det högsta tornet – utan att prata. Efteråt: vem bidrog med vad?" } },
  { id: "c3", dim: "collaborating", name: "Inkluderande hållning och interkulturell kompetens", icon: "c3-inklusive-denkweise",
    desc: "Villighet och kompetens att omfamna mångfald samt inkludera personer och kollektiv av skilda åsikter och bakgrunder.",
    teacher: ["Vem i min klass förekommer i exempel, bilder och texter – och vem gör det inte?", "Vilken normalitet förutsätter jag omedvetet?"],
    students: ["Vad är annorlunda hemma hos dig än hos andra – och vad tycker du om med det?", "När har du känt dig utanför någon gång?"],
    ideas: ["Språkporträtt: alla ritar in sina språk i en kroppssiluett och presenterar den.", "Ta in klassens högtider och ritualer i årskalendern."],
    subjects: ["Moderna språk", "Etik och samhälle", "Historia och geografi", "Musik"],
    exercise: { title: "Lika och olika", text: "Två och två: hitta på två minuter tre likheter och tre olikheter. Vilka var överraskande?" } },
  { id: "c4", dim: "collaborating", name: "Tillit", icon: "c4-vertrauen",
    desc: "Förmåga att visa tillit samt skapa och upprätthålla tillitsfulla relationer.",
    teacher: ["Var kontrollerar jag fastän jag skulle kunna lita på?", "Vad gör jag för att mina elever ska lita på mig – också efter en konflikt?"],
    students: ["Vem litar du på – och varför just hen?", "Vad skulle behöva hända för att du skulle lita på någon igen?"],
    ideas: ["Lämna över ansvar: klassuppdrag, materialvård, rastorganisation utan kontroll.", "En tillitsbana på idrotten med förbundna ögon."],
    subjects: ["Idrott och hälsa", "Klassens tid", "Alla ämnen"],
    exercise: { title: "Leda blint", text: "Två och två: en person blundar, den andra leder hen genom rummet enbart med rösten. Byt. Vad hjälpte?" } },
  { id: "c5", dim: "collaborating", name: "Mobilisering", icon: "c5-mobilisierungsfaehigkeiten",
    desc: "Förmåga att inspirera och organisera andra att engagera sig i delade intressen.",
    teacher: ["Vad entusiasmerar mig i mitt ämne – och ser klassen den entusiasmen?", "Hur vinner jag kollegor för en idé i stället för att övertala dem?"],
    students: ["Vad skulle du vilja entusiasmera andra för?", "Vem har ryckt med dig någon gång – hur gjorde hen?"],
    ideas: ["Eleverna planerar en aktion för skolan (insamling, rastkiosk, utställning) och kampanjar för den.", "Korta tal: vinn stöd för en sak på 60 sekunder."],
    subjects: ["Svenska", "Projektarbete", "Hem- och konsumentkunskap"],
    exercise: { title: "Enminuterspitch", text: "Alla väljer en liten förbättring för klassen. En minut att kampanja för den. Klassen röstar – och genomför vinnaren." } },

  { id: "a1", dim: "acting", name: "Mod", icon: "a1-mut",
    desc: "Förmåga att stå upp för sina värderingar, fatta beslut, agera kraftfullt samt, om situationen kräver, utmana och förändra existerande strukturer och synsätt.",
    teacher: ["Vad skulle jag ändra i min undervisning om jag inte var rädd för kritik?", "När invände jag senast i kollegiet?"],
    students: ["När vågade du säga något trots att det var svårt?", "Vad är skillnaden mellan modig och dumdristig?"],
    ideas: ["Samla modshistorier: barnen berättar om små modiga ögonblick – inte hjältedåd.", "Öva civilkuragescener i rollspel: vad säger jag när någon blir utskrattad?"],
    subjects: ["Etik och samhälle", "Svenska", "Drama", "Idrott och hälsa"],
    exercise: { title: "Ett litet mod", text: "Alla funderar: vad vore i dag ett litet modigt steg för mig? Skriv ned det, vik ihop lappen. I morgon: vem gjorde det?" } },
  { id: "a2", dim: "acting", name: "Kreativitet", icon: "a2-kreativitaet",
    desc: "Förmåga att generera och utveckla originella idéer, innovera samt vara villig att bryta konventionella mönster.",
    teacher: ["När fick mina elever senast göra något som inte finns än?", "Vilken uppgift ställde jag den här veckan så att bara ett svar är rätt – behövde det vara så?"],
    students: ["Hur skulle man kunna lösa det här helt annorlunda?", "Vad skulle du uppfinna om allt vore möjligt?"],
    ideas: ["Öppna uppgifter med flera lösningsvägar – särskilt i matematiken.", "Omvändningsövning: ett vardagsföremål får ett nytt syfte."],
    subjects: ["Bild", "Matematik", "Slöjd", "Musik"],
    exercise: { title: "30 cirklar", text: "Ett blad med 30 tomma cirklar. Gör på tre minuter så många som möjligt till något – boll, klocka, pizza. Kvantitet före kvalitet." } },
  { id: "a3", dim: "acting", name: "Optimism", icon: "a3-optimismus",
    desc: "Förmåga att upprätthålla och kommunicera en känsla av hopp, positiv inställning samt tilltro till möjligheten till en meningsfull förändring.",
    teacher: ["Vilken framtid förmedlar jag till min klass – en som går att forma, eller en som man måste stå ut med?", "Vad ger mig hopp i mitt yrke?"],
    students: ["Vad har blivit bättre de senaste åren?", "Vad skulle du kunna bidra med för att något ska gå bra?"],
    ideas: ["Veckans goda nyheter: eleverna undersöker vad som utvecklas positivt.", "Lösningsberättelser i stället för problemberättelser: vem har löst ett liknande problem?"],
    subjects: ["Medier och IT", "Naturkunskap och samhälle", "Svenska"],
    exercise: { title: "Ändå", text: "Var och en nämner en oro i en mening. Bänkgrannen svarar med en mening som börjar med ”Ändå…”." } },
  { id: "a4", dim: "acting", name: "Uthållighet", icon: "a4-beharrlichkeit",
    desc: "Förmåga att bibehålla engagemang och förbli beslutsam och tålmodig även när det tar lång tid innan ens ansträngningar ger resultat.",
    teacher: ["Vilket barn börjar jag i tysthet ge upp om – och vad skulle krävas för att hålla ut?", "Vilket föresats släppte jag för tidigt?"],
    students: ["Vad kan du i dag som du inte kunde förr? Hur lärde du dig det?", "Vad gör du när något inte lyckas på första försöket?"],
    ideas: ["Gör lärandet synligt: lägg arbeten från september och juni bredvid varandra.", "Ett långtidsprojekt över en termin med delmål – växter, dagbok, öva en färdighet."],
    subjects: ["Matematik", "Musik", "Idrott och hälsa", "Naturvetenskap och teknik"],
    exercise: { title: "Inte än", text: "Samla meningar med ”jag kan inte det” och lägg högt till ett ord: ”jag kan inte det än”. Vad ändrar det lilla ordet?" } }
];

export default { ui, dimensions, skills };
